### PR TITLE
Fix issue 5106

### LINKED ISSUE #5106: [BUG] Validate that routes configured in the sink exist on startup of Data Prepper
**Describe the bug**
Currently, data prepper does not validate that routes exist on startup, and even during runtime will not throw any errors.

**To Reproduce**
Create a config like

```
routes:
    - route_one: '/my_route == 10'
    - route_two: '/my_route == 11'
  sink:
    - pipeline:
        name: "sub-pipeline-1"
        routes:
          - FIRST_ROUTE
    - pipeline:
        name: "sub-pipeline-2"
        routes:
          - SECOND_ROUTE
```

None of the data will be routed to either pipeline, and there will be no errors or validations

**Expected behavior**
Throw a validation error when a route is defined in the sink that does not exist. For the above, this may look like

```
Route "FIRST_ROUTE" does not exist. Configured routes include [resources_route, resource_route]
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by saketh-pallempati**
### Description
* Added validation for sink routes in PipelineConfigurationValidator
* Added unit tests in PipelineConfigurationValidatorTest
* Added integration tests in PipelineConfigurationValidatorIT
* Routes now properly validate against defined conditional routes
 
### Issues Resolved
Resolves #5106
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by graytaylor0** [comment]
Thanks @saketh-pallempati! This change looks good. Re-ran the builds as those are failing

**Comment by saketh-pallempati** [comment]
> Thanks @saketh-pallempati! This change looks good. Re-ran the builds as those are failing

Hi @graytaylor0 

I don't see any relation to build errors and my code changes. Can you please help me out a bit to get the PR merged.

**Comment by graytaylor0** [comment]
> > Thanks @saketh-pallempati! This change looks good. Re-ran the builds as those are failing
> 
> Hi @graytaylor0
> 
> I don't see any relation to build errors and my code changes. Can you please help me out a bit to get the PR merged.

You should be able to run `./gradlew :data-prepper-core:build` to see the tests that are failing

**Comment by saketh-pallempati** [comment]
@graytaylor0 Thanks for the information will check on my end and get back

**Comment by saketh-pallempati** [comment]
Hi @graytaylor0,
I was able to run `./gradlew :data-prepper-core:build` with BUILD SUCCESSFUL.
Pushed the changes please do review.

**Review by graytaylor0 — APPROVED** [review]
Looks good!

**Comment by saketh-pallempati** [comment]
> Looks good!

@graytaylor0 Thank you

File: data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidator.java [hunk 1]
```diff
@@ -170,4 +175,35 @@ private static void validateForOrphans(
...
+        for (Map.Entry<String, PipelineConfiguration> entry : pipelineConfigurationMap.entrySet()) {
+            final String pipelineName = entry.getKey();
+            final PipelineConfiguration pipelineConfiguration = entry.getValue();
+            final Set<String> validRoutes = pipelineConfiguration.getRoutes().stream()
+                    .map(ConditionalRoute::getName)
+                    .collect(Collectors.toSet());
+
+            final List<SinkContextPluginSetting> sinkSettings = pipelineConfiguration.getSinkPluginSettings();
+            for (SinkContextPluginSetting sinkPlugin : sinkSettings) {
+                Collection<String> sinkRoutes = sinkPlugin.getSinkContext().getRoutes();
```
Comment (san81) [inline data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidator.java:196]: `sinkRoutes` could be null here?

File: data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidator.java [hunk 2]
```diff
@@ -170,4 +175,35 @@ private static void validateForOrphans(
...
+                List<String> invalidRoutes = sinkRoutes.stream()
+                        .filter(route -> !validRoutes.contains(route))
+                        .collect(Collectors.toList());
+
+                if (!invalidRoutes.isEmpty()) {
+                    throw new RuntimeException(String.format(
```
Comment (san81) [inline data-prepper-pipeline-parser/src/main/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidator.java:202]: nit: Probably, we should have introduced an `InvalidPipelineConfigurationException` or something like that.

File: data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidatorIT.java [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+import java.util.Map;
+import java.util.stream.Collectors;
+
+import static org.junit.jupiter.api.Assertions.assertThrows;
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.when;
+
+@ExtendWith(MockitoExtension.class)
+public class PipelineConfigurationValidatorIT {
+    private static final String TEST_YAML_CONFIG =
```
Comment (san81) [inline data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidatorIT.java:25]: Could you please enhance it to include the following cases
1. Simple valid pipeline with no routes configured
2. Routes configured but no routes on the sinks
3. Routes exists on the sink but no route configuration given. I think this is not a failure case but having a test case will help understand how to treat this case.

**Review by san81 — CHANGES_REQUESTED** [review]
Thank you for this nice fix. Just handling null route cases will make this fix ready to go

**Comment by saketh-pallempati** [comment]
Will work on the changes and get back. Thanks for the suggestions @san81

File: data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidatorIT.java (hunk 3 above)
Comment (saketh-pallempati) [reply data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidatorIT.java:25]: Hi @san81
I don't get the third test case you have suggested. 
The 3rd test case is the fix of the issue created which ensures and exception is thrown when a route exists on a sink but does not exist in conditional route configuration or (no route configuration given).

So I do think that's an failure case and the test case which already exists checks for that case. 

Please let me know if my thought process is work in this regard.

Comment (san81) [reply data-prepper-pipeline-parser/src/test/java/org/opensearch/dataprepper/pipeline/parser/PipelineConfigurationValidatorIT.java:25]: You are right. Ignore my 3rd point 👍

**Comment by saketh-pallempati** [comment]
Hi @san81 

I made the requried changes can you check the new commit.

**Review by san81 — DISMISSED** [review]

**Comment by san81** [comment]
@saketh-pallempati build is failing with some format violations. Please fix them

**Comment by saketh-pallempati** [comment]
> @saketh-pallempati build is failing with some format violations. Please fix them

Sorry that's an unused import error. Will submit a fix ASAP.

**Review by dlvenable — APPROVED** [review]

**Comment by dlvenable** [comment]
Thank you @saketh-pallempati !
