### PR TITLE
Fix broken DefaultKafkaClusterConfigSupplier get API

### LINKED ISSUE #3528: [BUG] NullPointer exception in DefaultKafkaClusterConfigSupplier get API
**Describe the bug**
NullPointer exception in DefaultKafkaClusterConfigSupplier get API 

**To Reproduce**
Start pipeline with the following YAML file, it crashes because the kafkaClusterConfig is null
```
kafka-pipeline:
  source:
    kafka:
      bootstrap_servers: ["localhost:9092"]
      acknowledgments: true
      encryption:
        type: none
      topics:
         - name: "TestTopic"
           group_id: "TestGroup"
  sink:
    - stdout:
```

**Expected behavior**
The pipeline should start successfully.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
Fix broken DefaultKafkaClusterConfigSupplier get API
The API doesn't check for the kafkaClusterConfig to be null or not. Modified to check for null config.

Resolves #3528 

### Issues Resolved
Resolves #3528 
 
### Check List
- [X ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dinujoh — APPROVED** [review]

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/extension/DefaultKafkaClusterConfigSupplier.java [hunk 1]
```diff
@@ -19,21 +20,21 @@ public DefaultKafkaClusterConfigSupplier(KafkaClusterConfig kafkaClusterConfig)
 
     @Override
     public List<String> getBootStrapServers() {
-        return kafkaClusterConfig.getBootStrapServers();
+        return Objects.nonNull(kafkaClusterConfig) ? kafkaClusterConfig.getBootStrapServers() : null;
```
Comment (dinujoh) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/extension/DefaultKafkaClusterConfigSupplier.java:23]: Is the Kafka source handling when these values are null ?

Comment (hshardeesi) [reply data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/extension/DefaultKafkaClusterConfigSupplier.java:23]: How about retruning empty list

**Review by hshardeesi — APPROVED** [review]

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/extension/DefaultKafkaClusterConfigSupplier.java (hunk 1 above)
Comment (dlvenable) [reply data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/extension/DefaultKafkaClusterConfigSupplier.java:23]: @dinujoh , I agree with @hshardeesi  here. Returning an empty list would be better.

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/extension/DefaultKafkaClusterConfigSupplier.java [hunk 2]
```diff
@@ -19,21 +20,21 @@ public DefaultKafkaClusterConfigSupplier(KafkaClusterConfig kafkaClusterConfig)
...
     }
 
     @Override
     public AuthConfig getAuthConfig() {
-        return kafkaClusterConfig.getAuthConfig();
+        return Objects.nonNull(kafkaClusterConfig) ? kafkaClusterConfig.getAuthConfig() : null;
```
Comment (dlvenable) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/extension/DefaultKafkaClusterConfigSupplier.java:28]: We may want to consider using `Optional<AuthConfig>` in the future.
