### PR TITLE
Fix PipelineConnector to duplicate the events

### LINKED ISSUE #1886: [BUG] Sending Events to multiple pipelines does not duplicate Events
**Describe the bug**

Data Prepper supports creating a pipeline which uses the pipeline sink to send events to multiple downstream pipelines. However, the Event is not being copied. Thus, the same Event object is passed into multiple threads. This produces unexpected behavior.

**To Reproduce**

Create a pipeline which modifies an Event in a downstream pipeline.

**Expected behavior**

Modifying an Event in one pipeline should not modify it in others. The `PipelineConnector` should duplicate the Events.

**Additional context**

The `Event` model contains metadata, making it hard to "copy" an event. We solved this in peer-forwarder with a quick fix which is can be seen in [this PR](https://github.com/opensearch-project/data-prepper/pull/1865/files#diff-0e97029518f91e331458a8a579d81237b6d2175edb0041a0c2ec119490db4cf9R116-R127). However, this approach is not highly extensible since it requires a lot of knowledge duplicated throughout the code.

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
This fix resolves the issue reported in the bug https://github.com/opensearch-project/data-prepper/issues/1886. This bug is about some pipeline processors not duplicating the events before modifying them. And that was causing wrong behavior when a pipeline is split into two parallel pipelines.

When pipeline1 has two sinks pipeline2 and pipeline3 and pipeline2 is just doing grok match and pipeline3 is doing string substitution, both the pipelines will see the string substitution because same event is used in both cases. 
Fix is to make a copy of the event whenever an event is modified.

Added a new end-to-end test case that was failing without the fix and verified that the test case is passing with the fix.
                                           
 
### Issues Resolved
Resolves #1886
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dlvenable — CHANGES_REQUESTED** [review]
@kkondaka , Thank you for contributing this fix.

The fundamental problem with #1886 is with routing events to multiple downstream pipelines. Once an Event is in a pipeline, it should be mutated and not copied. We'd have to perform a copy for every processor which updates Events if we took the approach of copying in the processors.

Data Prepper has a class named `PipelineConnector` which routes events from one pipeline to one or multiple downstream pipelines. I believe we should copy the Event in that class and not in the Processors.

You can see the moment that the Event goes into a new pipeline in the following snippet:

https://github.com/opensearch-project/data-prepper/blob/7901643baccc5e75675eb578362e2ea587a5ca9a/data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java#L59

We should perform the copy there.

Also, when copying an Event please use an approach similar to the following.

https://github.com/opensearch-project/data-prepper/blob/7901643baccc5e75675eb578362e2ea587a5ca9a/data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderHttpService.java#L117-L127

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java [hunk 1]
```diff
@@ -54,6 +56,21 @@ public void stop() {
     public void output(final Collection<T> records) {
         if (buffer != null && !isStopRequested.get()) {
             for (T record : records) {
+		if(record.getData() instanceof Event) {
+		    try {
+		        final Event recordEvent = (Event)record.getData();
+			Event newRecordEvent = JacksonEvent.builder()
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java:62]: This will not work for Trace events. Please take a similar approach to the following here:

https://github.com/opensearch-project/data-prepper/blob/7901643baccc5e75675eb578362e2ea587a5ca9a/data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/server/PeerForwarderHttpService.java#L117-L127

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java [hunk 2]
```diff
@@ -54,6 +56,21 @@ public void stop() {
     public void output(final Collection<T> records) {
         if (buffer != null && !isStopRequested.get()) {
             for (T record : records) {
+		if(record.getData() instanceof Event) {
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java:59]: It could be good to add some unit tests for this in `PipelineConnectorTest`.

**Review by dlvenable — CHANGES_REQUESTED** [review]
Thanks for making the change to use `PipelineConnector`! I have a couple other comments.

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java (hunk 2 above)
Comment (kkondaka) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java:59]: Will do

Comment (kkondaka) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java]: Added test case and updated diffs

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java [hunk 3]
```diff
@@ -54,6 +57,32 @@ public void stop() {
     public void output(final Collection<T> records) {
         if (buffer != null && !isStopRequested.get()) {
             for (T record : records) {
+		if(record.getData() instanceof JacksonSpan) {
+		    try {
+		        final JacksonSpan span = (JacksonSpan)record.getData();
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java:62]: You should be able use just `Span` here.

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java [hunk 4]
```diff
@@ -54,6 +57,32 @@ public void stop() {
...
+			JacksonSpan newSpanEvent = JacksonSpan.builder()
+			          .withJsonData(span.toJsonString())
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java:64]: This should be `withData(recordEvent.toMap())` similar to line 76 below.

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineConnectorTest.java [hunk 5]
```diff
@@ -78,6 +184,42 @@ public void testOutputSuccess() throws Exception {
...
+        eut.output(eventRecordList);
+
+	Map.Entry<Collection<Record<Event>>, CheckpointState> ent = eventBuffer.read(1);
+	ArrayList<Record<Event>> records = new ArrayList<>(ent.getKey());
+	// Make sure the records are different
+	Assertions.assertNotEquals(eventRecordList.get(0),  records.get(0));
+	// Make sure the events are different
+	Event event1 = eventRecordList.get(0).getData();
+	Event event2 = records.get(0).getData();
+	Assertions.assertNotEquals(event1, event2);
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineConnectorTest.java:200]: It would be clearer (and more accurate) to assert these are not the same instance.

```
assertThat(event1, not(sameInstance(event2));
```

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineConnectorTest.java [hunk 6]
```diff
@@ -78,6 +184,42 @@ public void testOutputSuccess() throws Exception {
...
+        sput.output(spanRecordList);
+
+	Map.Entry<Collection<Record<JacksonSpan>>, CheckpointState> ent = spanBuffer.doRead(10000);
+	ArrayList<Record<JacksonSpan>> records = new ArrayList<>(ent.getKey());
+	// Make sure the records are different
+	Assertions.assertNotEquals(spanRecordList.get(0),  records.get(0));
+	// Make sure the spans are different
+	JacksonSpan span1 = spanRecordList.get(0).getData();
+	JacksonSpan span2 = records.get(0).getData();
+	Assertions.assertNotEquals(span1, span2);
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineConnectorTest.java:220]: Similar comment as above - assert they are not the same instance.

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineConnectorTest.java [hunk 7]
```diff
@@ -78,6 +184,42 @@ public void testOutputSuccess() throws Exception {
...
+    }
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/PipelineConnectorTest.java:221]: This test should assert that the values are the same. Similar to your other test (lines 201-203).

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java (hunk 4 above)
Comment (dlvenable) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/PipelineConnector.java:64]: As it is not obvious, the `toMap` method returns a converted value. So it is not returning the same `Map` object as is help by the original `Event`.

**Comment by dlvenable** [comment]
@kkondaka , I believe this is almost ready.

You do have some unused imports, which our checkstyle rules prohibit. See the logs here for guidance: https://github.com/opensearch-project/data-prepper/actions/runs/3230696086/jobs/5300610638

Also, we should run that new end-to-end test. I commented above about how to make it run in GitHub. With that change, we should be able to verify it before merging.

Thanks!

File: .github/workflows/data-prepper-log-analytics-basic-grok-e2e-tests.yml [hunk 8]
```diff
@@ -26,4 +27,4 @@ jobs:
       - name: Checkout Data-Prepper
         uses: actions/checkout@v2
       - name: Run basic grok end-to-end tests with Gradle
-        run: ./gradlew -PendToEndJavaVersion=${{ matrix.java }} :e2e-test:log:basicLogEndToEndTest
\ No newline at end of file
+        run: ./gradlew -PendToEndJavaVersion=${{ matrix.java }} :e2e-test:log:${{ test }}
```
Comment (dlvenable) [inline .github/workflows/data-prepper-log-analytics-basic-grok-e2e-tests.yml:30]: This was my mistake. Please change `test` to `matrix.test`.

```
run: ./gradlew -PendToEndJavaVersion=${{ matrix.java }} :e2e-test:log:${{ matrix.test }}
```

**Review by dlvenable — CHANGES_REQUESTED** [review]

**Review by dlvenable — APPROVED** [review]
Thanks for your work in fixing this bug!

One of the tests is failing, but I believe that is because it is a compatibility test which might not work since 2.0. We can ignore that failure.
