### PR TITLE
Parquet codec tests fix

### LINKED ISSUE #3992: [BUG] ParquetOutputCodecTest may not be testing correctly
**Describe the bug**

I removed some try-catch lines in the `ParquetOutputCodecTest` test. These tests began to fail.

Something is definitely wrong as the lines in question are part of the setup. It may be that the tests are not actually testing what they claim to test.

**To Reproduce**

Remove these lines:

https://github.com/opensearch-project/data-prepper/blob/c4acf28be243b2fad676ba9863250c673be06d70/data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java#L576-L578

https://github.com/opensearch-project/data-prepper/blob/c4acf28be243b2fad676ba9863250c673be06d70/data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java#L584-L585

Run the tests.

Quite a few of them fail.

**Expected behavior**

I should be able to run tests without this code throwing exceptions at all.

**Additional context**

This was found while removing `ex.printStackTrace()` lines:

https://github.com/opensearch-project/data-prepper/pull/3991/files#r1459559030

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
Fix Parquet output codec tests
 
### Issues Resolved
Resolves #3992
 
### Check List
- [X ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java [hunk 1]
```diff
@@ -115,11 +117,11 @@ void test_happy_case(final int numberOfRecords) throws Exception {
             parquetOutputCodec.writeEvent(event, outputStream);
         }
         parquetOutputCodec.complete(outputStream);
-        List<Map<String, Object>> actualRecords = createParquetRecordsList(new ByteArrayInputStream(tempFile.toString().getBytes()));
+        List<Map<String, Object>> actualRecords = createParquetRecordsList(new FileInputStream(tempFile));
```
Comment (dlvenable) [inline data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java:120]: We need assertions on all of these to verify the size. Otherwise, the loop below will not assert anything.

```
assertThat(actualRecords.size(), equalTo(inputMaps.size()));
```

File: data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java [hunk 2]
```diff
@@ -567,15 +595,33 @@ private List<Map<String, Object>> createParquetRecordsList(final InputStream inp
...
+                                            break;
+                                case "myDouble": value = simpleGroup.getDouble(fieldIndex, 0);
+                                            break;
+                                case "myArray": value = extractStringList(simpleGroup, "myArray");
+                                            break;
+                                case "nestedRecord": value = extractNestedGroup(simpleGroup, "nestedRecord");
+                                            break;
+                                default: throw new IllegalArgumentException("Unknown field");
+                            }
+                        } catch (RuntimeException e) {continue;}
```
Comment (dlvenable) [inline data-prepper-plugins/s3-sink/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/ParquetOutputCodecTest.java:623]: I think we should remove this try-catch. Just let the exception propagate up.

Relatedly, there is an exception below. Can you remove it?

```
} catch (Exception parquetException) {
            LOG.error("Failed to parse Parquet", parquetException);
```

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: .github/workflows/static.yml [hunk 3]
```diff
@@ -0,0 +1,43 @@
+# Simple workflow for deploying static content to GitHub Pages
```
Comment (dlvenable) [inline .github/workflows/static.yml:1]: I think this was from a concept you were working. This commit shouldn't be in this branch.

**Comment by dlvenable** [comment]
Your DCO is failing.

**Review by graytaylor0 — APPROVED** [review]

**Review by dlvenable — APPROVED** [review]
