### PR TITLE
Fix class cast exception for lambda processor

### LINKED ISSUE #6054: [BUG] Lambda Processor ClassCastException with Aggregate Processor
## Bug Description
Lambda processor throws `ClassCastException` when processing events from aggregate processor with `response_events_match: false`.

## Error Details
```
ERROR org.opensearch.dataprepper.plugins.lambda.processor.LambdaProcessor - null java.lang.ClassCastException
```

**Location:** `AggregateResponseEventHandlingStrategy.java`
```
DefaultEventHandle eventHandle = (DefaultEventHandle) originalEvent.getEventHandle();
```

## Root Cause
1. Aggregate processor creates events with `AggregateEventHandle`
2. Lambda processor with `response_events_match: false` uses `AggregateResponseEventHandlingStrategy`
3. Strategy attempts to cast `AggregateEventHandle` to `DefaultEventHandle` - fails

## Reproduction
```yaml
- aggregate:
    identification_keys: ["key"]
    action:
      put_all: {}
- aws_lambda:
    function_name: 'test-function'
    response_events_match: false  # Triggers AggregateResponseEventHandlingStrategy
```

## Workaround
Option1: Set `response_events_match: true` to use `StrictResponseEventHandlingStrategy` instead.
Option2: Dont use aggregate processor before lambda processor.

## Proposed Fix
Replace unsafe cast with type check.
```java
...
if (handle instanceof DefaultEventHandle) {
    DefaultEventHandle eventHandle = (DefaultEventHandle) handle;
    ...
}
```

### PR DESCRIPTION
**Pull request by srikanthjg**
### Issues Resolved
Resolves #6054 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java [hunk 1]
```diff
@@ -1428,6 +1431,25 @@ private Record<Event> createLargeRecord(final int sizeInBytes) {
...
+        AggregateEventHandle aggregateHandle = new AggregateEventHandle(Instant.now());
+        
+        when(mockEvent.getEventHandle()).thenReturn(aggregateHandle);
+        when(mockRecord.getData()).thenReturn(mockEvent);
+
+        AggregateResponseEventHandlingStrategy strategy = new AggregateResponseEventHandlingStrategy();
+        List<Event> parsedEvents = Collections.emptyList();
+        List<Record<Event>> originalRecords = Collections.singletonList(mockRecord);
+
+        assertDoesNotThrow(() -> {
```
Comment (dlvenable) [inline data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java:1451]: Rather than making this test oriented around this not throwing, we should be testing the desired behavior when it is an `AggregateEventHandle`.

Use Mockito to verify this interaction:

```
aggregateHandle.addEventHandle(responseEvent.getEventHandle());
```

File: data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java [hunk 2]
```diff
@@ -1428,6 +1431,25 @@ private Record<Event> createLargeRecord(final int sizeInBytes) {
         return new Record<>(event);
     }
 
+    @Test
+    void testNoClassCastExceptionWithAggregateEventHandle() {
```
Comment (dlvenable) [inline data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java]: Rename this test to say what should happen, not just what shouldn't happen.

File: data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/AggregateResponseEventHandlingStrategy.java [hunk 3]
```diff
@@ -6,36 +6,55 @@
...
         for (Event responseEvent : parsedEvents) {
-            // Create a new record for the parsed response event
             Record<Event> newRecord = new Record<>(responseEvent);
             resultRecords.add(newRecord);
+        }
 
-            // Add the new event to ack set, older event will be released by core later
-            if (originalAcknowledgementSet != null) {
-                originalAcknowledgementSet.add(responseEvent);
+        if (handle instanceof DefaultEventHandle) {
```
Comment (dlvenable) [inline data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/AggregateResponseEventHandlingStrategy.java:39]: I think there is probably a better way to handle this. If we have other `EventHandle` implementations this will fail.

You are doing this in order to call `getAcknowledgementSet()`. Perhaps we should have interfaces for `SingleAcknowledgementSetEventHandle` and `MultipleAcknowledgementSetEventHandle`? Or would a collection of `AcknowledgementSet` on the base `EventHandle` interface be appropriate?

I'm not sure we need to handle this in this PR, but we should consider something more robust.

File: data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java (hunk 1 above)
Comment (srikanthjg) [reply data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java:1451]: Fixed and addressed it.

File: data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java (hunk 2 above)
Comment (srikanthjg) [reply data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java]: Fixed and addressed it.

File: data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/AggregateResponseEventHandlingStrategy.java (hunk 3 above)
Comment (srikanthjg) [reply data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/AggregateResponseEventHandlingStrategy.java:39]: yes i agree. I can look into this in another followup PR.
