### PR TITLE
Fix for kafka source issue #3247 (offset commit stops on deserialization error)

### LINKED ISSUE #3247: [BUG] Kafka source stops committing offsets after consuming a record that results in deserialization error
**Describe the bug**
With acknowledgments enabled, if KafkaConsumer encounters deserialization error while consuming a record then kafka source plugin stops committing offsets for that partition. Subsequent records are consumed and pushed to sink, but committed offset remains stuck on the offset one before the record that encountered deserialization exception.

**To Reproduce**
- Create kafka topic and ingest json records.
- Create pipeline with kafka source and "json" as serde_format
- Send one text (non-json) record to the topic.
- Deserialization exception will be thrown in pipeline.
- Describe kafka consumer group on kafka cluster to observe partition LAG/committed offsets.
- Any further records sent to the error partition will not result in new offsets being committed and LAG will remain non-zero.

**Expected behavior**
Failed records should not result in stuck committed offsets, commits should resume after accounting error records in NumberOfDeserializationErrors metric. (In future, failed records can be sent to source/pipeline level dlq if available)

### PR DESCRIPTION
**Pull request by hshardeesi**
### Description
- Fixed CommitTracker to track err offsets that failed to deserialize
-  Added ratelimiter for err logs to avoid flooding logs in case of unexpected err condition.

### Issues Resolved
Resolves #3247

### CODE REVIEW

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java [hunk 1]
```diff
@@ -176,19 +180,42 @@ public <T> void consumeRecords() throws Exception {
...
             Thread.sleep(10000);
         } catch (RecordDeserializationException e) {
-            LOG.warn("Deserialization error - topic {} partition {} offset {}",
-                    e.topicPartition().topic(), e.topicPartition().partition(), e.offset());
+
+            LOG.warn("Deserialization error - topic {} partition {} offset {}. Error message: {}",
+                    e.topicPartition().topic(), e.topicPartition().partition(), e.offset(), e.getMessage());
             if (e.getCause() instanceof AWSSchemaRegistryException) {
-                LOG.warn("AWSSchemaRegistryException: {}. Retrying after 30 seconds", e.getMessage());
+                LOG.warn("Retrying after 30 seconds");
```
Comment (graytaylor0) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:187]: Why would we not want to show the exception message here?

**Review by graytaylor0 — DISMISSED** [review]

File: data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/LogRateLimiterTest.java [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+@ExtendWith(MockitoExtension.class)
+public class LogRateLimiterTest {
+
+    @Test
+    public void testRateLimiter() {
+        long currentMs = System.currentTimeMillis();
+        LogRateLimiter objUnderTest = new LogRateLimiter(10, currentMs);
+        assertThat(objUnderTest.isAllowed(currentMs), equalTo(true));
+        assertThat(objUnderTest.isAllowed(currentMs), equalTo(false));
+        currentMs += 50;
```
Comment (dlvenable) [inline data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/util/LogRateLimiterTest.java:20]: Thank you for manipulating instead of sleeping!

I've made a number of test changes to reduce sleeps that exist in our tests and slow down the build.

File: data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java [hunk 3]
```diff
@@ -296,10 +295,68 @@ public void testJsonConsumeRecords() throws InterruptedException, Exception {
...
+                testMap1.forEach((k, v) -> assertThat(eventMap, hasEntry(k,v)));
+            }
+            if (kafkaKey.equals(testKey2)) {
+                testMap2.forEach((k, v) -> assertThat(eventMap, hasEntry(k,v)));
+            }
+            event.getEventHandle().release(true);
+        }
+        // Wait for acknowledgement callback function to run
+        try {
+            Thread.sleep(10000);
```
Comment (dlvenable) [inline data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java:341]: Can we lower this sleep?

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java (hunk 1 above)
Comment (dlvenable) [reply data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:187]: It is logged on line 185 now.

**Review by dlvenable — DISMISSED** [review]

File: data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java (hunk 3 above)
Comment (hshardeesi) [reply data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java:355]: This would require some change and mocking acknowledgement methods. I'll look into it, we'll probably take it as separate task.

**Review by dlvenable — APPROVED** [review]

File: data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java (hunk 3 above)
Comment (dlvenable) [reply data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java:355]: @hshardeesi , Can you create a GitHub issue to track this?

**Review by JonahCalvo — APPROVED** [review]

**Review by asifsmohammed — APPROVED** [review]

File: data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java (hunk 3 above)
Comment (hshardeesi) [reply data-prepper-plugins/kafka-plugins/src/test/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumerTest.java:355]: https://github.com/opensearch-project/data-prepper/issues/3263
