### PR TITLE
Caffeine-based caching parser for the user_agent processor

### LINKED ISSUE #4618: [BUG] The user_agent processor throws exceptions with multiple threads.
**Describe the bug**

I'm seeing a number of errors such as:

```
2024-06-05T20:54:54.420 [my-pipeline-processor-worker-1-thread-2] ERROR org.opensearch.dataprepper.plugins.processor.useragent.UserAgentProcessor - An exception occurred when parsing user agent data from event [******] with source key [******]
java.lang.IllegalStateException: Entry.next=null, data[removeIndex]=***
 previous=***
 key=***
 size=1000 maxSize=1000 This should not occur if your keys are immutable, and you have used synchronization properly.
 at org.apache.commons.collections4.map.LRUMap.reuseMapping(LRUMap.java:384) ~[commons-collections4-4.4.jar:4.4]
 at org.apache.commons.collections4.map.LRUMap.addMapping(LRUMap.java:349) ~[commons-collections4-4.4.jar:4.4]
 at org.apache.commons.collections4.map.AbstractHashedMap.put(AbstractHashedMap.java:289) ~[commons-collections4-4.4.jar:4.4]
 at ua_parser.CachingParser.parseUserAgent(CachingParser.java:92) ~[uap-java-1.6.1.jar:?]
 at ua_parser.Parser.parse(Parser.java:83) ~[uap-java-1.6.1.jar:?]
 at ua_parser.CachingParser.parse(CachingParser.java:72) ~[uap-java-1.6.1.jar:?]
 at org.opensearch.dataprepper.plugins.processor.useragent.UserAgentProcessor.doExecute(UserAgentProcessor.java:51) ~[user-agent-processor-2.x.88.jar:?]
 at org.opensearch.dataprepper.model.processor.AbstractProcessor.lambda$execute$0(AbstractProcessor.java:54) ~[data-prepper-api-2.x.88.jar:?]
 at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:69) ~[micrometer-core-1.13.0.jar:1.13.0]
 at org.opensearch.dataprepper.model.processor.AbstractProcessor.execute(AbstractProcessor.java:54) ~[data-prepper-api-2.x.88.jar:?]
```

**To Reproduce**

It is not very easy to reproduce this consistently.

1. Create a pipeline with the `user_agent` processor.
2. Be sure to have multiple workers in the pipeline.
3. Ingest a significant volume of data
4. These errors should occur.

**Expected behavior**

No errors, and cache works.

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

Adds and uses a Caffeine-based caching parser for the `user_agent` processor. Also, adds a Gradle version catalog for Caffeine since we now use it in three projects.
 
### Issues Resolved

Resolves #4618
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has a documentation issue. Please link to it in this PR.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+    private final Cache<String, Client> clientCache;
+    private final Cache<String, UserAgent> userAgentCache;
+    private final Cache<String, Device> deviceCache;
+    private final Cache<String, OS> osCache;
+
+    /**
+     * Constructs a new instance with a given cache size.
+     *
+     * @param cacheSize The size of the cache as a count of items.
+     */
```
Comment (KarstenSchnitter) [inline data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java:31]: This is misleading. It creates four caches of the given size. Is this intended? It will use more memory because of this.

File: data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+        return parseCaching(agentString, osCache, super::parseOS);
+    }
+
+    private <T> T parseCaching(
+            final String agentString,
+            final Cache<String, T> cache,
+            final Function<String, T> parseFunction) {
+        if (agentString == null) {
+            return null;
+        }
```
Comment (KarstenSchnitter) [inline data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java:65]: Is this different or faster from what Caffeine would return?

File: data-prepper-plugins/user-agent-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParserTest.java [hunk 3]
```diff
@@ -0,0 +1,158 @@
...
+        assertThat(objectUnderTest.parse(new String(userAgentString)), sameInstance(client));
+        assertThat(objectUnderTest.parse(new String(userAgentString)), sameInstance(client));
+        assertThat(objectUnderTest.parse(new String(userAgentString)), sameInstance(client));
+    }
+
+    @Test
+    void parseUserAgent_returns_expected_results() {
+        final CaffeineCachingParser objectUnderTest = createObjectUnderTest();
+
+        final UserAgent userAgent = objectUnderTest.parseUserAgent(KNOWN_USER_AGENT_STRING);
```
Comment (KarstenSchnitter) [inline data-prepper-plugins/user-agent-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParserTest.java:71]: This could be inline like the first test case `parse_returns_expected_results`.

File: data-prepper-plugins/user-agent-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParserTest.java [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+        assertThat(objectUnderTest.parseUserAgent(new String(userAgentString)), sameInstance(userAgent));
+        assertThat(objectUnderTest.parseUserAgent(new String(userAgentString)), sameInstance(userAgent));
+        assertThat(objectUnderTest.parseUserAgent(new String(userAgentString)), sameInstance(userAgent));
+    }
+
+    @Test
+    void parseDevice_returns_expected_results() {
+        final CaffeineCachingParser objectUnderTest = createObjectUnderTest();
+
+        final Device device = objectUnderTest.parseDevice(KNOWN_USER_AGENT_STRING);
```
Comment (KarstenSchnitter) [inline data-prepper-plugins/user-agent-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParserTest.java:102]: This could be inline like the first test case `parse_returns_expected_results`.

File: data-prepper-plugins/user-agent-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParserTest.java [hunk 5]
```diff
@@ -0,0 +1,158 @@
...
+        assertThat(objectUnderTest.parseDevice(new String(userAgentString)), sameInstance(device));
+        assertThat(objectUnderTest.parseDevice(new String(userAgentString)), sameInstance(device));
+        assertThat(objectUnderTest.parseDevice(new String(userAgentString)), sameInstance(device));
+    }
+
+    @Test
+    void parseOS_returns_expected_results() {
+        final CaffeineCachingParser objectUnderTest = createObjectUnderTest();
+
+        final OS os = objectUnderTest.parseOS(KNOWN_USER_AGENT_STRING);
```
Comment (KarstenSchnitter) [inline data-prepper-plugins/user-agent-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParserTest.java:132]: This could be inline like the first test case parse_returns_expected_results`.

**Review by KarstenSchnitter — COMMENTED** [review]
Looks good to me. Only minor comments.

**Comment by dlvenable** [comment]
> Looks great! Thanks for catching and addressing the bug. Were you able to verify that with this change the issue in #4618 no longer exists?

Yes, I did verify this. See PR #4620 where I added a quick solution to generate a large volume of requests with user agent strings. You can also see my reproduction steps here: https://github.com/opensearch-project/data-prepper/issues/4618#issuecomment-2163321593

I ran these tests without the changes. I received the errors. Then ran with my changes and saw no errors for user agent.

File: data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java (hunk 1 above)
Comment (dlvenable) [reply data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java]: This is the current behavior of the `CachingParser`. I followed it for consistency.

https://github.com/ua-parser/uap-java/blob/61ffd25de944bbe634ff5180104c9cdc07faad29/src/main/java/ua_parser/CachingParser.java#L30-L33

I did update the Javadoc to explain more.

File: data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java (hunk 2 above)
Comment (dlvenable) [reply data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java:66]: This is what the `CachingParser` does already.

https://github.com/ua-parser/uap-java/blob/61ffd25de944bbe634ff5180104c9cdc07faad29/src/main/java/ua_parser/CachingParser.java#L62-L64

Also, we can avoid storing `null` in the cache.

**Review by oeyh — APPROVED** [review]

File: data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java (hunk 2 above)
Comment (KarstenSchnitter) [reply data-prepper-plugins/user-agent-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/useragent/CaffeineCachingParser.java:66]: Caffeine does not store null values: https://github.com/ben-manes/caffeine/issues/118#issuecomment-243057017. This is also my experience with it. In one of my projects I had to work around this. But here we are checking the key not to be null, right? If we didn't, this would create an NPE. So I think, this is totally fine.

**Review by KarstenSchnitter — APPROVED** [review]
Looks good. Thanks for providing the change.
