### PR TITLE
Fix boolean conversion and integer conversion bug for Logstash configuration converter attributes

### LINKED ISSUE #762: [BUG] LogstashConfigurationConverter converts Logstash.conf booleans to strings in the Data Prepper pipeline.yaml
**Describe the bug**
* Right now, a boolean logstash value (which can only contain `true` or `false` with no quotes) will be converted to a string in the converted pipeline.yaml. For example,
```
grok => { break_on_match => true } 
```

converts to 
```
grok:
   break_on_match: "true"
```

while it should convert to 

```
grok:
   break_on_match: true
```

* Integration tests for the Logstash configuration converter do not contain any boolean conversions. These should be added as well.

### PR DESCRIPTION
**Pull request by graytaylor0**
Signed-off-by: Taylor Gray <33740195+graytaylor0@users.noreply.github.com>

### Description
* Fixes bug where Logstash booleans were converted to strings in the converted pipeline.yaml
* Fixes bug where Logstash integers were being converted to doubles in the converted pipeline.yaml
 
### Issues Resolved
Closes #762 
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java [hunk 1]
```diff
@@ -96,11 +96,22 @@ else if (attributeContext.value().getChild(0) instanceof LogstashParser.PluginCo
         }
         else if (attributeContext.value().NUMBER() != null && attributeContext.value().getText().equals(attributeContext.value().NUMBER().toString())) {
             logstashValueType = LogstashValueType.NUMBER;
-            value = Double.valueOf(attributeContext.value().getText());
+            try {
+                value = Integer.parseInt(attributeContext.value().getText());
+            } catch (NumberFormatException e) {
+                try {
+                    value = Double.parseDouble(attributeContext.value().getText());
+                } catch (NumberFormatException exception) {
```
Comment (asifsmohammed) [inline data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java:104]: I think we should throw `LogstashParsingException` here to indicate that .conf is not valid because number should either be an Integer or Double.

File: data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java [hunk 2]
```diff
@@ -96,11 +96,22 @@ else if (attributeContext.value().getChild(0) instanceof LogstashParser.PluginCo
...
+
+                }
+            }
         }
         else if (attributeContext.value().BAREWORD() != null && attributeContext.value().getText().equals(attributeContext.value().BAREWORD().toString())) {
             logstashValueType = LogstashValueType.BAREWORD;
             value = attributeContext.value().getText();
+            if (value.toString().equals("true") || value.toString().equals("false")) {
```
Comment (dlvenable) [inline data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java:112]: Should we do a case-insensitive equality here? If Logstash does that, I'd like to as well. But, if the values must be all lowercase, then what you have is perfect.

File: data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java (hunk 1 above)
Comment (graytaylor0) [reply data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java:104]: Seems like a good idea.

File: data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java (hunk 2 above)
Comment (graytaylor0) [reply data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java:112]: Logstash only supports all lowercase `true` or `false`

Comment (dlvenable) [reply data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java:112]: Thanks for confirming that!

Comment (dlvenable) [inline data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java:112]: Does this have a unit test?

Comment (graytaylor0) [reply data-prepper-logstash-configuration/src/main/java/org/opensearch/dataprepper/logstash/parser/ModelConvertingLogstashVisitor.java:112]: Added

**Review by dlvenable — APPROVED** [review]

**Review by asifsmohammed — APPROVED** [review]
LGTM. Thanks Taylor
