### PR TITLE
[2263] adding versioning property to pipeline yaml configuration

### LINKED ISSUE #2263: Support a version property in pipeline YAML configurations
## Problem

Pipeline configurations may change between major versions of Data Prepper. It can be useful to know what version of Data Prepper a given pipeline configuration was written to support and tested against.

## Proposal

Provide a pipeline definition version property in the pipeline configuration file. Specifically in the YAML, this would be a new property: `version`.

Example:

```
version: 2
otel-trace-pipeline:
  source:
    otel_trace_source:
  buffer:
  sink:
    ...
raw-pipeline:
  source:
    ..
  sink:
    ...
service-map-pipeline:
  source:
    ...
  sink:
    ...
```

The `version` can support strings in either forms:
* `${major}` (e.g. `2`)
* `${major}.${minor}` (e.g. `2.2`)

As patch versions of Data Prepper only provide bug fixes, there should be no need to include patch versions in the `version`.

Data Prepper would read the pipeline definition version and compare its current version against the definition supplied. Data Prepper will only report an error to users if the pipeline definition version represents a future version of Data Prepper.

If the pipeline definition version is older, Data Prepper will attempt to parse the configuration. It may not succeed if the major version is different and there are breaking changes reflected in the pipeline. Because a pipeline that works on 2.x may still run on 3.x, Data Prepper should at least attempt to parse it.

### Not in scope

Data Prepper could support a mechanism for reading older pipeline definition files. For example Data Prepper 3.x could read and understand breaking changes from 2.x pipelines. This proposal does not include any such attempts at keeping pipeline files operational indefinitely. This may add friction to further development of new features.

### Alternative names

I considered some other names.
* `definition_version` - This might clearly indicate that it is for the pipeline definition, but may be too verbose.
* `pipeline_version` - Even more that `version` this sounds like it is a version of the pipeline itself.
* `pipeline_definition_version` - This is accurate, but possibly too verbose.

### Alternative form

The current syntax of the pipeline YAML is a key-value map of `pipelineName:pipelineBody`. This would change that structure by adding a new key at the top: `version: ${version}`.

An alternative would be to create a modified structure:

```
version:
pipelines:
  entry-pipeline:
    ...
  raw-pipeline:
    ...
  service-map-pipeline:
    ...
```

This would break all existing pipeline YAML files. I do not believe we should take this alternative YAML.

There is the possibility that somebody has a pipeline named `version`. In which case, such a pipeline would fail to run with this change. As this is not highly likely, I suggest that we move forward with supporting existing pipelines which do not use `version` in the name.

## Additional questions

Data Prepper has a core syntax as expressed in [PipelinesDataFlowModel](https://github.com/opensearch-project/data-prepper/blob/c797d5cb85f5b7a02b8ff325846ee12f6be71904/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/PipelinesDataFlowModel.java). Data Prepper also has a set of built-in plugins. Should the version indicate only the pipeline syntax or also the available plugins for a given version? If the latter, how would we account for extracting plugins out of Data Prepper (see #321).

### PR DESCRIPTION
**Pull request by cmanning09**
### Description
Adding data prepper version as part of the pipeline configuration file. This PR creates a new `DataPrepperVersion` model in the API that is used in the `PipelinesDataFlowModel`. Added support for validating the current version is compatible with the current version of data prepper. Updated the documentation.
 
### Issues Resolved
- resolves #2263 
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by asuresh8 — DISMISSED** [review]

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
+package org.opensearch.dataprepper.model.configuration;
+
+import java.util.Objects;
+import java.util.Optional;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+public class DataPrepperVersion {
```
Comment (asuresh8) [inline data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java:8]: Did we decide on whether this was specifying the underlying version of DataPrepper or the config version?

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+            if (!this.minorVersion.equals(o.getMinorVersion().get())) {
+                return this.minorVersion > o.getMinorVersion().get();
+            }
+        }
+
+        return true;
+    }
+
+    @Override
+    public boolean equals(Object o) {
```
Comment (dlvenable) [inline data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java:85]: We should also have an implementation for hashCode.

File: data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/PipelinesDataFlowModelTest.java [hunk 3]
```diff
@@ -60,6 +64,28 @@ void testSerializing_PipelinesDataFlowModel_empty_Plugins_with_nonEmpty_delay_an
         assertThat(serializedString, equalTo(expectedYaml));
     }
 
+    @Test
+    void testSerializing_PipelinesDataFlowModel_with_Version() throws JsonProcessingException {
```
Comment (dlvenable) [inline data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/PipelinesDataFlowModelTest.java:68]: Thank you for adding new test cases (rather than modifying existing YAML files).

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java (hunk 1 above)
Comment (asuresh8) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java:8]: Yeah actually after thinking about this some more. I don't think it makes sense to have a DataPrepper version in the YAML the version is going to be whatever version the binary you are using is. The versioning should be the versioning of the config. I.e. the first check in the config file should be for the version. If the version is specified, then use the appropriate java class to deserialize the config into.

**Review by dlvenable — CHANGES_REQUESTED** [review]
Looks great! I just have a couple of requests to change.

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java (hunk 1 above)
Comment (cmanning09) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java:8]: Happy to change the internal class name. Right now every major and minor version of Data Prepper signifies a change in pipeline configuration. We have been using one version for the application and configuration. Adding support for configuration allows will give us the option to break these apart in the future. The validation checks are super simple at the moment. 

RE: deserializing different config objects based on the version - I am not sure we want to do that at this time. We don't have a need to support nor different config versions right now. I am not sure its in our best interest to support this either. That will become very difficult to maintain.

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java (hunk 2 above)
Comment (cmanning09) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java:85]: Can do!

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java [hunk 4]
```diff
@@ -0,0 +1,101 @@
+package org.opensearch.dataprepper.model.configuration;
+
+import java.util.Objects;
+import java.util.Optional;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+public class DataPrepperVersion {
+    private static final String CURRENT_VERSION = "2.1";
```
[the remark this answers is not in the document]
Comment (cmanning09) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java:9]: Can do!

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java (hunk 1 above)
Comment (asuresh8) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java:8]: So whenever we do a version bump on Data Prepper, this file will be updated?

**Comment by cmanning09** [comment]
@dlvenable - one follow up. I just want to clarify. Should Data Prepper version 2.0  be comparable with 1.5? I think I missed this in the original issue and want to understand if we truly want to support this. Is the intention here to ease migration to the latest version?

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java (hunk 1 above)
Comment (cmanning09) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/DataPrepperVersion.java:8]: Yes, that is the plan: https://github.com/opensearch-project/data-prepper/pull/2292#discussion_r1112321785

**Review by asuresh8 — APPROVED** [review]

**Comment by dlvenable** [comment]
> @dlvenable - one follow up. I just want to clarify. Should Data Prepper version 2.0 be comparable with 1.5? I think I missed this in the original issue and want to understand if we truly want to support this. Is the intention here to ease migration to the latest version?

Yes, I think it should be compatible. In any major version we should have migration fields to help with migrations. So a pipeline created for 1.5 could be compatible for 2.0. But, not always. I think more importantly, a 3.0 pipeline should not run on 2.x.

**Review by dlvenable — APPROVED** [review]
