### PR TITLE
Bug Fix: S3 source key 

### LINKED ISSUE #1923: [BUG] Unable to read from S3 key with spaces
**Describe the bug**

The Data Prepper S3 source is unable to read from keys with spaces in them.

**To Reproduce**

Simple pipeline:

```
log-pipeline:
  source:
    s3:
      notification_type: "sqs"
      codec:
        newline:
      sqs:
        queue_url: "https://sqs.us-east-1.amazonaws.com/123456789012/MyPipeline"
      aws:
        region: "us-east-1"

  processor:
  sink:
    - stdout:
```

Here is a sample file:

```
cat "has some spaces.log"
This file has spaces.
Two to be precise.
```

Upload that file:

```
aws s3 cp "has some spaces.log" s3://s3-source-manual-test/
```

**Expected behavior**

The S3 object should be read just like the one without spaces.

**Actual Outputs**

```
2022-10-15T16:56:08,659 [Thread-1] WARN  org.opensearch.dataprepper.plugins.source.SqsWorker - Unable to process S3Object: s3ObjectReference=[bucketName=***, key=has+some+spaces.log].
software.amazon.awssdk.services.s3.model.NoSuchKeyException: The specified key does not exist. (Service: S3, Status Code: 404, Request ID: ***, Extended Request ID: ***)
```

**Environment (please complete the following information):**

Data Prepper Docker build from `main`.

Files uploaded via macOS.

**Additional context**

The following values come from the S3 Console:
The S3 URI looks like:

S3 URI: `s3://***/has some spaces.log`

Object URL: `https://***.s3.amazonaws.com/has+some+spaces.log`

ARN: `arn:aws:s3:::***/has some spaces.log`

### PR DESCRIPTION
**Pull request by asifsmohammed**
Signed-off-by: Asif Sohail Mohammed <nsifmoh@amazon.com>

### Description
This PR fixes the bug in S3 source where keys with spaces are not decoded correctly. 

I tested it locally with and without the code change. Also made changes to `SqsWorkerIT` to have space in the key. Tested the IT also with and without the changes to verify.

```
 ./gradlew :data-prepper-plugins:s3-source:integrationTest --tests "org.opensearch.dataprepper.plugins.source.SqsWorkerIT" -Dtests.s3source.region=us-east-1 -Dtests.s3source.bucket=<bucket-name> -Dtests.s3source.queue.url=<queue-url>
```

 
### Issues Resolved
resolves #1923 
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dlvenable — CHANGES_REQUESTED** [review]
Nice! Thanks!

We should have a unit test for this in `SqsWorkerTest`. In general bug fixes are often good candidates for unit tests since we often have a concrete example of what to do and not do. It can verify that the object reference uses the `getUrlDecodedKey()` instead of `getKey()`. Perhaps you mock them to return different values.

I also think the integration test should be distinct. But, I'm fine accepting the PR without that change.

**Comment by asifsmohammed** [comment]
I tried adding nit test but this method `populateS3Reference` is nested with in 3 levels of private methods. I can make this method package private and test it. Let me know if there's a better approach here for unit testing.

File: data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java [hunk 1]
```diff
@@ -245,4 +247,30 @@ void processSqsMessages_should_invoke_delete_if_input_is_not_valid_JSON_and_dele
         verify(sqsMessagesDeletedCounter).increment(1);
         verify(sqsMessagesFailedCounter).increment();
     }
+
+    @Test
+    void populateS3Reference_should_interact_with_getUrlDecodedKey() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
+        // Using reflection to unit test a private method as part of bug fix.
+        final Method method = SqsWorker.class.getDeclaredMethod("populateS3Reference", S3EventNotification.S3EventNotificationRecord.class);
```
Comment (dlvenable) [inline data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java:254]: You can also make this method package protected specifically for testing purposes. I do think there is probably some opportunity for refactoring, but this should work for now.

**Review by dlvenable — APPROVED** [review]

File: data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java [hunk 2]
```diff
@@ -245,4 +247,30 @@ void processSqsMessages_should_invoke_delete_if_input_is_not_valid_JSON_and_dele
         verify(sqsMessagesDeletedCounter).increment(1);
         verify(sqsMessagesFailedCounter).increment();
     }
+
+    @Test
+    void populateS3Reference_should_interact_with_getUrlDecodedKey() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
+        // Using reflection to unit test a private method as part of bug fix.
```
Comment (sshivanii) [inline data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java:253]: Minor and non-blocking: It makes sense to include a link to the Bug for future reference

**Review by sshivanii — APPROVED** [review]

File: data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java [hunk 3]
```diff
@@ -245,4 +247,30 @@ void processSqsMessages_should_invoke_delete_if_input_is_not_valid_JSON_and_dele
         verify(sqsMessagesDeletedCounter).increment(1);
         verify(sqsMessagesFailedCounter).increment();
     }
+
+    @Test
+    void populateS3Reference_should_interact_with_getUrlDecodedKey() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
```
Comment (cmanning09) [inline data-prepper-plugins/s3-source/src/test/java/org/opensearch/dataprepper/plugins/source/SqsWorkerTest.java:252]: Can we not test an s3Entity with a key that has a space in it? Why do we need reflection?
