### PR TITLE
Fix for null pointer exception in remote peer forwarding (fix for issue 2123)

### LINKED ISSUE #2123: [BUG] Null pointer exception in Data-prepper while doing peer forwarding
**Describe the bug**
Data-prepper crashes with null pointer exception when remote peer forwarder sees an event without identification keys.

stack trace is -
ava.lang.NullPointerException: Cannot invoke "Object.toString()" because "identificationKeyValue" is null
        at org.opensearch.dataprepper.peerforwarder.RemotePeerForwarder.groupRecordsBasedOnIdentificationKeys(RemotePeerForwarder.java:156) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.peerforwarder.RemotePeerForwarder.forwardRecords(RemotePeerForwarder.java:86) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.peerforwarder.PeerForwardingProcessorDecorator.execute(PeerForwardingProcessorDecorator.java:81) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.pipeline.ProcessWorker.doRun(ProcessWorker.java:95) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:45) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**To Reproduce**
1. Start data prepper with at least two nodes with peer forwarder configuration
2. Use pipeline configuration with aggregate processor and identification keys
3. Send events which do not have the identification keys in them
4. See null pointer exception

**Expected behavior**
Expected behavior is to ignore the events that do not have the identification keys

### PR DESCRIPTION
**Pull request by kkondaka**
Signed-off-by: Krishna Kondaka <krishkdk@amazon.com>

### Description
Fix for null pointer exception in remote peer forwarding
 
### Issues Resolved
#2123 
 
### Check List
- [ X] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java [hunk 1]
```diff
@@ -141,8 +141,17 @@ private Map<String, List<Record<Event>>> groupRecordsBasedOnIdentificationKeys(
             final Event event = record.getData();
 
             final List<String> identificationKeyValues = new LinkedList<>();
+            boolean identificationKeysNotFound = false;
             for (final String identificationKey : identificationKeys) {
-                identificationKeyValues.add(event.get(identificationKey, Object.class).toString());
+                Object identificationKeyValue = event.get(identificationKey, Object.class);
```
Comment (dinujoh) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:146]: nit: add final

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java [hunk 2]
```diff
@@ -141,8 +141,17 @@ private Map<String, List<Record<Event>>> groupRecordsBasedOnIdentificationKeys(
...
+                if (identificationKeyValue == null) {
```
Comment (dinujoh) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:147]: Is this customer error ? Is this important enough to log and metric when this happens ?

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java [hunk 3]
```diff
@@ -214,6 +214,36 @@ void test_receiveRecords_should_return_record_from_buffer() throws Exception {
...
+        when(aggregatedHttpResponse.status()).thenReturn(HttpStatus.OK);
+        when(peerForwarderClient.serializeRecordsAndSendHttpRequest(anyCollection(), anyString(), anyString(), anyString())).thenReturn(aggregatedHttpResponse);
+
+        final List<String> testIps = List.of("8.8.8.8", "127.0.0.1");
+        lenient().when(hashRing.getServerIp(List.of("value1", "value1"))).thenReturn(Optional.of(testIps.get(0)));
+        lenient().when(hashRing.getServerIp(List.of("value2", "value2"))).thenReturn(Optional.of(testIps.get(1)));
+
+        RemotePeerForwarder peerForwarder = createObjectUnderTest();
+        final Collection<Record<Event>> testRecords = generateBatchRecords(2);
+        // Add an event that doesn't have identification keys in it
```
Comment (dinujoh) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java:229]: Can you provide an example of identification keys ?

**Comment by dinujoh** [comment]
Can you provide an example ingestion log data that you have tested with and without identification key ?

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java [hunk 4]
```diff
@@ -141,8 +141,17 @@ private Map<String, List<Record<Event>>> groupRecordsBasedOnIdentificationKeys(
...
+                    identificationKeysNotFound = true;
+                    break;
+                }
+                identificationKeyValues.add(identificationKeyValue.toString());
```
Comment (graytaylor0) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:151]: I think the behavior we want if an event does not have all the identification keys would be to just not add it to the values list. For example, let's say we have identification_keys `client`, `server`, `verb`, then the following event 

```
{
     "client": "1234",
     "server": "5678"
}
```

is still valid and would map to the identification_keys hash of 

```
{
     "client": "1234",
     "server": "5678",
     "verb": null
}
```

So are we sure we want to break immediately right when the first identification key is not found? Should it just be a `continue` on line 149?

Comment (asifsmohammed) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:151]: I think if `identificationKeyValue` is not null then we should add it to `identificationKeyValues` and use all existing keys for calculating hash.
```
for (final String identificationKey : identificationKeys) {
    Object identificationKeyValue = event.get(identificationKey, Object.class);
    if (identificationKeyValue != null) {
        identificationKeyValues.add(event.get(identificationKey, Object.class).toString());
    } else {
    // Add new metric here
        recordsWithMissingIdentificationKeys.increment();
    }
 }
```

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java (hunk 3 above)
Comment (kkondaka) [reply data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java:229]: Need not be customer error. We have a grok processor that extracts fields and if an input that doesn't match the grok comes, it won't have the fields needed for aggregate processor. This kind of inputs should be ignored instead of causing crash.

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java (hunk 4 above)
Comment (kkondaka) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:151]: I am not sure if it makes sense to use null value for the missing identification key. Because eventually in the aggregation the keys may be used (for example, if I am doing histogram action) and we will need those values. So, I am thinking it is better to not pass the events with missing identification keys.

Comment (dlvenable) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:151]: I agree with @asifsmohammed and @graytaylor0 . We should compute the hash when an identification key is missing, but others are present.

Only when no identification keys are present should we not pass these values.

Comment (dlvenable) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:151]: Though, I think the metric should only trigger if all values are not present.

Comment (kkondaka) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:151]: @dlvenable , we should use "null" for missing identification keys while calculating the hash?

Comment (dlvenable) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java]: Yes, we should use `null` for calculating the hash. 

This looks compatible with the current implementation for computing the hash:

https://github.com/opensearch-project/data-prepper/blob/4196a16e38123fc36651093773b8c3511ffebe63/data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/HashRing.java#L57

**Comment by dlvenable** [comment]
@kkondaka , I'm still not sure how this fixes #2123. Can you share the stack trace?

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java (hunk 4 above)
Comment (kkondaka) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java]: > @kkondaka , I'm still not sure how this fixes #2123. Can you share the stack trace?

ava.lang.NullPointerException: Cannot invoke "Object.toString()" because "identificationKeyValue" is null
        at org.opensearch.dataprepper.peerforwarder.RemotePeerForwarder.groupRecordsBasedOnIdentificationKeys(RemotePeerForwarder.java:156) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.peerforwarder.RemotePeerForwarder.forwardRecords(RemotePeerForwarder.java:86) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.peerforwarder.PeerForwardingProcessorDecorator.execute(PeerForwardingProcessorDecorator.java:81) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.pipeline.ProcessWorker.doRun(ProcessWorker.java:95) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at org.opensearch.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:45) ~[data-prepper-core-2.1.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java [hunk 5]
```diff
@@ -214,6 +219,37 @@ void test_receiveRecords_should_return_record_from_buffer() throws Exception {
...
+        final Map<String, String> eventData = new HashMap<>();
+        eventData.put("key3", "value3");
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java:236]: Please generate random strings for these keys and values. They are arbitrary aside from having to not be equal to the existing identification keys. This will make the tests clearer.

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java [hunk 6]
```diff
@@ -141,8 +144,18 @@ private Map<String, List<Record<Event>>> groupRecordsBasedOnIdentificationKeys(
...
+                final Object identificationKeyValue = event.get(identificationKey, Object.class);
+                if (identificationKeyValue == null) {
+                    identificationKeyValues.add(null);
+                    numMissingIdentificationKeys++;
+                } else {
+                    identificationKeyValues.add(identificationKeyValue.toString());
+                }
+            }
+            if (numMissingIdentificationKeys == identificationKeys.size()) {
+                recordsMissingIdentificationKeys.increment(1);
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:158]: Should we now clear the `identificationKeys`? As it is, when all the keys are missing we will create a hash from a non-empty list of all null values. These would then all be hashed to a single node in the cluster.

It seems the best behavior is to keep them on the local node. Clearing `identificationKeys` will keep this on the local endpoint.

https://github.com/opensearch-project/data-prepper/blob/87ba9cdd4198b41da79547d9231a6135fb0bfd1a/data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/HashRing.java#L53-L55

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java (hunk 4 above)
Comment (dlvenable) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java]: Yes, this looks like it fixes the NPE.

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java [hunk 7]
```diff
@@ -156,6 +156,7 @@ private Map<String, List<Record<Event>>> groupRecordsBasedOnIdentificationKeys(
             }
             if (numMissingIdentificationKeys == identificationKeys.size()) {
                 recordsMissingIdentificationKeys.increment(1);
+                identificationKeyValues.clear();
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:159]: Please add a test case for this behavior.

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java (hunk 7 above)
Comment (kkondaka) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarder.java:159]: The second test case test for recordsMissingIdentificationKeys to be incremented. Do you want the test to check for some thing else too?

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java [hunk 8]
```diff
@@ -245,12 +245,39 @@ void test_receiveRecords_with_missing_identification_keys() throws Exception {
...
+        for (int i = 0; i < 2; i++) {
+            final Map<String, String> eventData = new HashMap<>();
+            eventData.put(RandomStringUtils.randomAlphabetic(5), RandomStringUtils.randomAlphabetic(10));
+            eventData.put(RandomStringUtils.randomAlphabetic(5), RandomStringUtils.randomAlphabetic(10));
+            final JacksonEvent event = JacksonLog.builder().withData(eventData).build();
+            testRecords.add(new Record<>(event));
+        }
+
+        final Collection<Record<Event>> records = peerForwarder.forwardRecords(testRecords);
+        verify(peerForwarderClient, times(0)).serializeRecordsAndSendHttpRequest(anyList(), anyString(), anyString(), anyString());
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/peerforwarder/RemotePeerForwarderTest.java:270]: Thanks! This is what I was looking for!

**Review by dlvenable — APPROVED** [review]
