### PR TITLE
Tail Sampler action in Aggregate processor broken

### LINKED ISSUE #2760: [BUG] Tail Sampler action in Aggregate processor broken
**Describe the bug**
While uploading one of the revisions, the tail sampler action dropped core logic in the PR #2497 

**To Reproduce**
Basic functionality of allowing events matching error condition and percent sampling non-error events is broken

**Expected behavior**
All events matching error condition should be allowed
All events not matching error condition should go through probabilistic sampling logic and allow only some of them.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
Tail Sampler action in Aggregate processor broken. The core logic that does the tail sampling was got dropped while uploading one of the revisions in the PR #2497 

Resolves #2760 
 
### Issues Resolved
Resolves #2760 
 
### Check List
- [X ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java [hunk 1]
```diff
@@ -502,6 +511,51 @@ void aggregateWithHistogramAggregateAction() throws InterruptedException, NoSuch
...
+        final int numberOfErrorTraces = 2;
+        final int numberOfSpans = 5;
+        eventBatch = getBatchOfEventsForTailSampling(numberOfErrorTraces, numberOfSpans);
+        objectUnderTest.doExecute(eventBatch);
+        Thread.sleep(GROUP_DURATION_FOR_ONLY_SINGLE_CONCLUDE * 1000);
+
+        for (int i = 0; i < NUM_THREADS; i++) {
+            executorService.execute(() -> {
+                final List<Record<Event>> recordsOut = (List<Record<Event>>) objectUnderTest.doExecute(eventBatch);
+                assertThat(recordsOut.size(), equalTo(0));
```
Comment (dlvenable) [inline data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java:542]: I don't think this assertion is going to work as expected. This is running in another thread, so an error here will not fail the test.

Perhaps follow this pattern:

https://github.com/opensearch-project/data-prepper/blob/f2c9341ad127663b750a19df5f53527e4daf0dc3/data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java#L417-L425

An alternative would be to use `CallableFuture<>`.

Then in either case, put the assertions outside of the background thread.

File: data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java [hunk 2]
```diff
@@ -502,6 +511,51 @@ void aggregateWithHistogramAggregateAction() throws InterruptedException, NoSuch
         }
     }
 
+    @ParameterizedTest
+    @ValueSource(doubles = {20.0, 40.0, 60.0})
```
Comment (dlvenable) [inline data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java:515]: Is this really testing the sampling?

Since you are using the error condition, it seems that is taking precedence.

I think you may be able to create a test for the sampling. This could then have assertions on the size based on the sampling configuration.

File: data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateAction.java [hunk 3]
```diff
@@ -70,7 +71,12 @@ public AggregateActionResponse handleEvent(final Event event, final AggregateAct
     @Override
     public AggregateActionOutput concludeGroup(final AggregateActionInput aggregateActionInput) {
         GroupState groupState = aggregateActionInput.getGroupState();
-        return new AggregateActionOutput((List)groupState.getOrDefault(EVENTS_KEY, List.of()));
+        Random randomNum = new Random();
```
Comment (dlvenable) [inline data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateAction.java:74]: Create this in the constructor and re-use that object throughout.

File: data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateAction.java [hunk 4]
```diff
@@ -70,7 +71,12 @@ public AggregateActionResponse handleEvent(final Event event, final AggregateAct
...
+        int randomInt = randomNum.nextInt(100);
+        if (((groupState.containsKey(ERROR_STATUS_KEY) && (Boolean)groupState.get(ERROR_STATUS_KEY) == true)) || (randomInt < percent)) {
```
Comment (dlvenable) [inline data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateAction.java:76]: You are getting an int and then comparing to a double. I think this is somewhat minor, but it looked wrong to me at first. Typically, when doubles are used for percentages they are in the range of [0.0-1.0]. I did check and see that we use a double.

By the way, we might want to change the configuration `percent` to be a `BigDecimal` to avoid any issues with floating point numbers.

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java (hunk 2 above)
Comment (kkondaka) [reply data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java:515]: Yes. it is testing sampling but not exactly to the mentioned numbers because of the "probabilistic sampling" there is no way to test it exactly. The error condition is applied only to some events. I could only test for `lessThan` as the exact number is never guaranteed with probabilistic sampling.

Comment (dlvenable) [reply data-prepper-plugins/aggregate-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/aggregate/AggregateProcessorIT.java:515]: Yea, I was thinking about that as well. Do you think this would be flaky if we had an assertion that tested that it was within 10 percentage points each way?

File: data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateAction.java (hunk 4 above)
Comment (kkondaka) [reply data-prepper-plugins/aggregate-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/aggregate/actions/TailSamplerAggregateAction.java:76]: No need to be concerned about minor representation issues of floating points. Actually, I can make the percent as Integer. It doesn't have to be double. I thought using double will provide flexibility to have more granular percentages, but probably not necessary

**Review by dlvenable — APPROVED** [review]

**Review by graytaylor0 — APPROVED** [review]
