### PR TITLE
Fix NPE in s3 scan partition supplier

### LINKED ISSUE #3316: [BUG] S3 Scan hits NPE when bucket key has a null value
**Describe the bug**
It is possible for a NPE to occur when the global state Map for s3 scan contains a key for the bucket but the value is null (https://github.com/opensearch-project/data-prepper/blob/cd194c167233287b9be7fc83699a925cc6e44409/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java#L104)

```
2023-09-08T15:42:56.313 [Thread-10] ERROR org.opensearch.dataprepper.plugins.source.ScanObjectWorker - Received an exception while processing S3 objects, backing off and retrying
java.lang.NullPointerException: text
	at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1945) ~[?:?]
	at java.time.Instant.parse(Instant.java:395) ~[?:?]
	at org.opensearch.dataprepper.plugins.source.S3ScanPartitionCreationSupplier.listFilteredS3ObjectsForBucket(S3ScanPartitionCreationSupplier.java:104) ~[s3-source-2.4.0.jar:?]
	at org.opensearch.dataprepper.plugins.source.S3ScanPartitionCreationSupplier.apply(S3ScanPartitionCreationSupplier.java:87) ~[s3-source-2.4.0.jar:?]
	at org.opensearch.dataprepper.plugins.source.S3ScanPartitionCreationSupplier.apply(S3ScanPartitionCreationSupplier.java:32) ~[s3-source-2.4.0.jar:?]
	at org.opensearch.dataprepper.sourcecoordination.LeaseBasedSourceCoordinator.getNextPartition(LeaseBasedSourceCoordinator.java:153) ~[data-prepper-core-2.4.0.jar:?]
	at org.opensearch.dataprepper.plugins.source.ScanObjectWorker.startProcessingObject(ScanObjectWorker.java:128) ~[s3-source-2.4.0.jar:?]
	at org.opensearch.dataprepper.plugins.source.ScanObjectWorker.run(ScanObjectWorker.java:106) ~[s3-source-2.4.0.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Expected behavior**
No NullPointerException

** Steps to reproduce **
Configure an s3 scan pipeline with the same bucket duplicated twice

```
- bucket:
    name: "my-bucket"
- bucket:
    name: "my-bucket"
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by graytaylor0**
### Description
Fixes a potential NPE in the s3 scan partition supplier
 
### Issues Resolved
Resolves #3316 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java [hunk 1]
```diff
@@ -101,7 +101,7 @@ private List<PartitionIdentifier> listFilteredS3ObjectsForBucket(final List<Stri
                                                                      final LocalDateTime endDateTime,
                                                                      final Map<String, Object> globalStateMap) {
 
-        Instant mostRecentLastModifiedTimestamp = globalStateMap.containsKey(bucket) ? Instant.parse((String) globalStateMap.get(bucket)) : null;
+        Instant mostRecentLastModifiedTimestamp = globalStateMap.containsKey(bucket) && Objects.nonNull(globalStateMap.get(bucket)) ? Instant.parse((String) globalStateMap.get(bucket)) : null;
```
Comment (dlvenable) [inline data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3ScanPartitionCreationSupplier.java:104]: `globalStateMap.containsKey(bucket) && Objects.nonNull(globalStateMap.get(bucket)) ` can simplify to `globalStateMap.get(bucket) != null`

Also, `Objects.nonNull` is not necessary here. It is intended for use where a `Predicate` is needed.

**Review by dlvenable — CHANGES_REQUESTED** [review]

**Review by dlvenable — APPROVED** [review]

**Comment by dlvenable** [comment]
@graytaylor0 , We should probably have a unit test here as well.

**Review by dlvenable — APPROVED** [review]

**Review by oeyh — APPROVED** [review]
