### PR TITLE
Fix consecutive hyphens in export id

### LINKED ISSUE #6186: [BUG]Special Aurora Postgres name caused the pipeline to fail in creating rds.export.ExportTask.
**Describe the bug**
When using the pipeline to ingest data from Aurora Postgres to the OpenSearch Domain, if I named the Aurora Postgres instance stable-datalake-db2schema-apse2-01, when the pipeline tries to create an rds.export.ExportTask to export the database snapshot to the S3 bucket, I received the following error:

2025-10-14T23:28:40.029 [pool-30-thread-2] INFO org.opensearch.dataprepper.plugins.source.rds.export.ExportScheduler - Snapshot stable-datalake-db2schema-apse2-01-snapshot-c63a4ed7 is available.

2025-10-14T23:28:40.055 [pool-30-thread-2] ERROR org.opensearch.dataprepper.plugins.source.rds.export.ExportTaskManager - Failed to start an export task with error: The parameter ExportTaskIdentifier is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens. (Service: Rds, Status Code: 400, Request ID: 18b20dd3-b8c4-4b7a-8ed1-fb4bfe29a5e3) (SDK Attempt Count: 1)

However, if I change the name to stable-datalake-db2schema-apse2, there is no error occurred, and I can successfully create the rds.export.ExportTask.

Checked the logic of how Dataprepper created the export task identifier:

private String generateExportTaskId(String snapshotArn) {
    String snapshotId = Arn.fromString(snapshotArn).resource().resource();
    return truncateString(snapshotId, EXPORT_TASK_ID_MAX_LENGTH - 16) + "-export-" + UUID.randomUUID().toString().substring(0, 8);
}

private String truncateString(String originalString, int maxLength) {
    if (originalString.length() <= maxLength) {
        return originalString;
    }
    return originalString.substring(0, maxLength);
}

From the error log, if the snapshot name is stable-datalake-db2schema-apse2-01-snapshot-c63a4ed7, the export task identifier would be: stable-datalake-db2schema-apse2-01-snapshot--export-xxxxxxxx. This exportTaskIdentifier value has two '-' characters together, which does not meet the requirement. 

**To Reproduce**
1. Create an Aurora Postgres with the name stable-datalake-db2schema-apse2-01; the error will be shown.

**Expected behavior**
No matter what the Aurora Postgres name is, it should successfully create the RDS export task.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by oeyh**
### Description
Fixed the RDS export task ID generation to prevent consecutive hyphens in export task identifiers that cause RDS validation failures.
 
### Issues Resolved
Resolves #6186 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java [hunk 1]
```diff
@@ -76,7 +76,10 @@ public String checkExportStatus(String exportTaskId) {
 
     private String generateExportTaskId(String snapshotArn) {
         String snapshotId = Arn.fromString(snapshotArn).resource().resource();
-        return truncateString(snapshotId, EXPORT_TASK_ID_MAX_LENGTH - 16) + "-export-" + UUID.randomUUID().toString().substring(0, 8);
+        String truncatedSnapshotId = truncateString(snapshotId, EXPORT_TASK_ID_MAX_LENGTH - 16);
+        // Remove trailing hyphens to prevent consecutive hyphens in the export task identifier
+        truncatedSnapshotId = truncatedSnapshotId.replaceAll("-+$", "");
```
Comment (kkondaka) [inline data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java:81]: I think using "replaceAll" is expensive due to regular expressions. You can use either 
1. a while loop like
```
int endIndex = truncatedSnapshotId.length();
while (endIndex > 0 && truncatedSnapshotId.charAt(endIndex - 1) == '-') {
    endIndex--;
}
truncatedSnapshotId = truncatedSnapshotId.substring(0, endIndex);

```
or use Apache StringUtils like this

```
import org.apache.commons.lang3.StringUtils;

truncatedSnapshotId = StringUtils.stripEnd(truncatedSnapshotId, "-");

```

Comment (dlvenable) [reply data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java:81]: Creating an export only happens once per database. I think this is fine.

File: data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java [hunk 2]
```diff
@@ -76,7 +76,10 @@ public String checkExportStatus(String exportTaskId) {
...
+        return truncatedSnapshotId + "-export-" + UUID.randomUUID().toString().substring(0, 8);
```
Comment (dlvenable) [inline data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java:82]: Are there any other export restrictions which we might hit?

**Review by dlvenable — APPROVED** [review]

File: data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java (hunk 2 above)
Comment (oeyh) [reply data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java:82]: These are the naming restrictions:
- Identifiers must begin with a letter; 
- must contain only ASCII letters, digits, and hyphens; 
- and must not end with a hyphen or contain two consecutive hyphens. 
- cannot be longer than 60 characters

The snapshot Id, which is used as first part of the export id here, conforms to similar rules, so after truncating and preventing consecutive hyphens, we should be good.

File: data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java (hunk 1 above)
Comment (oeyh) [reply data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/export/ExportTaskManager.java:81]: Yes, this runs only once when pipeline starts.
