### PR TITLE
Cancel the existing grok task when a timeout occurs

### LINKED ISSUE #4026: [BUG] Grok processor match requests continue after timeout
**Describe the bug**

When running Data Prepper's `grok` processor with a timeout, the thread running the grok pattern continues.

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

Cancel the existing grok task when a timeout occurs by catching a TimeoutException.
 
### Issues Resolved

Resolves #4026
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by graytaylor0 — APPROVED** [review]

**Review by oeyh — APPROVED** [review]

File: data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java [hunk 1]
```diff
@@ -319,7 +319,12 @@ private boolean shouldBreakOnMatch(final Map<String, Object> captures) {
...
     private void runWithTimeout(final Runnable runnable) throws TimeoutException, ExecutionException, InterruptedException {
-        Future<?> task = executorService.submit(runnable);
-        task.get(grokProcessorConfig.getTimeoutMillis(), TimeUnit.MILLISECONDS);
+        final Future<?> task = executorService.submit(runnable);
+        try {
+            task.get(grokProcessorConfig.getTimeoutMillis(), TimeUnit.MILLISECONDS);
+        } catch (final TimeoutException exception) {
+            task.cancel(true);
+            throw exception;
+        }
```
Comment (kkondaka) [inline data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java:328]: Should we keep a count of number of tasks submitted to the executor and export it as a metric?
