### PR TITLE
Delete s3:TestEvent objects and log them

### LINKED ISSUE #1924: [BUG] S3 TestEvent stuck in SQS queue
**Describe the bug**

The Data Prepper S3 source fails to process `s3:TestEvent` objects. These remain the SQS queue and are reprocessed over and over again.

**To Reproduce**

Configure the S3 bucket to send notifications to SQS. It will create an SQS record for `s3:TestEvent`.

Create an S3 source pipeline in Data Prepper. Run it.

**Expected behavior**

Data Prepper should recognize the `s3:TestEvent` and remove it from the SQS queue. It should also not add this to the buffer. Ideally it does output the fact it received it since this can be useful for whomever is running Data Prepper to check that the SQS queue reads work.

**Actual Output**

```
2022-10-15T17:09:11,275 [Thread-1] ERROR org.opensearch.dataprepper.plugins.source.SqsWorker - Invalid JSON string in message body of bf803036-5fd3-4857-9db2-d608be440d8d
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Service" (class org.opensearch.dataprepper.plugins.source.S3EventNotification), not marked as ignorable (one known property: "Records"])
 at [Source: (String)"{"Service":"Amazon S3","Event":"s3:TestEvent","Time":"2022-10-15T16:36:25.510Z","Bucket":"***","RequestId":"***","HostId":"***"}"; line: 1, column: 233] (through reference chain: org.opensearch.dataprepper.plugins.source.S3EventNotification["Service"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1650) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:540) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597) ~[jackson-databind-2.13.4.jar:2.13.4]
	at org.opensearch.dataprepper.plugins.source.S3EventNotification.parseJson(S3EventNotification.java:58) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.source.SqsWorker.convertS3EventMessages(SqsWorker.java:137) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at org.opensearch.dataprepper.plugins.source.SqsWorker.getS3MessageEventNotificationRecordMap(SqsWorker.java:132) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.source.SqsWorker.processSqsMessages(SqsWorker.java:99) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.source.SqsWorker.run(SqsWorker.java:76) ~[s3-source-2.1.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Environment (please complete the following information):**

Data Prepper 2.1.0-SNAPSHOT from `main` build.

**Additional context**

Connecting an S3 Event Subscription to SQS will create this test message.

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

Detects SQS messages for the `s3:TestEvent`. When found, log that it was found and delete it from the SQS queue.
 
### Issues Resolved

Resolves #1924.
 
###

Validated by seeing one occurrence of:

```
2022-10-19T02:40:18,760 [Thread-1] INFO  org.opensearch.dataprepper.plugins.source.SqsWorker - Found s3:TestEvent message. Deleting from SQS queue.
```

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java [hunk 1]
```diff
@@ -128,58 +124,67 @@ private ReceiveMessageRequest createReceiveMessageRequest() {
...
+                return new ParsedMessage(message, s3EventNotification.getRecords());
             else {
                 LOG.debug("S3 notification message with ID:{} cannot be parsed into S3EventNotificationRecord.", message.messageId());
-                return Collections.emptyList();
+                return new ParsedMessage(message, true);
             }
 
         } catch (SdkClientException | JsonProcessingException e) {
-            LOG.error("Invalid JSON string in message body of {}", message.messageId(), e);
+            if (message.body().contains("s3:TestEvent") && message.body().contains("Amazon S3")) {
```
Comment (chenqi0805) [inline data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java:144]: QUES: why do we handle those events in exception handling instead of in the try block?

Comment (dlvenable) [reply data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java:144]: The `s3:TestEvent` has a different JSON format from what we currently parse, so we can only do this by checking the string or parsing against a different JSON structure.

These test events are very rare. They are only created when S3 is configured to send messages to an SQS queue. Since they are rare, I took this approach so that the normal messages are handled first. It might yield a few benefits:
* Not incorrectly parsing a valid upload in the unlikely scenario that these strings are present.
* Avoid checking the string for something we probably know is not there.

**Comment by cmanning09** [comment]
Hey @dlvenable, Did you do any manual testing for this change? I saw the unit tests in the PR but I am wondering if you validated data prepper can handle these events.

**Review by chenqi0805 — APPROVED** [review]

**Comment by dlvenable** [comment]
> Hey @dlvenable, Did you do any manual testing for this change? I saw the unit tests in the PR but I am wondering if you validated data prepper can handle these events.

Yes, I noted that in the description, but wasn't clear that I ran it.

I ran Data Prepper without the change and would see repeated errors.

Then I ran it with the change. I saw exactly one occurrence of the following line. This indicates that it was deleted from the queue.

```
2022-10-19T02:40:18,760 [Thread-1] INFO  org.opensearch.dataprepper.plugins.source.SqsWorker - Found s3:TestEvent message. Deleting from SQS queue.
```

Then I re-ran Data Prepper and did not see any errors from this or any line about `TestEvent`.

**Review by asifsmohammed — APPROVED** [review]

**Comment by cmanning09** [comment]
> > Hey @dlvenable, Did you do any manual testing for this change? I saw the unit tests in the PR but I am wondering if you validated data prepper can handle these events.
> 
> Yes, I noted that in the description, but wasn't clear that I ran it.
> 
> I ran Data Prepper without the change and would see repeated errors.
> 
> Then I ran it with the change. I saw exactly one occurrence of the following line. This indicates that it was deleted from the queue.
> 
> ```
> 2022-10-19T02:40:18,760 [Thread-1] INFO  org.opensearch.dataprepper.plugins.source.SqsWorker - Found s3:TestEvent message. Deleting from SQS queue.
> ```
> 
> Then I re-ran Data Prepper and did not see any errors from this or any line about `TestEvent`.

Thank you!
