### PR TITLE
Fix for kafka source not committing offsets issue #3231

### LINKED ISSUE #3231: [BUG] Kafka source plugin does not commit offsets when "acknowledgments" are enabled
**Describe the bug**
If a Kafka topic partition has non-zero beginningOffset then Kafka source plugin does not commit offsets when acknowledgements are enabled. 
e.g. issue was seen with following kafka partition:
```
Assigned partition test-topic5-12. beginningOffset: 833, endOffset: 417499, committedOffset: -
```

Also, numberOfRecordsCommitted metric does not reflect correct value. In above scenario, numberOfRecordsCommitted incremented equal to the number of consumed records and not committed records, which was 0.

### PR DESCRIPTION
**Pull request by hshardeesi**
### Description
This PR fixes following issues:
- Commit offsets when a kafka partition's beginning offset is non-zero.
- Fix numRecordsCommitted metric.
- Fix shutdown sequence for all topics+workers.

Following tests were conducted with these changes:
> Ingest 10M records from a kafka topic + group membership mutations.
> Ingest 12 M records from 2 kafka topics in single pipeline.
> Ingest 10M records from 2 different topics in 2 different pipelines.
> 2 pipelines part of same consumer group ingesting 10 M records.
> Shutdown pipeline in the middle of ingestion and resume and make sure all data is ingested.
> Ingest data without acknowledgments enabled.
> Ingest data with auto_offset_reset=earliest/latest.

 
### Issues Resolved
Resolves #3231 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java [hunk 1]
```diff
@@ -357,8 +366,8 @@ private <T> void iterateRecordPartitions(ConsumerRecords<String, T> records, fin
                                              Map<TopicPartition, CommitOffsetRange> offsets) throws Exception {
         for (TopicPartition topicPartition : records.partitions()) {
             final long partitionEpoch = getPartitionEpoch(topicPartition);
-            if (partitionEpoch == 0) {
-                LOG.info("Skipping partition {}, lost ownership", topicPartition);
+            if (acknowledgementsEnabled && partitionEpoch == 0) {
+                //ToDo: Add metric
```
Comment (engechas) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:370]: Would the metric here be useful for debugging? I'm wondering if it's worth just adding now

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java [hunk 2]
```diff
@@ -438,4 +450,26 @@ public void onPartitionsRevoked(Collection<TopicPartition> partitions) {
...
     }
+
+    final void dumpTopicPartitionOffsets(final Collection<TopicPartition> partitions) {
+        try {
+            final Map<TopicPartition, OffsetAndMetadata> committedOffsets = consumer.committed(new HashSet<>(partitions));
+            final Map<TopicPartition, Long> beginningOffsets = consumer.beginningOffsets(partitions);
+            final Map<TopicPartition, Long> endOffsets = consumer.endOffsets(partitions);
+            for (TopicPartition topicPartition : partitions) {
+                final OffsetAndMetadata offsetAndMetadata = committedOffsets.get(topicPartition);
+                LOG.info("Assigned partition {} with offsets: beginningOffset: {}, endOffset: {}, committedOffset: {}",
```
Comment (engechas) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:461]: Minor: this might be better off as a debug log rather than info

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java [hunk 3]
```diff
@@ -168,18 +168,21 @@ public void start(Buffer<Record<Event>> buffer) {
     @Override
     public void stop() {
         shutdownInProgress.set(true);
-        LOG.info("Shutting down Consumers...");
-        sourceConfig.getTopics().forEach(topic -> {
-            stopConsumer(topicExecutorService.get(topic), topicConsumer.get(topic));
-        });
-        LOG.info("Consumer shutdown successfully...");
+        final long shutdownWaitTime = calculateLongestThreadWaitingTime();
```
Comment (engechas) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java:171]: What's the upper limit on this?

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java [hunk 4]
```diff
@@ -438,4 +450,26 @@ public void onPartitionsRevoked(Collection<TopicPartition> partitions) {
...
+                        topicPartition, getTopicPartitionOffset(beginningOffsets, topicPartition),
+                        getTopicPartitionOffset(endOffsets, topicPartition),
+                        Objects.isNull(offsetAndMetadata) ? "-" : offsetAndMetadata.offset());
```
Comment (dlvenable) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:464]: This line isn't assigning anything. I think you can remove it.

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java [hunk 5]
```diff
@@ -238,6 +232,21 @@ void processAcknowledgedOffsets() {
         acknowledgedOffsets.clear();
     }
 
+    private void updateCommitCount(final TopicPartition topicPartition, final OffsetAndMetadata offsetAndMetadata) {
```
Comment (dlvenable) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:235]: It appears this only updates the metric, but the name implies it updates an actual count. Perhaps rename to `updateCommitCountMetric`.

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java [hunk 6]
```diff
@@ -215,20 +213,16 @@ void processAcknowledgedOffsets() {
...
-                            Long committedOffset = Objects.nonNull(committedOffsetAndMetadata) ? committedOffsetAndMetadata.offset() : null;
-                            LOG.info("Tracking offsets for partition{} starting with committedOffset {}", partition,
-                                    committedOffset);
-                            partitionCommitTrackerMap.put(partitionId, new TopicPartitionCommitTracker(partition, committedOffset));
+                        if (partitionCommitTrackerMap.containsKey(partitionId)) {
+                            final OffsetAndMetadata offsetAndMetadata =
+                                    partitionCommitTrackerMap.get(partitionId).addCompletedOffsets(offsetRange.getOffsets());
+                            updateOffsetsToCommit(partition, offsetAndMetadata);
+                        } else {
+                            LOG.error("!! Commit tracker not found for topic: {} partition: {}", partition.topic(), partitionId);
```
Comment (dlvenable) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:224]: I don't think we need these exclamation marks. The log level is `ERROR` which is sufficient here.

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java [hunk 7]
```diff
@@ -164,10 +161,10 @@ public <T> void consumeRecords() throws Exception {
                 }
                 iterateRecordPartitions(records, acknowledgementSet, offsets);
                 if (!acknowledgementsEnabled) {
-                    offsets.forEach((partition, offsetRange) ->
-                            updateOffsetsToCommit(partition,
-                                    new OffsetAndMetadata(offsetRange.getOffsets().getMaximum() + 1),
-                                    offsetRange.getOffsets()));
+                    offsets.forEach((partition, offsetRange) -> {
```
Comment (dlvenable) [inline data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:164]: We should be unit testing this behavior.

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java (hunk 1 above)
Comment (hshardeesi) [reply data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:370]: I didn't have time to add a new metric. I'll see if I can add now, but there are other metrics and logs from which it can be inferred if we are hitting this condition. Ideally, it should not happen and an assert is more appropriate here.

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java (hunk 2 above)
Comment (hshardeesi) [reply data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/KafkaSourceCustomConsumer.java:461]: this is very crucial log for debugging, I wish we had it from the beginning. If debug shows up by default then I can change it to debug level else leave it as INFO.

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java (hunk 3 above)
Comment (hshardeesi) [reply data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/source/KafkaSource.java:171]: Looking at calculateLongestThreadWaitingTime() implementation it looks like it can be atmost 5 seconds (default value) unless user has configured to be higher number.

**Comment by hshardeesi** [comment]
> Thanks for the contribution @hshardeesi !
> 
> There is a lot here that could be unit tested to ensure that the behavior remains correct.

File: data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicPartitionCommitTracker.java [hunk 8]
```diff
@@ -68,6 +90,7 @@ public OffsetAndMetadata addCompletedOffsets(final Range<Long> offsetRange) {
             Long maxValue = offsetMinMap.get(committedOffset).getMaximum();
             if (maxValue != committedOffset) {
                 offsetMinMap.remove(committedOffset);
+                committedRecordCount += (maxValue - committedOffset);
```
[the remark this answers is not in the document]
Comment (hshardeesi) [reply data-prepper-plugins/kafka-plugins/src/main/java/org/opensearch/dataprepper/plugins/kafka/consumer/TopicPartitionCommitTracker.java:93]: Sure I'll add unit test for this and other scenarios you pointed out below.

**Review by dlvenable — APPROVED** [review]
Thanks for updating the tests!
