### PR TITLE
Fix Null Pointer Exception in KeyValue Processor

### LINKED ISSUE #3928: [BUG] Null Pointer Exception in Key Value Processor
**Describe the bug**
A Null pointer exception occurs in Key Value Processor with the following stack trace

2023-12-29T11:03:28.730 [osi-logs-dev-pipeline-processor-worker-1-thread-2] ERROR org.opensearch.dataprepper.pipeline.ProcessWorker - Encountered exception during pipeline osi-logs-dev-pipeline processing
java.lang.NullPointerException: null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770) ~[?:?]
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416) ~[?:?]
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253) ~[?:?]
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134) ~[?:?]
	at java.base/java.util.regex.Pattern.split(Pattern.java:1262) ~[?:?]
	at org.opensearch.dataprepper.plugins.processor.keyvalue.KeyValueProcessor.doExecute(KeyValueProcessor.java:239) ~[key-value-processor-2.6.0.jar:?]
	at org.opensearch.dataprepper.model.processor.AbstractProcessor.lambda$execute$0(AbstractProcessor.java:54) ~[data-prepper-api-2.6.0.jar:?]
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:69) ~[micrometer-core-1.11.3.jar:1.11.3]
	at org.opensearch.dataprepper.model.processor.AbstractProcessor.execute(AbstractProcessor.java:54) ~[data-prepper-api-2.6.0.jar:?]
	at org.opensearch.dataprepper.pipeline.ProcessWorker.doRun(ProcessWorker.java:133) ~[data-prepper-core-2.6.0.jar:?]
	at org.opensearch.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:61) ~[data-prepper-core-2.6.0.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]

**To Reproduce**
To reproduce the issue, send input that does not have the "source" in the key value processor config.

**Expected behavior**
Input without the configured source should be ignored and the not crash data prepper.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
Fix Null Pointer Exception in KeyValue Processor which is occurring when the input event does not have the "source" field

Resolves #3928 
### Issues Resolved
Resolves #3928
 
### Check List
- [X ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java [hunk 1]
```diff
@@ -236,6 +236,9 @@ public Collection<Record<Event>> doExecute(final Collection<Record<Event>> recor
             final Map<String, Object> outputMap = new HashMap<>();
             final Event recordEvent = record.getData();
             final String groupsRaw = recordEvent.get(keyValueProcessorConfig.getSource(), String.class);
+            if (groupsRaw == null) {
```
Comment (oeyh) [inline data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java:239]: Thanks for the fix! 

Can we add `tagsOnFailure` to metadata in this case? Similar to Line 250 below.

Comment (kkondaka) [reply data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java:239]: We could add it but I think that should be a separate PR.

Comment (graytaylor0) [reply data-prepper-plugins/key-value-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/keyvalue/KeyValueProcessor.java:239]: Will resolve this duplicate issue (https://github.com/opensearch-project/data-prepper/issues/3496). I think tagging it makes sense

**Review by graytaylor0 — APPROVED** [review]

**Review by oeyh — APPROVED** [review]
