### PR TITLE
S3 sink without path_prefix provided should write to bucket root

### LINKED ISSUE #6090: S3 sink without path_prefix provided is failing to write
**Describe the bug**
`object_key` and `path_prefix` configuration options under S3 sink are optional. If not provided, S3 sink should write to the root of the bucket, but in the current state, it is failing with the following exception

```
ERROR org.opensearch.dataprepper.plugins.sink.s3.S3SinkService - Unable to add 1 events to buffer. Dropping these events. Sample exception provided.
java.lang.NullPointerException: Cannot invoke "String.indexOf(String, int)" because "format" is null
	at org.opensearch.dataprepper.model.event.JacksonEvent.formatStringInternal(JacksonEvent.java:492)
	at org.opensearch.dataprepper.model.event.JacksonEvent.formatString(JacksonEvent.java:484)
	at org.opensearch.dataprepper.plugins.sink.s3.accumulator.ObjectKey.buildingPathPrefixInternal(ObjectKey.java:52)
	at org.opensearch.dataprepper.plugins.sink.s3.accumulator.ObjectKey.buildingPathPrefix(ObjectKey.java:45)
	at org.opensearch.dataprepper.plugins.sink.s3.KeyGenerator.generateKeyForEvent(KeyGenerator.java:37)
	at org.opensearch.dataprepper.plugins.sink.s3.grouping.S3GroupIdentifierFactory.getS3GroupIdentifierForEvent(S3GroupIdentifierFactory.java:56)
	at org.opensearch.dataprepper.plugins.sink.s3.grouping.S3GroupManager.getOrCreateGroupForEvent(S3GroupManager.java:77)
	at org.opensearch.dataprepper.plugins.sink.s3.S3SinkService.output(S3SinkService.java:120)
```

**To Reproduce**
1. Create a pipeline with S3 sink without `object_key` config option

```
sink:
    - s3:
        bucket: "some-bucket-name"
        codec:
          ndjson:
        threshold:
          event_collect_timeout: 60s
        aws:
          region: "us-west-2"
```

**Expected behavior**
Objects should be written to the bucket root folder

### PR DESCRIPTION
**Pull request by san81**
### Description
`object_key` and `path_prefix` configuration options under S3 sink are optional. If not provided, S3 sink should write to the root of the bucket, but in the current state, it is failing. This code change fixes it.
 
### Issues Resolved
Resolves #6090
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/KeyGenerator.java [hunk 1]
```diff
@@ -35,7 +35,8 @@ public KeyGenerator(final S3SinkConfig s3SinkConfig,
      */
     public String generateKeyForEvent(final Event event) {
         final String pathPrefix = s3BucketSelector != null ? s3BucketSelector.getPathPrefix() : ObjectKey.buildingPathPrefix(s3SinkConfig, event, expressionEvaluator);
```
Comment (graytaylor0) [inline data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/KeyGenerator.java:37]: I think the NPE comes from the call to buildingPathPrefix here, so this change doesn't prevent it

Comment (san81) [reply data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/KeyGenerator.java:37]: `ObjectKey.buildingPathPrefix` method fix is also included in this PR.

**Review by graytaylor0 — APPROVED** [review]

**Review by dlvenable — APPROVED** [review]
