### PR TITLE
Fix lambda processor batching

### LINKED ISSUE #5473: [BUG] Lambda Plugin Batching
**Describe the bug**
Noticed following issues with lambda processor
1. When batching multiple records based on size, we seems to be adding more than the limit mentioned in the batch threshold configuration. Specifically, we seem to be one over the limit. 

2. When there is a lambda invocation failure, we seem to fail all the records that the processor is receiving. We should only fail for that perticular batch and not all the records that the processor receives.

**To Reproduce**
try to execute the processor with 3 records, 1MB,7MB and 1MB; in that sequence. We should ideally see 3 batches , ie 3 requests to lambda, but currently we will see only 2 batches - first 2 in once batch and the last 1 mb in another.

### PR DESCRIPTION
**Pull request by srikanthjg**
### Description
Fix lambda processor batching
1. Fixed threshold check 
2. Fix futures handling
3. Refactor and fix lambda sink 

### Issues Resolved
Resolves #5473 
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java [hunk 1]
```diff
@@ -62,16 +62,35 @@ private static List<Buffer> createBufferBatches(Collection<Record<Event>> record
...
+
+                // After adding, check if the event count threshold is reached.
+                if (ThresholdCheck.checkEventCountThresholdExceeded(currentBufferPerBatch, maxEvents)) {
+                    batchedBuffers.add(currentBufferPerBatch);
+                    currentBufferPerBatch = new InMemoryBuffer(keyName, outputCodecContext);
+                    continue; // Continue with next record.
+                }
+
+                // Also, check if the timeout threshold is reached.
+                if (ThresholdCheck.checkTimeoutExceeded(currentBufferPerBatch, maxCollectionDuration)) {
```
Comment (kkondaka) [inline data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java:87]: This check must be outside the loop.

File: data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/util/ThresholdCheck.java [hunk 2]
```diff
@@ -5,30 +5,53 @@
...
+import java.nio.charset.StandardCharsets;
 import java.time.Duration;
 
 /**
  * Check threshold limits.
  */
 public class ThresholdCheck {
 
-    public static boolean checkThresholdExceed(final Buffer currentBuffer, final int maxEvents, final ByteCount maxBytes, final Duration maxCollectionDuration) {
+    public static boolean checkThresholdExceed(final Buffer currentBuffer, final int maxEvents,
```
Comment (kkondaka) [inline data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/util/ThresholdCheck.java:21]: Where is this used?

File: data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSink.java [hunk 3]
```diff
@@ -203,7 +203,7 @@ public void doOutput(final Collection<Record<Event>> records) {
                 //statefulBuffer is either empty or partially filled(from previous run)
                 statefulBuffer.addRecord(record);
 
-                if (isThresholdExceeded(statefulBuffer)) {
+                if (isThresholdExceeded(statefulBuffer, record)) {
```
Comment (kkondaka) [inline data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/sink/LambdaSink.java:206]: Fix this.

File: data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java (hunk 1 above)
Comment (srikanthjg) [reply data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java:87]: i dont think it should be outside the loop as both batchedBuffer and currentBufferPerBatch are newly created here. Processor uses stateless buffer, and we flush all records received.

File: data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java [hunk 4]
```diff
@@ -62,16 +62,35 @@ private static List<Buffer> createBufferBatches(Collection<Record<Event>> record
...
-            currentBufferPerBatch.addRecord(record);
-            if (ThresholdCheck.checkThresholdExceed(currentBufferPerBatch, maxEvents, maxBytes,
-                    maxCollectionDuration)) {
-                batchedBuffers.add(currentBufferPerBatch);
-                currentBufferPerBatch = new InMemoryBuffer(keyName, outputCodecContext);
-            }
+        java.util.Iterator<Record<Event>> iterator = records.iterator();
+        if (iterator.hasNext()) {
+            do {
+                Record<Event> record = iterator.next();
```
Comment (kkondaka) [inline data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java]: Please change it back to "for" loop.

File: data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java [hunk 5]
```diff
@@ -63,15 +63,21 @@ private static List<Buffer> createBufferBatches(Collection<Record<Event>> record
 
         LOG.debug("Batch size received to lambda processor: {}", records.size());
         for (Record<Event> record : records) {
+            //check size or time has exceeded threshold
+            if (ThresholdCheck.checkSizeThresholdExceed(currentBufferPerBatch, maxBytes, record)
+            || ThresholdCheck.checkTimeoutExceeded(currentBufferPerBatch, maxCollectionDuration)) {
```
Comment (kkondaka) [inline data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/common/LambdaCommonHandler.java:68]: Timeout check must be outside the for loop.

File: data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorIT.java [hunk 6]
```diff
@@ -164,6 +170,28 @@ public void setup() {
...
+        setPrivateField(lambdaProcessor, "numberOfRequestsSuccessCounter",
+                numberOfRequestsSuccessCounter);
+        setPrivateField(lambdaProcessor, "numberOfRequestsFailedCounter",
+                numberOfRequestsFailedCounter);
+        setPrivateField(lambdaProcessor, "batchExceedingThresholdCounter",
+                batchExceedingThresholdCounter);
+    }
+
+    // Helper method to set private fields via reflection
+    private void setPrivateField(Object targetObject, String fieldName, Object value)
```
Comment (san81) [inline data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorIT.java:188]: FYI: We have this method defined in `test-commons` package. Possibly we can reuse this method instead of defining it here. 

https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-test-common/src/main/java/org/opensearch/dataprepper/test/helper/ReflectivelySetField.java#L30

File: data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorIT.java [hunk 7]
```diff
@@ -525,4 +553,171 @@ def lambda_handler(event, context):
...
+        final BatchOptions batchOptions = lambdaProcessorConfig.getBatchOptions();
+        when(lambdaProcessorConfig.getFunctionName()).thenReturn(functionName);
+        when(invocationType.getAwsLambdaValue()).thenReturn(InvocationType.REQUEST_RESPONSE.getAwsLambdaValue());
+        when(lambdaProcessorConfig.getResponseEventsMatch()).thenReturn(true); // Strict mode
+        when(lambdaProcessorConfig.getTagsOnFailure()).thenReturn(Collections.singletonList("lambda_failure"));
+
+        final ThresholdOptions thresholdOptions = batchOptions.getThresholdOptions();
+        when(thresholdOptions.getEventCollectTimeOut()).thenReturn(Duration.ofSeconds(100));
+        when(thresholdOptions.getMaximumSize()).thenReturn(ByteCount.parse("5mb"));
+        lambdaProcessor = createObjectUnderTest(lambdaProcessorConfig);
```
Comment (san81) [inline data-prepper-plugins/aws-lambda/src/integrationTest/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorIT.java:610]: This indentation is confusing here. I would recommend something like this to setup in your IDE. 

https://w.amazon.com/bin/view/COCO/NACO/CodingBestPractices#HAddingFormatter

File: data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java [hunk 8]
```diff
@@ -194,6 +201,9 @@ public Collection<Record<Event>> doExecute(Collection<Record<Event>> records) {
 
             } catch (Exception e) {
                 LOG.error(NOISY, e.getMessage(), e);
+                if(e.getMessage().contains(EXCEEDING_PAYLOAD_LIMIT_EXCEPTION)){
+                    batchExceedingThresholdCounter.increment();
```
Comment (san81) [inline data-prepper-plugins/aws-lambda/src/main/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessor.java:205]: do we need this counter? As you are adding this threshold check in-advance, we may never see this counter increased - right?

File: data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/common/ThresholdCheckTest.java [hunk 9]
```diff
@@ -11,116 +11,93 @@
...
+import org.opensearch.dataprepper.model.record.Record;
 import org.opensearch.dataprepper.model.types.ByteCount;
 import org.opensearch.dataprepper.plugins.lambda.common.accumlator.Buffer;
 import org.opensearch.dataprepper.plugins.lambda.common.util.ThresholdCheck;
 
-import java.io.IOException;
 import java.time.Duration;
 
 @ExtendWith(MockitoExtension.class)
+@MockitoSettings(strictness = Strictness.LENIENT)
```
Comment (san81) [inline data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/common/ThresholdCheckTest.java:28]: I would recommend, not adding this

File: data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java [hunk 10]
```diff
@@ -783,4 +729,106 @@ public void testDoExecute_nonRetryableException_thrownImmediatelyFail() throws E
...
+        // Create 2000 events
+        List<Record<Event>> records = getSampleEventRecords(2000);
+        Collection<Record<Event>> results = lambdaProcessor.doExecute(records);
+        // Expect 20 batches (thus 20 successful invocations)
+        verify(numberOfRequestsSuccessCounter, times(19)).increment();
+        verify(numberOfRequestsFailedCounter, times(1)).increment();
+    }
+
+
+    private Record<Event> createLargeRecord(final int sizeInBytes) {
```
Comment (san81) [inline data-prepper-plugins/aws-lambda/src/test/java/org/opensearch/dataprepper/plugins/lambda/processor/LambdaProcessorTest.java:815]: I saw this in multiple places. You can avoid duplication, if you make this method as a static util and reuse

**Review by san81 — APPROVED** [review]
All my comments are related to better testing. Assuming that will be addressed in a follow up PR, approving it now
