### PR TITLE
Fix: IllegalArgument Exception in String converter

### LINKED ISSUE #3135: [BUG] Processor threads shutting down due to IllegalArgumentException thrown by StringConverter
**Describe the bug**
The processor threads are shutting down due to IllegalArgumentException thrown for invalid type in the StringCoverter.

**To Reproduce**
1. Create a data prepper pipeline to write data to OpenSearch
2. Send some data that is not in the supported format https://github.com/opensearch-project/data-prepper/blob/47a9bc0b99590d4b6554371a38860964947a06fd/data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java#L8
3. Notice that opensearch.documentsSuccess metrics is at 0
4. Now send the correctly formatted data, note that opensearch.documentsSuccess is still at zero, which indicates that the data is not processed by the pipeline

**Expected behavior**
The pipeline should drop invalid messages instead of shutting down while emitting the right metrics. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**
```
2023-07-30T20:00:04.944 [apache-log-pipeline-processor-worker-1-thread-2] ERROR org.opensearch.dataprepper.pipeline.ProcessWorker - Encountered exception during pipeline apache-log-pipeline processing
java.lang.IllegalArgumentException: Unsupported type conversion
    at org.opensearch.dataprepper.typeconverter.StringConverter.convert(StringConverter.java:28) ~[data-prepper-api-2.3.2.jar:?]
    at org.opensearch.dataprepper.typeconverter.StringConverter.convert(StringConverter.java:8) ~[data-prepper-api-2.3.2.jar:?]
    at org.opensearch.dataprepper.plugins.processor.mutateevent.ConvertEntryTypeProcessor.doExecute(ConvertEntryTypeProcessor.java:52) ~[mutate-event-processors-2.3.2.jar:?]
    at org.opensearch.dataprepper.model.processor.AbstractProcessor.lambda$execute$0(AbstractProcessor.java:54) ~[data-prepper-api-2.3.2.jar:?]
    at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:69) ~[micrometer-core-1.10.5.jar:1.10.5]
    at org.opensearch.dataprepper.model.processor.AbstractProcessor.execute(AbstractProcessor.java:54) ~[data-prepper-api-2.3.2.jar:?]
    at org.opensearch.dataprepper.pipeline.ProcessWorker.doRun(ProcessWorker.java:127) ~[data-prepper-core-2.3.2.jar:?]
    at org.opensearch.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:60) ~[data-prepper-core-2.3.2.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
    at java.lang.Thread.run(Thread.java:829) [?:?]
2023-07-30T20:04:06.922 [apache-log-pipeline-sink-worker-2-thread-2] WARN  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Document [******] has failure. DLQ not configured
2023-07-30T20:05:04.844 [apache-log-pipeline-processor-worker-1-thread-1] ERROR org.opensearch.dataprepper.pipeline.ProcessWorker - Encountered exception during pipeline apache-log-pipeline processing
java.lang.IllegalArgumentException: Unsupported type conversion
    at org.opensearch.dataprepper.typeconverter.StringConverter.convert(StringConverter.java:28) ~[data-prepper-api-2.3.2.jar:?]
    at org.opensearch.dataprepper.typeconverter.StringConverter.convert(StringConverter.java:8) ~[data-prepper-api-2.3.2.jar:?]
    at org.opensearch.dataprepper.plugins.processor.mutateevent.ConvertEntryTypeProcessor.doExecute(ConvertEntryTypeProcessor.java:52) ~[mutate-event-processors-2.3.2.jar:?]
    at org.opensearch.dataprepper.model.processor.AbstractProcessor.lambda$execute$0(AbstractProcessor.java:54) ~[data-prepper-api-2.3.2.jar:?]
    at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:69) ~[micrometer-core-1.10.5.jar:1.10.5]
    at org.opensearch.dataprepper.model.processor.AbstractProcessor.execute(AbstractProcessor.java:54) ~[data-prepper-api-2.3.2.jar:?]
    at org.opensearch.dataprepper.pipeline.ProcessWorker.doRun(ProcessWorker.java:127) ~[data-prepper-core-2.3.2.jar:?]
    at org.opensearch.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:60) ~[data-prepper-core-2.3.2.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
    at java.lang.Thread.run(Thread.java:829) [?:?]
```

### PR DESCRIPTION
**Pull request by asifsmohammed**
### Description
Fix IllegalArgumentException and return object.toString
 
### Issues Resolved
Resolves #3135 
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java [hunk 1]
```diff
@@ -25,6 +34,11 @@ public String convert(Object source) throws IllegalArgumentException {
         if (source instanceof String) {
             return (String)source;
         }
-        throw new IllegalArgumentException("Unsupported type conversion");
+        LOG.error(EVENT, "Unable to convert {} to String", source);
+        if (Objects.nonNull(source)) {
+            return source.toString();
+        } else {
+            return "";
```
Comment (dlvenable) [inline data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java:41]: In the case of `null`, we can probably handle this in the `ConvertEntryTypeProcessor` class. Any `null` value can be converted to `null` for the target.

Also, it should not be an empty string. It should be `null`.

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java [hunk 2]
```diff
@@ -25,6 +34,11 @@ public String convert(Object source) throws IllegalArgumentException {
         if (source instanceof String) {
             return (String)source;
         }
-        throw new IllegalArgumentException("Unsupported type conversion");
+        LOG.error(EVENT, "Unable to convert {} to String", source);
+        if (Objects.nonNull(source)) {
+            return source.toString();
```
Comment (dlvenable) [inline data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java:39]: I'm not sure this is really a good behavior. It could result in strange output. Say a list is provided. The user will get a string that looks like `ListString@89879` or something like that.

I think this should continue to throw the exception.

We can handle the exception in the `ConvertEntryTypeProcessor` class to make it consistent across all types. 

Perhaps by dropping the data?

**Review by dlvenable — CHANGES_REQUESTED** [review]

**Review by dlvenable — COMMENTED** [review]
I think the solution to this issue should be done entirely within `ConvertEntryTypeProcessor`. Let's continue to have the TypeConverter class throw and expect non-null.

So change `ConvertEntryTypeProcessor` to:

1. Handle `null` conversions since the result is always `null`.
2. Catch exceptions and handle these. 

One item 2, the solution isn't completely clear. It should definitely log the error. But, what about the data? Does it drop the whole event or just the field? Or leave unconverted?

I tend to think we should add a user configuration to let the user decide how to handle. The most appropriate default to me seems to be to drop the data. Otherwise, we are sending garbage downstream.

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java (hunk 1 above)
Comment (asifsmohammed) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java:41]: I can return `null` string in case of null value instead of empty string. convert method is also used in translate processor.

**Comment by asifsmohammed** [comment]
I added `tags_on_failure` option which will add tags and log the failure. This change would not alter the current behavior. The key would be deleted first and then the if conversion works the key with new value will be added.

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java [hunk 3]
```diff
@@ -25,6 +27,9 @@ public String convert(Object source) throws IllegalArgumentException {
         if (source instanceof String) {
             return (String)source;
         }
+        if (Objects.isNull(source)) {
+            return "null";
```
Comment (dlvenable) [inline data-prepper-api/src/main/java/org/opensearch/dataprepper/typeconverter/StringConverter.java:31]: I think we can return `null`, not a string named `"null"`.

**Review by dlvenable — CHANGES_REQUESTED** [review]

**Review by dlvenable — APPROVED** [review]
Nice! Thanks for these improvements!

**Review by graytaylor0 — APPROVED** [review]
