### PR TITLE
Fix visibility timeout errors (#4812)

### LINKED ISSUE #4812: [BUG] Visibility duplication protection fails when using S3 source for large files and receiving 10 messages from SQS queue
**Describe the bug**
When ingesting large files using S3-SQS processing, OpenSearch Ingestion pipeline failed to prevent duplication although visibility_duplication_protection was set to true. The SQS queue's ApproximateNumberOfMessagesVisible metric kept growing. Confirmed duplicated documents existed in the OpenSearch index. There were many errors in the pipeline logs. For example: 
ERROR org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Failed to set visibility timeout for message [foo] to 60
software.amazon.awssdk.services.sqs.model.SqsException: Value [bar] for parameter ReceiptHandle is invalid. Reason: Message does not exist or is not available for visibility timeout change. (Service: Sqs, Status Code: 400, Request ID: [baz])

The issue happened when OSI received 10 messages (or close to 10) from the SQS queue in a single request. It worked fine when OSI received one message in a single request.

**To Reproduce**
1. Configure a S3 bucket and a SQS queue according to the documentation
2. Set the following parameters in the pipeline configuration
  source:
    s3:
      acknowledgments: true
      notification_type: "sqs"
      compression: "gzip"
      codec:
        ndjson:
      workers: 5
      sqs:
        queue_url: 
        maximum_messages: 10
        visibility_timeout: "60s"
        visibility_duplication_protection: true
3. Provision the right amount of OCUs for the pipeline
4. Start the pipeline
5. Send large gzipped files, e.g. 80MB, to the S3 bucket continuously
6. Check the pipeline's logs using CloudWatch Log Insights with the following query
fields @timestamp, @message 
| filter @message like /ReceiptHandle is invalid/ 
| sort @timestamp desc
7. Check the pipeline's logs using CloudWatch Log Insights with the following query
fields @timestamp, @message 
| filter @message like /10 messages from SQS. Processing/ 
| sort @timestamp desc
8. Check the queue's ApproximateNumberOfMessagesVisible metric
9. Check OpenSearch index for duplicated documents

**Expected behavior**
No log messages are found from step 6. Log messages are found from step 7. The ApproximateNumberOfMessagesVisible metric doesn't keep growing. There are no duplicated documents in the index.

### PR DESCRIPTION
**Pull request by danhli**
### Description
The change fixes the visibility timeout errors by creating acknowledgement sets for all the messages from a SQS ReceiveMessage call before additional processing. 
 
### Issues Resolved
Resolves #4812
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
- [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by kkondaka — DISMISSED** [review]

**Comment by kkondaka** [comment]
@danhli Thanks for working on this.

File: data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java [hunk 1]
```diff
@@ -262,7 +264,19 @@ && isEventBridgeEventTypeCreated(parsedMessage)) {
                         },
                         Duration.ofSeconds(progressCheckInterval));
                 }
+                messageAcknowledgementSetMap.put(parsedMessage, acknowledgementSet);
+                messageWaitingForAcknowledgementsMap.put(parsedMessage, waitingForAcknowledgements);
             }
+        }
+        
+        if (endToEndAcknowledgementsEnabled) {
+            LOG.info("Created acknowledgement sets for {} messages.", parsedMessagesToRead.size());
```
Comment (dlvenable) [inline data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java:273]: Let's make this a `debug` level log. Otherwise, we'll have too many logs generated.

**Review by dlvenable — CHANGES_REQUESTED** [review]
Overall, this change makes sense after looking closely.

Basically, it seems that we started processing the messages in order, but without the acknowledgement set, we were not changing the visibility timeout. With this change, we will have acknowledgement sets that are going to trigger the change visibility timeout while processing the messages.

File: data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java (hunk 1 above)
Comment (danhli) [reply data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java:273]: OK. I will update the log level to `debug`.

**Comment by danhli** [comment]
@kkondaka I ran the following tests to validate the changes. 
1. Deployed the OOTB Data Prepper to an EC2. Updated the pipeline configuration to use a S3 source and an OpenSearch sink. Set the visibility timeout value to 30s. Sent 60 log files (80MB each) within a minute to the S3 source bucket. Confirmed the Data Prepper logs on the EC2 had the visibility timeout errors.
2. Deployed the updated DataPrepper to the same EC2. Used the same test configuration as those in step 1. Confirmed the Data Prepper logs didn't have the visibility timeout errors.

**Review by kkondaka — APPROVED** [review]

**Review by dlvenable — APPROVED** [review]
