### PR TITLE
Fix race condition in SqsWorker when acknowledgements are enabled

### LINKED ISSUE #3000: [BUG] Race condition in S3 source when E2E acknowledgements enabled
**Describe the bug**
Race condition in S3 source when E2E acknowledgements enabled.
The main thread and the ack callback thread may get executed in different order causing the `waitingForAcknowledgements` to be not populated correctly. This can cause SQS messages not deleted.

**To Reproduce**

**Expected behavior**
Expected behavior is for the callback thread to run only after `waitingForAcknowledgements` are fully populated by the main thread.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
Fix race condition in SqsWorker when acknowledgements are enabled
When E2E acknowledgements are enabled, S3 Source need to synchronize between the callback thread and the main thread because main thread may not have got chance to fully populate the waitingForAcknowledgements list
 
Resolves #3000 
### Issues Resolved
#3000 
 
### Check List
- [ X] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java [hunk 1]
```diff
@@ -226,6 +227,7 @@ && isEventBridgeEventTypeCreated(parsedMessage)) {
         for (ParsedMessage parsedMessage : parsedMessagesToRead) {
             List<DeleteMessageBatchRequestEntry> waitingForAcknowledgements = new ArrayList<>();
             AcknowledgementSet acknowledgementSet = null;
+            AtomicBoolean acknowledgementSetReady = new AtomicBoolean(false);
```
Comment (engechas) [inline data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsWorker.java:230]: Doesn't look like this is used anywhere

File: data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/SqsWorkerIT.java [hunk 2]
```diff
@@ -127,6 +147,145 @@ void processSqsMessages_should_return_at_least_one_message(final int numberOfObj
...
+        });
+        sinkThread.start();
+        final int sqsMessagesProcessed = objectUnderTest.processSqsMessages();
+        synchronized(this) {
+            ready.set(true);
+            this.notify();
+        }
+        try {
+            Thread.sleep(10000);
+        } catch (Exception e){}
```
Comment (dlvenable) [inline data-prepper-plugins/s3-source/src/integrationTest/java/org/opensearch/dataprepper/plugins/source/SqsWorkerIT.java:210]: Are you expecting the thread to be interrupted? If you are not expecting this, then you can just let an interruption fail the test.

```
Thread.sleep(10000);
```

and update the method to `throws Exception`.

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java [hunk 3]
```diff
@@ -84,6 +86,8 @@ public boolean isDone() {
             if (Instant.now().isAfter(expiryTime)) {
                 if (callbackFuture != null) {
                     callbackFuture.cancel(true);
+                    callbackFuture = null;
+                    LOG.warn("AcknowledgementSet expired");
```
[the remark this answers is not in the document]
Comment (kkondaka) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/acknowledgements/DefaultAcknowledgementSet.java:90]: I am expecting there shouldn't be a lot of these. Since we only support one source, the acknowledgement set and expiry time should be obvious. We could pass a name to `AcknowledgementSetManager.create` when we support multiple sources.

**Review by engechas — APPROVED** [review]

**Review by dlvenable — APPROVED** [review]
