### PR TITLE
DynamicIndexTemplate can cause NPE that shuts down pipeline - Issue #2210

### LINKED ISSUE #2210: [BUG] DynamicIndexTemplate can cause NPE that shuts down pipeline
**Describe the bug**
An NPE occurs in the DynamicIndexTemplate parsing that shuts down the pipeline:
```
ERROR org.opensearch.dataprepper.pipeline.common.PipelineThreadPoolExecutor - Pipeline [log-pipeline] process worker encountered a fatal exception, cannot proceed further
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:191)
at org.opensearch.dataprepper.pipeline.common.PipelineThreadPoolExecutor.afterExecute(PipelineThreadPoolExecutor.java:70)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1129)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:829) 
Caused by: java.lang.NullPointerException
at java.util.regex.Matcher.getTextLength(Matcher.java:1770)
at java.util.regex.Matcher.reset(Matcher.java:416)
at java.util.regex.Matcher.<init>(Matcher.java:253)
at java.util.regex.Pattern.matcher(Pattern.java:1134)
at org.opensearch.dataprepper.plugins.sink.opensearch.index.AbstractIndexManager.getDatePatternFormatter(AbstractIndexManager.java:76)
at org.opensearch.dataprepper.plugins.sink.opensearch.index.AbstractIndexManager.getIndexAliasWithDate(AbstractIndexManager.java:94)
at org.opensearch.dataprepper.plugins.sink.opensearch.index.DynamicIndexManager.getIndexName(DynamicIndexManager.java:51)
at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.doOutput(OpenSearchSink.java:138)
at org.opensearch.dataprepper.model.sink.AbstractSink.lambda$output$0(AbstractSink.java:38)
at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:89) 
at org.opensearch.dataprepper.model.sink.AbstractSink.output(AbstractSink.java:38)
at org.opensearch.dataprepper.pipeline.Pipeline.lambda$publishToSinks$3(Pipeline.java:247)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
... 2 more
```

The stack trace is a bit opaque, but as far as I can tell, null was [passed to Pattern::matcher here](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/AbstractIndexManager.java#L76). The null appears to have originated from here: https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java#L173

**Expected behavior**
Any configuration that could lead to this scenario should be validated as part of pipeline construction to fail fast and provide an informative error message.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by kkondaka**
Signed-off-by: Krishna Kondaka <krishkdk@amazon.com>

### Description
DynamicIndexTemplate can cause NPE that shuts down pipeline.
The dynamic index feature that extracts the index name from the events is not handling the events that do not have the field that is used in the index name. 
Fix is to skip the event if it does not contain the field required to make the index name by throwing an exception.
 
### Issues Resolved
Resolves #2210 
 
### Check List
- [X ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dlvenable — CHANGES_REQUESTED** [review]
This doesn't seem the correct solution to this problem. 

* This may be hiding the underlying issue.
* We should not throw an `IOException` when it isn't an IO Exception.

I think the problem is actually here:

https://github.com/opensearch-project/data-prepper/blob/7a9c1fcd06718b8e2817f63ea72902d4896a58f9/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEvent.java#L279-L281

That code probably has the wrong behavior. What if you have a format string like `foo-${propa}-${propb}` and `propa` is null? This will return `null`. It should probably return `foo--bvalue` right?

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java [hunk 1]
```diff
@@ -48,6 +48,9 @@ public void setupIndex() throws IOException {
 
     @Override
     public String getIndexName(final String dynamicIndexAlias) throws IOException {
+        if (dynamicIndexAlias == null) {
+            throw new IOException("index alias is null");
```
Comment (engechas) [inline data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java:52]: From what I can tell, this will still cause data prepper to crash when the alias is null. Is there a way we can validate that this is not null during initialization? Crashing on initialization rather than during ingestion would be a better user experience

Comment (engechas) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java:52]: > Is there a way we can validate that this is not null during initialization?

It looks like this value is dependent on the events that are ingested. In that case, I don't think validation during initialization is possible. I am in agreement with David's comment.

Comment (kkondaka) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java:52]: @dlvenable @engechas we can go either way. Using null string when the property is missing, vs discarding the event. If the config has `index-name: ${prop}` and the `prop` does not exist in the event, the index-name will become nullstring and it will be discarded anyways.

Comment (asifsmohammed) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java:52]: I think we should not crash Data Prepper, any event at at some point can have null value. I think we should have a null string and log the error.

Comment (engechas) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java:52]: Discarding the event seems reasonable as well. I think we should [log this as a warning here](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java#L142) with some message like "Dropping event due to missing field {}. Field {} is required for the configured DynamicIndexTemplate." and create a custom exception for this case rather than reusing IOException.

Comment (kkondaka) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/DynamicIndexManager.java:52]: @asifsmohammed @engechas I do not think we should log, because this would be logged for every event and there could be millions of events. I have discussed with Dinu and I think introducing a metrics counter is better.

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java [hunk 2]
```diff
@@ -51,6 +51,7 @@ public class OpenSearchSink extends AbstractSink<Record<Event>> {
   public static final String BULKREQUEST_LATENCY = "bulkRequestLatency";
   public static final String BULKREQUEST_ERRORS = "bulkRequestErrors";
   public static final String BULKREQUEST_SIZE_BYTES = "bulkRequestSizeBytes";
+  public static final String DYNAMIC_INDEX_DROPPED_EVENTS = "DynamicIndexDroppedEvents";
```
Comment (engechas) [inline data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java:54]: nit: camelCase

While it is a nit, I believe this is the value populated in the metrics store. We should be consistent. I am fine to address this later

**Review by engechas — APPROVED** [review]
I'm still in agreement that we should not use IOException for a non-IOException, but I am fine to address this later

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java (hunk 2 above)
Comment (kkondaka) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java]: Addressed the comment. But for some reason end to end test is failing.

**Review by engechas — APPROVED** [review]

**Review by dlvenable — CHANGES_REQUESTED** [review]
I think we need to fix the case on the metrics. We are releasing 2.1 soon and having this invalid will end up with a released inconsistency.

Also, I think we should fix this `IOException`.

**Review by dlvenable — APPROVED** [review]
I see we have the metric correct now.

@kkondaka , Can you create an issue to fix the IOException issue?

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java [hunk 3]
```diff
@@ -137,7 +140,8 @@ public void doOutput(final Collection<Record<Event>> records) {
       try {
           indexName = indexManager.getIndexName(event.formatString(indexName));
       } catch (IOException e) {
-	  continue;
+          dynamicIndexDroppedEvents.increment();
```
Comment (dlvenable) [inline data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java:143]: This is still not quite right. If you get an actual `IOException`, your metrics will be invalid.

Since you have these metrics, we really need to throw a different exception here.

**Review by dlvenable — COMMENTED** [review]
@kkondaka , Can you fix the issues still outstanding here?

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java [hunk 4]
```diff
@@ -51,6 +51,7 @@ public class OpenSearchSink extends AbstractSink<Record<Event>> {
   public static final String BULKREQUEST_LATENCY = "bulkRequestLatency";
   public static final String BULKREQUEST_ERRORS = "bulkRequestErrors";
   public static final String BULKREQUEST_SIZE_BYTES = "bulkRequestSizeBytes";
+  public static final String DYNAMIC_INDEX_DROPPED_EVENTS = "dynamicIndexDroppedEvents";
```
Comment (dlvenable) [inline data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java:54]: This metric should probably also be in the `DynamicIndexManager`.

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java (hunk 3 above)
Comment (kkondaka) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java:143]: Makes sense.
