### PR TITLE
Fixed sorting of `includeKeys` and `excludeKeys` in `SinkModel`

### LINKED ISSUE #5695: [BUG] The sink's include_keys feature won't work unless inputs are alphabetically ordered
**Describe the bug**
Say we have a sink A defined like:
```
  sink:
  - opensearch:
      document_root_key: info # My testing involved a document root key
      include_keys: ["foo", "name"]
```
And sink B defined like:
```
  sink:
  - opensearch:
      document_root_key: info # My testing involved a document root key
      include_keys: ["name", "foo"]
```
The two have different outputs. Sink A results in documents retaining both `foo` and `name`, but Sink B results in documents only retaining `name`.  Based on larger inputs, I can confirm that alphabetical order is required.

**To Reproduce**
It's easy to see if you modify the unit test [testJsonStringBuilderWithIncludeKeys](https://github.com/opensearch-project/data-prepper/blob/a08cd7b82f63d4d107bd9469620099fa45af0297/data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java#L971) by appending the following lines:
```
// Test order independence
List<String> includeKeys8a = List.of("foo", "name");
List<String> includeKeys8b = List.of("name", "foo");
final String expectedJsonString8 = "{\"name\":\"hello\",\"foo\":\"bar\"}";

// Succeeds
assertThat(event.jsonBuilder().rootKey("info").includeKeys(includeKeys8a).toJsonString(), equalTo(expectedJsonString8));
        
// Fails
assertThat(event.jsonBuilder().rootKey("info").includeKeys(includeKeys8b).toJsonString(), equalTo(expectedJsonString8));
```

**Of note**
So when the `include_keys` functionality was first added (MR: https://github.com/opensearch-project/data-prepper/pull/2989), the `SinkModel` had a method `preprocessingKeys` that sorted the keys. At some point that code went away but the `searchAndFilter` function within `JacksonEvent` still expects a sorted input. 

Whether the fix should be in `JacksonEvent` or `SinkModel` is beyond my knowledge of this repo.

**Expected behavior**
The sink's `include_keys` feature should not depend on the order of its inputs.

**Environment (please complete the following information):**
1st environment:
 - OS: unknown. 
 - Using AWS's OpenSearch serverless pipeline on May 14th, 2025.

2nd environment in which I ran the above unit test changes:
 - OS: OSX Sequoia 15.5
 - Using main (commit a08cd7b)

### PR DESCRIPTION
**Pull request by mishail**
### Description
To fix #5695 this PR restores sorting of `includeKeys` and `excludeKeys` in `SinkModel`, which was removed for some reason in https://github.com/opensearch-project/data-prepper/pull/3181

### Issues Resolved
Resolves #5695
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mishail** [comment]
@dlvenable are these changes still needed?

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/SinkModel.java [hunk 1]
```diff
@@ -134,15 +134,12 @@ void validateConfiguration() {
         /**
          * Validates both include and exclude keys if they contain /
          */
-        private void validateKeys() {
-            includeKeys.forEach(key -> {
+        private static List<String> validateKeys(List<String> input) {
+            input.forEach(key -> {
                 if(key.contains("/"))
                     throw new InvalidPluginConfigurationException("include_keys cannot contain /");
```
Comment (divbok) [inline data-prepper-api/src/main/java/org/opensearch/dataprepper/model/configuration/SinkModel.java]: You'll need to update the exception message

**Comment by mishail** [comment]
@divbok I've addressed your comment

File: data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java [hunk 2]
```diff
@@ -148,8 +149,8 @@ void sinkModel_with_include_keys() {
         final Map<String, Object> pluginSettings = new LinkedHashMap<>();
         final SinkModel sinkModel = new SinkModel("customSinkPlugin", Arrays.asList("routeA", "routeB"), null, Arrays.asList("bcd", "abc", "efg"), null, pluginSettings);
 
-        assertThat(sinkModel.getExcludeKeys(), equalTo(new ArrayList<String>()));
-        assertThat(sinkModel.getIncludeKeys(), equalTo(Arrays.asList("bcd", "abc", "efg")));
+        assertThat(sinkModel.getExcludeKeys(), is(empty()));
+        assertThat(sinkModel.getIncludeKeys(), contains("abc", "bcd", "efg")); //must be sorted
```
Comment (dlvenable) [inline data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java:153]: @Mishail , This is not verifying the exact order. If you need them sorted, then you should assert equality.

```
assertThat(sinkModel.getIncludeKeys(), equalTo(List.of("abc", "bcd", "efg"));
```

File: data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java [hunk 3]
```diff
@@ -162,10 +163,10 @@ void sinkModel_with_invalid_include_keys() {
     @Test
     void sinkModel_with_exclude_keys() {
         final Map<String, Object> pluginSettings = new LinkedHashMap<>();
-        final SinkModel sinkModel = new SinkModel("customSinkPlugin", Arrays.asList("routeA", "routeB"), null, List.of(), Arrays.asList("abc", "bcd", "efg"), pluginSettings);
+        final SinkModel sinkModel = new SinkModel("customSinkPlugin", Arrays.asList("routeA", "routeB"), null, List.of(), Arrays.asList("bcd", "efg", "abc"), pluginSettings);
 
-        assertThat(sinkModel.getIncludeKeys(), equalTo(new ArrayList<String>()));
-        assertThat(sinkModel.getExcludeKeys(), equalTo(Arrays.asList("abc", "bcd", "efg")));
+        assertThat(sinkModel.getIncludeKeys(), is(empty()));
+        assertThat(sinkModel.getExcludeKeys(), contains("abc", "bcd", "efg")); //must be sorted
```
Comment (dlvenable) [inline data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java:169]: Same comment about verifying equality.

**Review by dlvenable — CHANGES_REQUESTED** [review]
Thanks @Mishail for the contribution. I have some comments about the tests so that they assert for the sorted order.

File: data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java (hunk 2 above)
Comment (mishail) [reply data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java:153]: I politely disagree. `contains` does verify the order, it also gives you a hint where the order is broken

```
assertThat(List.of(1,2,3), contains(1,2,3))  - pass
assertThat(List.of(1,2,3), contains(1,3,2))  - fails
Expected: iterable containing [<1>, <3>, <2>]
     but: item 1: was <2>

```

Comment (mishail) [reply data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java:153]: @dlvenable please take a look at my comment and let me knwo if you still want to make me to change that. I do believe my changes are correct and check the order.

Comment (dlvenable) [reply data-prepper-api/src/test/java/org/opensearch/dataprepper/model/configuration/SinkModelTest.java:153]: @Mishail , Thank you for clarifying that. The name itself is unclear, but this should work.

**Comment by mishail** [comment]
@dlvenable could you please merge this?

**Comment by dlvenable** [comment]
Thank you for the contribution @Mishail !
