### PR TITLE
Health check auth bug

### LINKED ISSUE #1600: [BUG] Health Check returns 401 when Auth is enabled
**Describe the bug**
Health Check to Log Source or Otel Source returns 401 when Auth is enabled. If we have data prepper fronted by load balancer and load balancer is doing health check, the health check path should be excluded from Auth.

**To Reproduce**
1. Configure the Data Pepper Pipeline config with Auth
```
source:
  http:
    authentication:
      http_basic:
        username: my-user
        password: my_s3cr3t
```
2. Start Data Prepper
3. curl http://localhost:2021/health

**Expected behavior**
return Http status 200 with response {}.

**Screenshots**
```
curl http://localhost:2021/health
401 Unauthorized%
```

**Environment (please complete the following information):**
 - OS: Linux

### PR DESCRIPTION
**Pull request by dapowers87**
### Description
Fix auth for gRPC provider. 
 
### Issues Resolved
#1600 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java [hunk 1]
```diff
@@ -363,6 +364,139 @@ void start_with_Health_configured_includes_HealthCheck_service() throws IOExcept
         verify(serverBuilder, never()).service(eq("/health"),isA(HealthCheckService.class));
     }
 
+    @Test
+    void start_with_Health_configured_includes_HealthCheck_service_Unauthenticated_disabled() throws IOException {
```
Comment (chenqi0805) [inline data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java:368]: This test case seems redundant to me as I am not sure what it covers that the following two tests fail to cover.

**Review by chenqi0805 — COMMENTED** [review]
Overall looks good. Just one inline comment.

File: data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java (hunk 1 above)
Comment (dapowers87) [reply data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java:368]: This test confirms that the appropriate decorator was added to the server builder

**Review by chenqi0805 — APPROVED** [review]

File: data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java [hunk 2]
```diff
@@ -363,6 +364,139 @@ void start_with_Health_configured_includes_HealthCheck_service() throws IOExcept
...
+        try (MockedStatic<Server> armeriaServerMock = Mockito.mockStatic(Server.class);
+             MockedStatic<GrpcService> grpcServerMock = Mockito.mockStatic(GrpcService.class)) {
+            armeriaServerMock.when(Server::builder).thenReturn(serverBuilder);
+            grpcServerMock.when(GrpcService::builder).thenReturn(grpcServiceBuilder);
+            when(grpcServiceBuilder.addService(any(ServerServiceDefinition.class))).thenReturn(grpcServiceBuilder);
+            when(grpcServiceBuilder.useClientTimeoutHeader(anyBoolean())).thenReturn(grpcServiceBuilder);
+
+            when(server.stop()).thenReturn(completableFuture);
```
Comment (dlvenable) [inline data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java:376]: Probably most of this can be moved out of the try-with-resources.

File: data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java [hunk 3]
```diff
@@ -363,6 +364,139 @@ void start_with_Health_configured_includes_HealthCheck_service() throws IOExcept
...
+        }
+
+        verify(grpcServiceBuilder, times(1)).useClientTimeoutHeader(false);
+        verify(grpcServiceBuilder, times(1)).useBlockingTaskExecutor(true);
+        verify(grpcServiceBuilder).addService(isA(HealthGrpcService.class));
+        verify(serverBuilder, never()).service(eq("/health"),isA(HealthCheckService.class));
+    }
+
+    @Test
+    public void testHealthCheckUnauthNotAllowed() {
```
Comment (dlvenable) [inline data-prepper-plugins/otel-metrics-source/src/test/java/com/amazon/dataprepper/plugins/source/otelmetrics/OTelMetricsSourceTest.java:410]: I'd consider putting this test and the `testHealthCheckUnauthAllowed` into a `@Nested` sub-class. You can configure all the common setup (everything except `unauthenticated_health_check`). This will make it easier to tell the difference between these two tests.
