### PR TITLE
Handle delayed sync between GSI and primary table when DDB is used as Source Coordination Store

### LINKED ISSUE #5468: [BUG] S3 source folder partitioning has noisy log that causes delay in processor folders
**Describe the bug**
The S3 source with folder partitioning enabled will quickly acquire and give up a partition if that folder has no objects to process. With the dynamodb source coordination store, this can lead to a failure to give up the partition because the Global Secondary Index on the table has not replicated the change, which leads to the folder partition not getting acquired again until it's ownership times out

```
org.opensearch.dataprepper.model.source.coordinator.exceptions.PartitionNotOwnedException: The partition is no longer owned by this instance of Data Prepper. The partition ownership timeout most likely expired and was grabbed by another instance of Data Prepper
at org.opensearch.dataprepper.core.sourcecoordination.LeaseBasedSourceCoordinator.validatePartitionOwnership(LeaseBasedSourceCoordinator.java:437) ~[data-prepper-core-2.x.418.jar:?]
	at org.opensearch.dataprepper.core.sourcecoordination.LeaseBasedSourceCoordinator.giveUpPartitionInternal(LeaseBasedSourceCoordinator.java:362) ~[data-prepper-core-2.x.418.jar:?]
	at org.opensearch.dataprepper.core.sourcecoordination.LeaseBasedSourceCoordinator.giveUpPartition(LeaseBasedSourceCoordinator.java:351) ~[data-prepper-core-2.x.418.jar:?]
	at org.opensearch.dataprepper.plugins.source.s3.ScanObjectWorker.processFolderPartition(ScanObjectWorker.java:287) ~[s3-source-2.x.418.jar:?]
	at org.opensearch.dataprepper.plugins.source.s3.ScanObjectWorker.startProcessingObject(ScanObjectWorker.java:189) ~[s3-source-2.x.418.jar:?]
	at org.opensearch.dataprepper.plugins.source.s3.ScanObjectWorker.run(ScanObjectWorker.ja
```

**Expected behavior**
The S3 source with folder partitioning should handle race conditions better. The simplest way to do this would be to add a new function to `LeaseBasedSourceCoordinator` `giveUpPartitionWithRetries()` where the partition is grabbed from the source coordination store X amount of times to try to give up the partition (call regular `giveUpPartition` method with back off and retry)

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by divbok**
### Description
Adding retries and backoff to handle delayed sync between GSI and primary table when DDB is used as Source Coordination Store 

### Issues Resolved
Resolves #5468 
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/core/sourcecoordination/LeaseBasedSourceCoordinator.java [hunk 1]
```diff
@@ -343,14 +343,37 @@ private void updatePartitionOwnership(final String partitionKey, final Duration
...
+        giveUpPartitionInternalWithRetries(partitionKey, null);
     }
 
     @Override
     public void giveUpPartition(final String partitionKey, final Instant priorityTimestamp) {
-        giveUpPartitionInternal(partitionKey, priorityTimestamp);
+        giveUpPartitionInternalWithRetries(partitionKey, priorityTimestamp);
     }
 
+    public void giveUpPartitionInternalWithRetries(final String partitionKey, final Instant priorityTimestamp) {
```
Comment (graytaylor0) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/core/sourcecoordination/LeaseBasedSourceCoordinator.java:354]: May be lower blast radius to add a new function to the interface


```
    @Override
    public void giveUpPartition(final String partitionKey, final Instant priorityTimestamp, final int maxRetries) {
        giveUpPartitionInternalWithRetries(partitionKey, priorityTimestamp);
    }
```

Then just use this method in S3 scan folder partition for now. Also the internal method should be private.

**Review by graytaylor0 — APPROVED** [review]

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/core/sourcecoordination/LeaseBasedSourceCoordinator.java [hunk 2]
```diff
@@ -351,6 +351,30 @@ public void giveUpPartition(final String partitionKey, final Instant priorityTim
...
+        final long backoffMillis = 200;
+        for (int attempt = 1; attempt <= maxRetries; attempt++) {
+            try {
+                giveUpPartitionInternal(partitionKey, priorityTimestamp);
+                return;
+            } catch (PartitionNotOwnedException e) {
+                if (attempt == maxRetries) {
+                    throw e;
+                }
+                LOG.warn("Partition {} not owned on attempt {}/{}. Retrying...", partitionKey, attempt, maxRetries);
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/core/sourcecoordination/LeaseBasedSourceCoordinator.java:365]: Let's avoid ellipses. When will it retry? Is it trying now? 

Maybe we can say something like: `Will retry giving up the partition`.

**Review by dlvenable — APPROVED** [review]

**Review by graytaylor0 — APPROVED** [review]

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/core/sourcecoordination/LeaseBasedSourceCoordinator.java [hunk 3]
```diff
@@ -351,6 +351,31 @@ public void giveUpPartition(final String partitionKey, final Instant priorityTim
...
+        final long backoffMillis = 200;
+        for (int attempt = 1; attempt <= maxRetries; attempt++) {
+            try {
+                giveUpPartitionInternal(partitionKey, priorityTimestamp);
+                return;
+            } catch (PartitionNotOwnedException e) {
+                if (attempt == maxRetries) {
+                    throw e;
+                }
+                LOG.warn("Partition {} not owned on attempt {}/{}. Will retry giving up the partition", partitionKey,
```
Comment (san81) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/core/sourcecoordination/LeaseBasedSourceCoordinator.java:365]: May be it is my understanding - but this sentence is confusing to me. If I read this sentence right, it says that it is trying to give up a partition that it is not owning!! Why is it giving up a partition that it is not owning?
