### PR TITLE
Fix documentErrors metric incorrectly counting version conflict error…

### LINKED ISSUE #5376: [BUG]
**Describe the bug**
The `documentVersionConflictErrrors` in the OpenSearch sink are not sent to DLQ and are not a true documentError since it means the latest document is in OpenSearch already. Due to this, it should not be included in the `documentErrors` metric, as this is a confusing user experience.

**Expected behavior**
Do not include `documentVersionConflictError` in the overall `documentErrors` metric

### PR DESCRIPTION
**Pull request by Keyur-S-Patel**
### Description

In `BulkRetryStrategy.handleFailures()`, the `documentErrorsCounter` was being incremented for all item-level errors, including version conflict errors. Version conflict errors are not true document errors — they indicate the latest version of the document already exists in OpenSearch and are not sent to the DLQ. This caused the `documentErrors` metric to be inflated, creating a confusing user experience.

This change moves `documentErrorsCounter.increment()` and `getDocumentStatusCounter().increment()` into the `else` branch so they only fire for actual non-retryable failures, skipping version conflicts. This matches the existing behavior already present in `createBulkRequestForRetry()`. A unit test was added to verify that version conflicts only increment `documentsVersionConflictErrors` and not `documentErrors`.

### Issues Resolved

Resolves #5376

### Check List
- [x] New functionality includes testing.
- [x] New functionality has a documentation issue. Please link to it in this PR.
- [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [[here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md)](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java [hunk 1]
```diff
@@ -452,9 +452,9 @@ private void handleFailures(final AccumulatingBulkRequest<BulkOperationWrapper,
                             .withBulkOperation(bulkOperation)
                             .withBulkResponseItem(bulkItemResponse)
                             .build());
+                    documentErrorsCounter.increment();
```
Comment (graytaylor0) [inline data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java:458]: Thanks for making this change! there was a discussion here on having a condition to skip applying documentErrors only if the `document_version_type` is set to external. I think that in some cases there can be a true failure when not using external versioning. Can we add that check here?

**Review by graytaylor0 — DISMISSED** [review]

**Review by graytaylor0 — APPROVED** [review]

**Review by oeyh — APPROVED** [review]
