### PR TITLE
Make expressions evaluating on keys with List or Map values not throw an exception

### LINKED ISSUE #4109: [BUG] Attempting to evaluate if a key is null throws an Exception if the value is a List<String> for conditional expressions
**Describe the bug**
Evaluating a statement like

```
when: '/my_field == null'
```

will throw an Exception if the value of my_field does not match the expression ANTLR language

**To Reproduce**
1. Create a pipeline with a when condition equal to `/my_field == null`
2. Send an Event where my_field is an array, such as `{ "my_field": ["2024-02-09 19:26:25.308", "2024-02-09 19:26:25.308"] }`
3. Observe the exception

```
2024-02-12T10:28:13,789 [test-pipeline-processor-worker-1-thread-1] ERROR org.opensearch.dataprepper.expression.ParseTreeEvaluator - Unable to evaluate event
org.opensearch.dataprepper.expression.ExpressionCoercionException: Unsupported type for value [2024-02-09 19:26:25.308, 2024-02-09 19:26:25.308]
	at org.opensearch.dataprepper.expression.ParseTreeCoercionService.lambda$new$0(ParseTreeCoercionService.java:33) ~[data-prepper-expression-2.7.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.expression.ParseTreeCoercionService.resolveJsonPointerValue(ParseTreeCoercionService.java:103) ~[data-prepper-expression-2.7.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.expression.ParseTreeCoercionService.coercePrimaryTerminalNode(ParseTreeCoercionService.java:69) ~[data-prepper-expression-2.7.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.expression.ParseTreeEvaluatorListener.visitTerminal(ParseTreeEvaluatorListener.java:69) ~[data-prepper-expression-2.7.0-SNAPSHOT.jar:?]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:29) ~[antlr4-runtime-4.10.1.jar:4.10.1]
```

**Expected behavior**
For checks of `/my_field != null` or `/my_field == null`, we should convert the value of my_field to an Object and check that it is null or not null, and should not rely on the ANTLR language for conditional expressions

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by graytaylor0**
### Description
Fixes a bug where the Data Prepper expression language would throw exceptions if the value of a json pointer was a List or Map, for instance if the expression is `/my_field == null' and my_field is a List, an exception is thrown instead of evaluating whether my_field is null 
 
### Issues Resolved
Resolves #4109 
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by oeyh — DISMISSED** [review]

File: data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java [hunk 1]
```diff
@@ -350,11 +323,9 @@ private static Stream<Arguments> provideSupportedJsonPointerValues() {
...
                 Arguments.of(1.1f),
                 Arguments.of(1.1),
+                Arguments.of(List.of("test_value")),
+                Arguments.of(Map.of("test_key", "test_value")),
                 Arguments.of((Object) null)
         );
     }
-
-    private static Stream<Arguments> provideUnSupportedJsonPointerValues() {
-        return Stream.of(Arguments.of(new HashMap<>()));
```
Comment (dlvenable) [inline data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java:358]: Instead of `new HashMap<>()` could you provide some other class? Perhaps `new AtomicBoolean()` or `new JsonFactory()`.

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java (hunk 1 above)
Comment (graytaylor0) [reply data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java:358]: I'll try those! Thanks I tried some other classes but nothing was failing

Comment (dlvenable) [reply data-prepper-expression/src/test/java/org/opensearch/dataprepper/expression/ParseTreeCoercionServiceTest.java:358]: Thanks for trying. I do see that these are integration tests. Can you find the corresponding unit tests and use mocking to keep the code coverage?

**Review by oeyh — APPROVED** [review]
