### PR TITLE
Fix for [BUG] Data Prepper is losing connections from S3 pool

### LINKED ISSUE #3809: [BUG] Data Prepper is losing connections from S3 pool
**Describe the bug**

Data Prepper's S3 source can loose connections from the AWS SDK connection pool. See the following error.

```
2023-11-30T22:35:53.601 [Thread-11] ERROR org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker - Error reading from S3 object: s3ObjectReference=[bucketName=my-bucket, key=not-valid-gzip.gz]. Unable to execute HTTP request: Timeout waiting for connection from pool
2023-11-30T22:35:53.601 [Thread-11] ERROR org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Error processing from S3: Unable to execute HTTP request: Timeout waiting for connection from pool. Retrying with exponential backoff.
```

After this happens, Data Prepper's `s3` source is unable to reclaim the connection from the connection pool. Data Prepper can run for hours or days without getting this back.

**To Reproduce**
1. Configure an S3 bucket with SQS queue
2. Create a pipeline with an `s3` source. Configure it to use `automatic` compression (using `gzip` would probably work too)
3. Upload a file which is uncompressed, but has the `.gz` extension `not-valid-gzip.gz`
4. Wait a while - maybe 30 minutes.
5. You see the error.
6. Upload a valid file. You will see the same error because the S3 AWS SDK is out of connections in the pool.

**Expected behavior**

Data Prepper will not reach this point of running out of connections.

**Environment (please complete the following information):**

Data Prepper 2.6.0

**Additional context**

Here are the logs from when the transition occurred. The `GZIP encoding specified but data did contain gzip magic header` log is expected since this is not a Gzip file.

```
2023-11-30T22:34:21.343 [Thread-11] INFO  org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Received 1 messages from SQS. Processing 1 messages.
2023-11-30T22:34:21.387 [Thread-11] ERROR org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Error processing from S3: GZIP encoding specified but data did contain gzip magic header. Retrying with exponential backoff.
2023-11-30T22:34:21.387 [Thread-11] ERROR org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker - Error reading from S3 object: s3ObjectReference=[bucketName=my-bucket, key=not-valid-gzip.gz]. GZIP encoding specified but data did contain gzip magic header
2023-11-30T22:34:21.387 [Thread-11] INFO  org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Pausing SQS processing for 21.3 seconds due to an error in processing.
2023-11-30T22:34:51.343 [Thread-11] INFO  org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker - Read S3 object: [bucketName=my-bucket, key=not-valid-gzip.gz]
2023-11-30T22:34:51.343 [Thread-11] INFO  org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Received 1 messages from SQS. Processing 1 messages.
2023-11-30T22:35:53.601 [Thread-11] ERROR org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker - Error reading from S3 object: s3ObjectReference=[bucketName=my-bucket, key=not-valid-gzip.gz]. Unable to execute HTTP request: Timeout waiting for connection from pool
2023-11-30T22:35:53.601 [Thread-11] ERROR org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Error processing from S3: Unable to execute HTTP request: Timeout waiting for connection from pool. Retrying with exponential backoff.
2023-11-30T22:35:53.601 [Thread-11] INFO  org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Pausing SQS processing for 18.477 seconds due to an error in processing.
2023-11-30T22:36:12.134 [Thread-11] INFO  org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker - Read S3 object: [bucketName=my-bucket, key=not-valid-gzip.gz]
2023-11-30T22:36:12.134 [Thread-11] INFO  org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Received 1 messages from SQS. Processing 1 messages.
2023-11-30T22:37:13.656 [Thread-11] ERROR org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Error processing from S3: Unable to execute HTTP request: Timeout waiting for connection from pool. Retrying with exponential backoff.
```

Also, here are the logs from the first GZip failure. This shows the timestamps for the expected errors.

```
2023-11-30T22:09:51.178 [Thread-11] INFO  org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Received 1 messages from SQS. Processing 1 messages.
2023-11-30T22:09:51.179 [Thread-11] INFO  org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker - Read S3 object: [bucketName=my-bucket, key=not-valid-gzip.gz]
2023-11-30T22:09:51.234 [Thread-11] ERROR org.opensearch.dataprepper.plugins.source.s3.S3ObjectWorker - Error reading from S3 object: s3ObjectReference=[bucketName=my-bucket, key=not-valid-gzip.gz]. GZIP encoding specified but data did contain gzip magic header
2023-11-30T22:09:51.234 [Thread-11] ERROR org.opensearch.dataprepper.plugins.source.s3.SqsWorker - Error processing from S3: GZIP encoding specified but data did contain gzip magic header. Retrying with exponential backoff.
```

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
Fix for [BUG] Data Prepper is losing connections from S3 pool.
Root cause for this issue is that the input stream opened in codec is not closed.
 
Resolves #3809 
### Issues Resolved
Resolves #3809 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/codec/InputCodec.java [hunk 1]
```diff
@@ -31,8 +32,19 @@ public interface InputCodec {
...
             DecompressionEngine decompressionEngine,
-            Consumer<Record<Event>> eventConsumer) throws IOException;
+            Consumer<Record<Event>> eventConsumer) throws IOException {
+        Objects.requireNonNull(inputFile);
+        Objects.requireNonNull(eventConsumer);
+        InputStream inputStream = inputFile.newStream();
+        try {
+            parse(decompressionEngine.createInputStream(inputStream), eventConsumer);
+            inputStream.close();
+        } catch (Exception e) {
```
Comment (dlvenable) [inline data-prepper-api/src/main/java/org/opensearch/dataprepper/model/codec/InputCodec.java:45]: Can we make use of `AutoCloseable` and put this in a try-with-resources statement?

```
try(InputStream inputStream = inputFile.newStream()) {
  parse(decompressionEngine.createInputStream(inputStream), eventConsumer);
}
```

**Review by dlvenable — CHANGES_REQUESTED** [review]

**Review by dlvenable — DISMISSED** [review]

**Review by asifsmohammed — DISMISSED** [review]

**Review by dlvenable — APPROVED** [review]

**Review by asifsmohammed — APPROVED** [review]
