### PR TITLE
Fix for Issue 5531

### LINKED ISSUE #5531: [BUG] S3 Scan with multiple buckets does not read the S3DataSelection correctly
**Describe the bug**
When S3 scans multiple buckets, it doesn't load the newly added S3DataSelection config parameter correctly at the bucket level.

In this case, the first bucket should be scanned only for metadata_only, and the second bucket scanned only for data_only. 
~~~
    s3:
      codec:
        ndjson:
      compression: none
      aws:
        region: "us-east-1"
      default_bucket_owner: 802041417063
      scan:
        scheduling:
          interval: PT6M
        buckets:
          - bucket:
              name: "offlinebatch"
              data_selection: metadata_only
              filter:
                include_prefix:
                  - sagemaker/sagemaker_djl_batch_input
          - bucket:
              name: "offlinebatch"
              data_selection: data_only
              filter:
                include_prefix: 
                  - sagemaker/output/
~~~ 

But in reality, from my testing the S3Scan scans data content for the first bucket too. So it becomes something similar like this 
~~~
        buckets:
          - bucket:
              name: "offlinebatch"
              data_selection: data_only
              filter:
                include_prefix:
                  - sagemaker/sagemaker_djl_batch_input
                  - sagemaker/output/
~~~

So overall this is not the intention of the newly added "data_selection" config that should be applied to each bucket. I think there should be a bug somewhere in the pipeline creation with this multiple bucket source. 

**To Reproduce**
1. Use the above pipeline source of S3 scanning multiple buckets with different "data_selection"
2. Run the pipeline
3. Check the pipeline results
4. You will see that the content of the first bucket in the input folder is flowing through the pipeline processors which shouldn't happen. 

**Expected behavior**
Different S3 bucket with different "data_selection" should scan based on the config value.

**Screenshots**
Below is the full pipeline for reference.
~~~
ml-batch-job-pipeline:
  source:
    s3:
      codec:
        ndjson:
      compression: none
      aws:
        region: "us-east-1"
      default_bucket_owner: <your account>
      scan:
        scheduling:
          interval: PT6M
        buckets:
          - bucket:
              name: "offlinebatch"
              data_selection: metadata_only
              filter:
                include_prefix:
                  - sagemaker/sagemaker_djl_batch_input
          - bucket:
              name: "offlinebatch"
              data_selection: data_only
              filter:
                include_prefix: 
                  - sagemaker/output/

  buffer:
    bounded_blocking:
      buffer_size: 2048 # max number of records the buffer accepts
      batch_size: 512 # max number of records the buffer drains after each read

  processor:
    - ml:
        host: "<your host url>"
        aws_sigv4: true
        action_type: "batch_predict"
        service_name: "sagemaker"
        model_id: "<your model id>"
        output_path: "s3://offlinebatch/sagemaker/output"
        aws:
          region: "us-east-1"
        ml_when: /bucket == "offlinebatch"
    - copy_values:
        entries:
          - to_key: chapter
            from_key: /content/0
          - to_key: title
            from_key: /content/1
          - to_key: chapter_embedding
            from_key: /SageMakerOutput/0
          - to_key: title_embedding
            from_key: /SageMakerOutput/1
    - delete_entries:
        with_keys: [content, SageMakerOutput]
  
  route:
      - ml-ingest-route: "/chapter != null and /title != null"

  sink:
    - stdout:
    - opensearch:
        hosts: ["<your host url>"]
        aws_sigv4: true
        index: "test-nlp-index"
        routes: [ml-ingest-route]
        username: "<your user name>"
        password: "<your password>"

~~~

**Environment (please complete the following information):**
 - OS: Mac OS latest
 - Version: Data Prepper running from main branch

**Additional context**

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
Fixes issue 5531.
Root causes for the bug -
1. The newly added metadata_only option only maps S3DataSelection to a bucket, which means there can only one data selection for a given bucket
2. The existing s3 scan code does not handle if the same bucket is specified twice because the scan time for the bucket is updated first time, making the second scan not possible
This change fixes both issues.
 
### Issues Resolved
Resolves #5531 
 
### Check List
- [ X] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [X ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by Zhangxunmt — APPROVED** [review]

File: data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java [hunk 1]
```diff
@@ -116,16 +116,23 @@ public ScanObjectWorker(final S3Client s3Client,
...
         this.s3ObjectHandler= s3ObjectHandler;
         this.bucketOwnerProvider = bucketOwnerProvider;
         this.sourceCoordinator = sourceCoordinator;
         this.s3ScanSchedulingOptions = s3SourceConfig.getS3ScanScanOptions().getSchedulingOptions();
         this.bucketDataSelectionMap = new HashMap<>();
         for (S3ScanBucketOptions bucketOption: s3SourceConfig.getS3ScanScanOptions().getBuckets()) {
+
             if (bucketOption.getS3ScanBucketOption() != null) {
-                bucketDataSelectionMap.put(bucketOption.getS3ScanBucketOption().getName(), bucketOption.getS3ScanBucketOption().getDataSelection());
+                final String bucketName = bucketOption.getS3ScanBucketOption().getName();
```
Comment (graytaylor0) [inline data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/ScanObjectWorker.java:127]: Should there be a unit test covering this?

**Review by graytaylor0 — APPROVED** [review]
