### PR TITLE
Fix uncaught exception causing pipeline shutdown 

### LINKED ISSUE #3184: [BUG] ParseJson processor overwrites fields in Otel Log Event causing pipeline to shut down
**Describe the bug**
In a pipeline with OTEL log source and parse_json processor, it's possible that the processor overwrites `attributes` field in the event, changing its value from a map to a string. This will subsequently cause ClassCastException in the sink when it calls `JacksonOtelLog.toJsonString()`. The exception is currently not caught and will trigger a pipeline shutdown.

**To Reproduce**
With this pipeline config:
```yaml
version: "2"
otel-logs-pipeline:
  source:
    otel_logs_source:
      path: "/${pipelineName}/v1/logs"
      unframed_requests: true
      ssl: false
  processor:
    - parse_json:
        source: "body"
  sink:
    - stdout:
```

and this test data:

```
{
  "resourceLogs": [
    {
      "resource": {
        "attributes": [
          {
            "key": "resource-attr",
            "value": {
              "stringValue": "resource-attr-val-01"
            }
          }
        ]
      },
      "scopeLogs": [
        {
          "scope": {},
          "logRecords": [
            {

              "name": "logA",
              "body": {
                "stringValue": "{\"attributes\": \"hello\"}"
              },
              "attributes": [
                {
                  "key": "app",
                  "value": {
                    "stringValue": "server"
                  }
                },
                {
                  "key": "instance_num",
                  "value": {
                    "intValue": "1"
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

Pipeline shutdown will be triggered:
```
2023-08-16T23:38:15,731 [otel-logs-pipeline-sink-worker-2-thread-1] ERROR org.opensearch.dataprepper.pipeline.common.PipelineThreadPoolExecutor - Pipeline [otel-logs-pipeline] process worker encountered a fatal exception, cannot proceed further
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.TextNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.TextNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader 'app')
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at org.opensearch.dataprepper.pipeline.common.PipelineThreadPoolExecutor.afterExecute(PipelineThreadPoolExecutor.java:70) [data-prepper-core-2.4.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.TextNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.TextNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader 'app')
	at org.opensearch.dataprepper.model.log.JacksonOtelLog.toJsonString(JacksonOtelLog.java:112) ~[data-prepper-api-2.4.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.model.event.JacksonEvent$JsonStringBuilder.toJsonString(JacksonEvent.java:578) ~[data-prepper-api-2.4.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.sink.StdOutSink.checkTypeAndPrintObject(StdOutSink.java:56) ~[common-2.4.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.plugins.sink.StdOutSink.output(StdOutSink.java:48) ~[common-2.4.0-SNAPSHOT.jar:?]
	at org.opensearch.dataprepper.pipeline.Pipeline.lambda$publishToSinks$5(Pipeline.java:336) ~[data-prepper-core-2.4.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	... 2 more
```

**Expected behavior**
Pipeline should continue to run in the above situation.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by oeyh**
### Description
Fixes #3184 by:
- Catch ClassCastException in JacksonOtelLog.toJsonString()
- Add `overwrite_if_exists` option to parse-json processor. It defaults to true to avoid breaking change. Set it to false will prevent fields from being overwritten by the processor.
 
### Issues Resolved
Resolves #3184
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java [hunk 1]
```diff
@@ -109,7 +109,12 @@ public static JacksonOtelLog.Builder builder() {
 
     @Override
     public String toJsonString() {
-        final ObjectNode attributesNode = (ObjectNode) getJsonNode().get("attributes");
+        ObjectNode attributesNode;
+        try {
+            attributesNode = (ObjectNode) getJsonNode().get("attributes");
+        } catch (final ClassCastException e) {
+            attributesNode = null;
```
Comment (graytaylor0) [inline data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java:116]: Would this mean that there are attributes getting dropped, or that there are not really any attributes required? Could you explain what the end user experience is when this happens? Do they care about these attributes being dropped?

File: data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java [hunk 2]
```diff
@@ -31,6 +31,9 @@ public class ParseJsonProcessorConfig {
     @JsonProperty("tags_on_failure")
     private List<String> tagsOnFailure;
 
+    @JsonProperty("overwrite_if_key_exists")
```
Comment (graytaylor0) [inline data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java:34]: Should this be `overwrite_if_destination_exists` to align with the naming in this processor?

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java (hunk 1 above)
Comment (dlvenable) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java:116]: I was concerned here as well. But, it shouldn't be dropped. It just won't be flattened. As I understand this, the `toJsonString` will still include `attributes` because we are not calling `flattenedJsonNode.remove("attributes")`.

Is this correct?

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java [hunk 3]
```diff
@@ -109,7 +109,12 @@ public static JacksonOtelLog.Builder builder() {
 
     @Override
     public String toJsonString() {
-        final ObjectNode attributesNode = (ObjectNode) getJsonNode().get("attributes");
+        ObjectNode attributesNode;
```
Comment (dlvenable) [inline data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java:112]: Try to avoid throwing exceptions when possible as they have a performance impact.

Also, we can avoid the `deepCopy()` in this situation.

```
Object anyAttributes = getJsonNode().get("attributes");
if(anyAttributes instanceof ObjectNode) {
    final ObjectNode flattenedJsonNode = getJsonNode().deepCopy();
    flattenedJsonNode.remove("attributes");
    // existing loop
    return flattenedJsonNode.toString();
}
return super.toJsonString();
```

File: data-prepper-api/src/test/java/org/opensearch/dataprepper/model/log/JacksonOtelLogTest.java [hunk 4]
```diff
@@ -149,5 +149,16 @@ public void testHistogramToJsonString() throws JSONException {
         String expected = String.format(file, TEST_TIME_KEY1, TEST_KEY2);
         JSONAssert.assertEquals(expected, actual, false);
     }
+
+    @Test
+    public void testDeformedAttributesToJsonStringNotThrow() {
```
Comment (dlvenable) [inline data-prepper-api/src/test/java/org/opensearch/dataprepper/model/log/JacksonOtelLogTest.java:154]: Please rename this - "NotThrow" is not very descriptive. And "deformed" is a little vague.

Perhaps `non_object_attributes_toJsonString_serializes_as_is`?

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java (hunk 1 above)
Comment (oeyh) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java:116]: If ClassCastException is caught here, it means the "attributes" field collected by Otel source plugin has already been overwritten (the damage has been done). Catching the exception here and setting `attributesNode` to null only prevents the pipeline from shutting down. 

>  The toJsonString will still include attributes

This is correct. But now the `attributes` field will contain whatever uncovered by the processor (such as parse-json), rather than those collected and decoded by Otel source.

File: data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java (hunk 2 above)
Comment (oeyh) [reply data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java:34]: I'm open to the change. But one thing to consider is that destination can be unset, in that case, key-value pairs are being written to event root, and this added option controls whether those key-value pairs overwrite existing keys at root.

File: data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java (hunk 3 above)
Comment (oeyh) [reply data-prepper-api/src/main/java/org/opensearch/dataprepper/model/log/JacksonOtelLog.java:112]: Thanks for the suggestion. This makes sense.

File: data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java (hunk 2 above)
Comment (oeyh) [reply data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java:34]: Will update. This makes sense.

**Review by graytaylor0 — DISMISSED** [review]

File: data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java (hunk 2 above)
Comment (dlvenable) [reply data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java:34]: @oeyh , You need to change the value in line 34 as well.

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java (hunk 2 above)
Comment (oeyh) [reply data-prepper-plugins/parse-json-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/parsejson/ParseJsonProcessorConfig.java]: Done.

**Review by dlvenable — DISMISSED** [review]
Thanks @oeyh !

**Comment by dlvenable** [comment]
@oeyh , The unit tests are failing:

```
ParseJsonProcessorTest > test_when_dataFieldEqualToRootField_then_notOverwritesOriginalFields() FAILED
    java.lang.AssertionError at ParseJsonProcessorTest.java:430
```

**Review by dlvenable — APPROVED** [review]

**Comment by graytaylor0** [comment]
Noticed this exception in the java 17 build action 

```
ParseJsonProcessorTest > test_when_dataFieldEqualToRootField_then_notOverwritesOriginalFields() FAILED
    java.lang.AssertionError at ParseJsonProcessorTest.java:430
```

**Review by graytaylor0 — APPROVED** [review]
