### PR TITLE
Correctly add compression extensions to the generated S3 sink keys

### LINKED ISSUE #3158: [BUG] S3 Sink Avro Output issues
**Describe the bug**
A few bugs found for S3 Sink Avro output codecs:
1. With `compression: gzip` specified, the files are still uploaded with just a `.avro` suffix. This should be `.avro.gz`
2. The contents of the avro file show null for all fields:
```
{"version":null,"srcport":null,"dstport":null,"accountId":null,"interfaceId":null,"srcaddr":null,"dstaddr":null,"start":null,"end":null,"protocol":null,"packets":null,"bytes":null,"action":null,"logStatus":null}
{"version":null,"srcport":null,"dstport":null,"accountId":null,"interfaceId":null,"srcaddr":null,"dstaddr":null,"start":null,"end":null,"protocol":null,"packets":null,"bytes":null,"action":null,"logStatus":null}
{"version":null,"srcport":null,"dstport":null,"accountId":null,"interfaceId":null,"srcaddr":null,"dstaddr":null,"start":null,"end":null,"protocol":null,"packets":null,"bytes":null,"action":null,"logStatus":null}
{"version":null,"srcport":null,"dstport":null,"accountId":null,"interfaceId":null,"srcaddr":null,"dstaddr":null,"start":null,"end":null,"protocol":null,"packets":null,"bytes":null,"action":null,"logStatus":null}
```
3. The timestamp in the file name is 12 hours behind UTC. I am not sure what the "correct" time is but UTC seems logical

**To Reproduce**
Sink config:
```
sink:
    - s3:
        aws:
          region: "us-west-2"
          sts_role_arn: "<my role>"
        bucket: "my-sink-bucket"
        object_key:
          path_prefix: "s3-sink"
        threshold:
          event_collect_timeout: 600s
        compression: "gzip"
        codec:
          avro:
            schema: >
              {
                "type" : "record",
                "namespace" : "org.opensearch.dataprepper.examples",
                "name" : "VpcFlowLog",
                "fields" : [
                  { "name" : "version", "type" : ["null", "string"]},
                  { "name" : "srcport", "type": ["null", "int"]},
                  { "name" : "dstport", "type": ["null", "int"]},
                  { "name" : "accountId", "type" : ["null", "string"]},
                  { "name" : "interfaceId", "type" : ["null", "string"]},
                  { "name" : "srcaddr", "type" : ["null", "string"]},
                  { "name" : "dstaddr", "type" : ["null", "string"]},
                  { "name" : "start", "type": ["null", "int"]},
                  { "name" : "end", "type": ["null", "int"]},
                  { "name" : "protocol", "type": ["null", "int"]},
                  { "name" : "packets", "type": ["null", "int"]},
                  { "name" : "bytes", "type": ["null", "int"]},
                  { "name" : "action", "type": ["null", "string"]},
                  { "name" : "logStatus", "type" : ["null", "string"]}
                ]
              }
```

**Screenshots**
File name times example:
image

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

Supports adding the compression extension for keys generated for the S3 sink. This also avoids adding the extension when the codec supports internal compression.
 
### Issues Resolved
Resolves #3158
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/StandardExtensionProvider.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+    static ExtensionProvider create(OutputCodec outputCodec, CompressionOption compressionOption) {
+
+        String codecExtension = outputCodec.getExtension();
+
+        if(outputCodec.isCompressionInternal()) {
+            return new StandardExtensionProvider(codecExtension);
+        }
+
+        String extension = compressionOption.getExtension()
```
Comment (asifsmohammed) [inline data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/StandardExtensionProvider.java:17]: Will the configured extension be ignored if there is a internal compression?

**Review by asifsmohammed — APPROVED** [review]

File: data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/StandardExtensionProvider.java (hunk 1 above)
Comment (dlvenable) [reply data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/StandardExtensionProvider.java:17]: Yes, it will be ignored.

With internal compression the file itself is not compressed. Different parts are independently compressed. A user should not try to run it through GZip/Snappy decompression. 

With Parquet specifically, the compression is stored as metadata inside the file. And compressed files retain the `.parquet` extension.

Comment (dlvenable) [reply data-prepper-plugins/s3-sink/src/main/java/org/opensearch/dataprepper/plugins/sink/s3/StandardExtensionProvider.java:17]: This test verifies that exact behavior: `getExtension_returns_extension_of_codec_when_compression_internal`.
