### PR TITLE
Add support for DECIMAL logical type in fixed-length byte arrays when parsing Parquet files

### LINKED ISSUE #6339: [BUG] Rds does not handle mysql decimal data types when precision value is 19 or higher
**Describe the bug**
Data Prepper RDS source does not handle MySQL DECIMAL data types with precision ≥19. When RDS exports snapshots to S3, values ≥2^63 are encoded as FIXED_LEN_BYTE_ARRAY in Parquet format (per [AWS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ExportSnapshot.data-types.html)). The NumericTypeHandler does not support this encoding, causing pipeline failures.

To Reproduce
1. Create MySQL table with DECIMAL(38,0) column containing values ≥2^63
2. Export RDS snapshot to S3
3. Configure Data Prepper pipeline with RDS source pointing to the export
4. Pipeline fails with error:
```
java.lang.IllegalArgumentException: Unsupported value type. The value is of type: class java.util.ArrayList
  at org.opensearch.dataprepper.plugins.source.rds.datatype.mysql.handler.NumericTypeHandler.handleNumericType
```

**Expected behavior**
RDS source should handle all MySQL DECIMAL types regardless of precision, converting FIXED_LEN_BYTE_ARRAY (ArrayList<Byte>) to BigInteger for values that exceed INT64 range.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**

### PR DESCRIPTION
**Pull request by divbok**
### Description
Adds proper deserialization of DECIMAL logical types stored as GenericFixed in Parquet files. Converts fixed byte arrays to BigDecimal using the schema's scale, then serializes as numeric values. Includes fallback handling for non-decimal fixed arrays as JSON byte objects.

This resolves issues where mysql decimal columns with large precision were not handled. 
 
### Issues Resolved
Resolves #6339 
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/NumericTypeHandler.java [hunk 1]
```diff
@@ -107,4 +114,29 @@ private static BigInteger bitSetToBigInteger(BitSet bitSet) {
...
     }
+
+    private Number handleByteArray(final Object value) {
+        if (value instanceof byte[]) {
+            return new BigDecimal(new BigInteger((byte[]) value));
+        }
+
+        if (value instanceof Map) {
+            Object data = ((Map<?, ?>)value).get(BYTES_KEY);
+            if (data instanceof byte[]) {
```
Comment (oeyh) [inline data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/NumericTypeHandler.java]: Is `data` always of `byte[]` type? Do we need an else block here?

Comment (divbok) [reply data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/NumericTypeHandler.java]: Did not encounter the Map use case. In my tests the values were an ArrayList type

**Comment by divbok** [comment]
> Thanks for the fix! Were you able to verify the changes with export and stream data?

Yes, I was able to verify the changes.

File: data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/NumericTypeHandlerTest.java [hunk 2]
```diff
@@ -113,7 +113,12 @@ private static Stream<Arguments> provideNumericTypeData() {
 
                 // BIT tests
                 Arguments.of(MySQLDataType.BIT, "bit_col", BitSet.valueOf(new byte[]{ 4, 3, 2, 1 }), new BigInteger("16909060")), // BitSet interprets the bytes in little-endian order
-                Arguments.of(MySQLDataType.BIT, "bit_col", Map.of("bytes", new byte[]{ 1, 2, 3, 4 }), new BigInteger("16909060")) // Direct BigInteger interprets the bytes in big-endian order.
+                Arguments.of(MySQLDataType.BIT, "bit_col", Map.of("bytes", new byte[]{ 1, 2, 3, 4 }), new BigInteger("16909060")), // Direct BigInteger interprets the bytes in big-endian order.
+
+                //DECIMAL tests represented as byte arrays
+                Arguments.of(MySQLDataType.DECIMAL, "decimal_col", new ArrayList<>(List.of(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)), new BigDecimal("1339673755198158349044581307228491536")),
```
Comment (san81) [inline data-prepper-plugins/rds-source/src/test/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/NumericTypeHandlerTest.java]: Could be worth testing negative and fractional values as well, converted to BigDecimal?

File: data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/NumericTypeHandler.java [hunk 3]
```diff
@@ -107,4 +114,29 @@ private static BigInteger bitSetToBigInteger(BitSet bitSet) {
         }
         return result;
     }
+
+    private Number handleByteArray(final Object value) {
+        if (value instanceof byte[]) {
+            return new BigDecimal(new BigInteger((byte[]) value));
```
Comment (dlvenable) [inline data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/NumericTypeHandler.java]: Each of these conditions at some point calls this: `new BigDecimal(new BigInteger(someBytes)`. Refactor this out into a method so that changes to one affect others.

File: data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/NumericTypeHandler.java (hunk 1 above)
Comment (dlvenable) [reply data-prepper-plugins/rds-source/src/main/java/org/opensearch/dataprepper/plugins/source/rds/datatype/mysql/handler/NumericTypeHandler.java]: I think we should still have the else condition to log this case if it ever happens. Otherwise you will get the exception on line 139, which would make it seem that we didn't find the right type.

**Comment by divbok** [comment]
Previous implementation failed to apply the correct decimal scale during deserialization, resulting in incorrect numeric values. The fixed length byte array when passed directly to MYSQL Numeric handler loses the scale information. This change extracts the scale from the Avro schema's Decimal logical type and applies it when converting fixed byte arrays to BigDecimal, ensuring accurate decimal representation in the output JSON when reading from the Parquet files.

File: data-prepper-plugins/parquet-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoderTest.java [hunk 4]
```diff
@@ -316,4 +316,69 @@ void serialize_WithNullDecimalLogicalType_ReturnsNull() {
...
+
+        assertEquals("{\"amount\": 12.3456}", json);
+    }
+
+    @Test
+    void serialize_WithNonDecimalFixedType_ReturnsEscapedString() {
+        byte[] tokenBytes = new byte[] { 34, 92, 13, 10, 9};
+        Schema tokenSchema = new Schema.Parser().parse(
+                "{ \"type\": \"record\", \"name\": \"MyRecord\", \"fields\": [" +
+                        "{\"name\": \"token\", \"type\": {\"type\":\"fixed\",\"name\":\"TokenFixed\",\"size\":4}}" +
```
Comment (oeyh) [inline data-prepper-plugins/parquet-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoderTest.java]: Size should be 5?

File: data-prepper-plugins/parquet-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoder.java [hunk 5]
```diff
@@ -172,7 +173,22 @@ private void serialize(final Object datum, final StringBuilder buffer,
...
             buffer.append(datum);
             buffer.append("\"");
-        } else if (datum instanceof GenericData) {
+        } else if (datum instanceof GenericFixed ) {
+            GenericFixed fixed = (GenericFixed) datum;
+            byte[] bytes = fixed.bytes();
+            if (decimalScale != null) {
+                BigInteger unscaledValue = new BigInteger(bytes);
+                BigDecimal decimal = new BigDecimal(unscaledValue, decimalScale);
+                buffer.append(decimal.doubleValue());
```
Comment (oeyh) [inline data-prepper-plugins/parquet-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoder.java]: Downstream Json parser may treat it as Double but I suggest we preserve the precision here with `decimal.toPlainString()` or `decimal.toString()`

**Review by oeyh — COMMENTED** [review]
Thanks for making the change. With this change, what's the type that MySQL NumericHandler will get for Decimals?

**Comment by divbok** [comment]
> Thanks for making the change. With this change, what's the type that MySQL NumericHandler will get for Decimals?

It will be Number

File: data-prepper-plugins/parquet-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoderTest.java (hunk 4 above)
Comment (divbok) [reply data-prepper-plugins/parquet-codecs/src/test/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoderTest.java]: Will make this change.

File: data-prepper-plugins/parquet-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoder.java (hunk 5 above)
Comment (divbok) [reply data-prepper-plugins/parquet-codecs/src/main/java/org/opensearch/dataprepper/plugins/codec/parquet/GenericRecordJsonEncoder.java]: Made the change

**Review by san81 — APPROVED** [review]
