### PR TITLE
MAINT: add default retry rule for Armeria client in End-to-end tests

### LINKED ISSUE #366: Trace analytics ingestion End-to-end tests have been flaky
**Describe the bug**
Recently I am seeing more frequent CI failure on e2e tests due to UnprocessedRequestException when Armeria client sending the requests.
```
Task :data-prepper-core:rawSpanEndToEndTest

com.amazon.dataprepper.integration.EndToEndRawSpanTest > testPipelineEndToEnd FAILED
    io.grpc.StatusRuntimeException at EndToEndRawSpanTest.java:156
        Caused by: com.linecorp.armeria.client.UnprocessedRequestException at UnprocessedRequestException.java:45
            Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException
                Caused by: java.net.ConnectException at Errors.java:155
```
**To Reproduce**
This is produced by github CI.

**Screenshots**

**Environment (please complete the following information):**
 - OS: linux
 - Version: github

**Additional context**

### PR DESCRIPTION
**Pull request by chenqi0805**
Signed-off-by: qchea <qchea@amazon.com>

### Description
This change is to mitigate the flaky UnprocessedRequestException found in end-to-end tests.
 
### Issues Resolved
#366 (mitigate)
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-core/src/integrationTest/java/com/amazon/dataprepper/integration/EndToEndRawSpanTest.java [hunk 1]
```diff
@@ -152,8 +154,10 @@ private void refreshIndices(final RestHighLevelClient restHighLevelClient) throw
     }
 
     private void sendExportTraceServiceRequestToSource(final int port, final ExportTraceServiceRequest request) {
-        Clients.newClient(String.format("gproto+http://127.0.0.1:%d/", port),
-                TraceServiceGrpc.TraceServiceBlockingStub.class).export(request);
+        TraceServiceGrpc.TraceServiceBlockingStub client = Clients.builder(String.format("gproto+http://127.0.0.1:%d/", port))
+                .decorator(RetryingClient.newDecorator(RetryRule.failsafe()))
```
Comment (dlvenable) [inline data-prepper-core/src/integrationTest/java/com/amazon/dataprepper/integration/EndToEndRawSpanTest.java:158]: I like this change overall!

The documentation on this wasn't clear regarding how many times it tries. Is this limited?
If we are unsure as to the number of retries, we should be sure that the test itself has a [JUnit @Timeout](https://junit.org/junit5/docs/5.5.1/api/org/junit/jupiter/api/Timeout.html).

Comment (chenqi0805) [reply data-prepper-core/src/integrationTest/java/com/amazon/dataprepper/integration/EndToEndRawSpanTest.java:158]: Yes. Here is the specification: https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.11.0/com/linecorp/armeria/common/Flags.html#defaultBackoffSpec()
