### PR TITLE
Fix Data Prepper to not terminate on invalid open telemetry metric/trace data

### LINKED ISSUE #2089: [BUG] Invalid Opentelemetry Data can cause ingestion to be stopped
Using DataPrepper to ingest metrics into OpenSearch it is possible to crash the metrics ingestion with invalid data. If data points without a value are sent, the null check in the OtelMetricsRawProcessor throws a NullPointerException. This crashes the current ingestion thread. Once all threads crash, no more data ingestion is possible. DataPrepper does not restart failed threads nor does it crash itself. Additional monitoring of the buffers or logs is required to detect this disfunctional state. Restarting DataPrepper resolves the issue until the next invalid data point is ingested. During restarts all data in the buffers is lost.

**To Reproduce**
We encountered the issue using the OpenTelemetry Collector to scrape Istio metrics from its Prometheus endpoint. Since the issue only happens occasionally and could not be forced, we provide an alternative approach, that generates the invalid metrics directly. Nevertheless, keep in mind, that the issue happened in a productive setup.

1. Run DataPrepper with a default metrics pipeline, e.g.:
```
    metrics-pipeline:
      source:
        otel_metrics_source:
          ssl: false
      processor:
        - otel_metrics_raw_processor:
```
2. Store the following OTEL metric as JSON in a file `metric.json`. Note, that there is no "value" field in the data point.
```
{
    "resourceMetrics": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "service.name",
                        "value": {
                            "stringValue": "basic-metric-service"
                        }
                    }
                ],
                "droppedAttributesCount": 0
            },
            "scopeMetrics": [
                {
                    "metrics": [
                        {
                            "description": "Example of a Counter",
                            "name": "requests",
                            "gauge": {
                                "dataPoints": [
                                    {
                                        "attributes": [],
                                        "startTimeUnixNano": 1660736598000000000,
                                        "timeUnixNano": 1660736598000001000
                                    }
                                ]
                            },
                            "unit": "1"
                        }
                    ],
                    "scope": {
                        "name": "example-exporter-collector",
                        "version": ""
                    }
                }
            ]
        }
    ]
}
```
3. Prepare a otel-collector docker image, e.g. `docker pull otel/opentelemetry-collector:0.67.0` and point it to the DataPrepper instance using the following configuration:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "*"

processors:
  batch:
    send_batch_size: 50
    timeout: 1s

exporters:
  logging:
    logLevel: debug
  otlp/metrics:
    endpoint: "<DataPrepper Endpoint>"
    tls:
      insecure_skip_verify: true
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/metrics]
```
4. Run the Docker image with:
```
docker run -v "${PWD}/otelcol-config-sample.yaml":/otelcol-config-sample.yaml -p 4318:4318 otel/opentelemetry-collector:0.67.0 --config otelcol-config-sample.yaml
```
5. Send the invalid metric to the otel-collector:
```
curl -X POST -H "Content-Type: application/json" -d @metric-request-gauge.json http://localhost:4318/v1/metrics
``` 

The OpenTelemetry Collector should send the invalid metric to DataPrepper causing the NPE (stacktrace from DataPrepper 1.5):
```
2022-11-23T16:23:08,402 [metrics-pipeline-processor-worker-7-thread-1] ERROR com.amazon.dataprepper.pipeline.ProcessWorker - Encountered exception during pipeline metrics-pipeline processing
java.lang.NullPointerException: value cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.model.metric.ParameterValidator.lambda$validate$2(ParameterValidator.java:33) ~[data-prepper.jar:1.5.0]
	at java.util.Collections$SingletonList.forEach(Collections.java:4933) ~[?:?]
	at com.amazon.dataprepper.model.metric.ParameterValidator.validate(ParameterValidator.java:31) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.model.metric.JacksonGauge$Builder.build(JacksonGauge.java:80) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.plugins.processor.otelmetrics.OTelMetricsRawProcessor.lambda$mapGauge$0(OTelMetricsRawProcessor.java:89) ~[data-prepper.jar:1.5.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.amazon.dataprepper.plugins.processor.otelmetrics.OTelMetricsRawProcessor.mapGauge(OTelMetricsRawProcessor.java:91) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.plugins.processor.otelmetrics.OTelMetricsRawProcessor.doExecute(OTelMetricsRawProcessor.java:54) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.model.processor.AbstractProcessor.lambda$execute$0(AbstractProcessor.java:55) ~[data-prepper.jar:1.5.0]
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:65) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.model.processor.AbstractProcessor.execute(AbstractProcessor.java:55) ~[data-prepper.jar:1.5.0]
	at com.amazon.dataprepper.pipeline.ProcessWorker.run(ProcessWorker.java:62) ~[data-prepper.jar:1.5.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
```

**Expected behavior**
DataPrepper should not lose a worker thread to faulty input data. The metric should be dropped increasing an appropriate counter in the metrics. Optionally a log entry can be issued at DEBUG or INFO level.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]
 - DataPrepper versions 1.5 and 2.0 were tested. Both with local binaries and the provided Docker images.

**Additional context**
The issue is cause by declaring the value field as "REQUIRED_NON_NULL_VALUES" in the JacksonGauge: https://github.com/opensearch-project/data-prepper/blob/01228357aa9f5c6f8099887b3c90d15e892c769c/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonGauge.java#L25-L29.
Since the validation exceptions are not called and handled, the worker thread crashes. It would be nice, if a different behaviour on validation errors would be implemented as indicated in expected behaviour.

### PR DESCRIPTION
**Pull request by kkondaka**
Signed-off-by: Krishna Kondaka <krishkdk@amazon.com>

### Description
Fix Data Prepper to not terminate on invalid open telemetry metric data. When invalid data is received by metric or trace data source, the metric/trace is ignored and bad request counter is incremented.
 
### Issues Resolved
Resolves #2089 
 
### Check List
- [X ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceGrpcService.java [hunk 1]
```diff
@@ -96,7 +96,7 @@ private void processRequest(
         } catch (Exception e) {
             LOG.error("Failed to parse the request due to:", request, e);
             badRequestsCounter.increment();
-            responseObserver.onError(Status.INVALID_ARGUMENT.withDescription(e.getMessage()).asException());
+            responseObserver.onCompleted();
```
Comment (dlvenable) [inline data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceGrpcService.java:99]: This doesn't seem quite right to me. We are recording bad messages as successful. It seems there is a deeper issue here where the threads are being lost on errors. That is probably what we need to find an answer on.

Comment (kkondaka) [reply data-prepper-plugins/otel-trace-source/src/main/java/org/opensearch/dataprepper/plugins/source/oteltrace/OTelTraceGrpcService.java:99]: As per - https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html - "completed" only means, the stream is successfully completed, which is true because we have completed processing. Since we are not doing "onNext", I don't think it is a successful request. That's how I understood the API. What do you mean by "where the threads are being lost"?

File: data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OTelMetricsRawProcessor.java [hunk 2]
```diff
@@ -36,34 +37,41 @@
...
-                for (ScopeMetrics sm : rs.getScopeMetricsList()) {
-                    final Map<String, Object> ils = OTelProtoCodec.getInstrumentationScopeAttributes(sm.getScope());
-                    recordsOut.addAll(processMetricsList(sm.getMetricsList(), serviceName, ils, resourceAttributes, schemaUrl));
+                    for (ScopeMetrics sm : rs.getScopeMetricsList()) {
+                        final Map<String, Object> ils = OTelProtoCodec.getInstrumentationScopeAttributes(sm.getScope());
+                        recordsOut.addAll(processMetricsList(sm.getMetricsList(), serviceName, ils, resourceAttributes, schemaUrl));
+                    }
                 }
-
+            } catch (Exception e) {
```
Comment (dlvenable) [inline data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OTelMetricsRawProcessor.java:73]: I tend to think we should put this exception handling inside the loop in `processMetricsList`.

Say we get a metrics export request with 50 metrics and only one is invalid. The current try-catch will fail them all. I think we can probably isolate these exceptions to the individual metrics and thus allow the metrics which have the correct pre-condition to process correctly.

```
      for (io.opentelemetry.proto.metrics.v1.Metric metric : metricsList) {
        try {
            if (metric.hasGauge()) {
                recordsOut.addAll(mapGauge(metric, serviceName, ils, resourceAttributes, schemaUrl));
            } else if (metric.hasSum()) {
                recordsOut.addAll(mapSum(metric, serviceName, ils, resourceAttributes, schemaUrl));
            } else if (metric.hasSummary()) {
                recordsOut.addAll(mapSummary(metric, serviceName, ils, resourceAttributes, schemaUrl));
            } else if (metric.hasHistogram()) {
                recordsOut.addAll(mapHistogram(metric, serviceName, ils, resourceAttributes, schemaUrl));
            } else if (metric.hasExponentialHistogram()) {
                recordsOut.addAll(mapExponentialHistogram(metric, serviceName, ils, resourceAttributes, schemaUrl));
            }
        } catch(Exception ex) {
        ...
        }
      }

```

**Review by dlvenable — CHANGES_REQUESTED** [review]
I made a suggestion for the OTel Metrics raw processor change.

The issues underlying these two bugs are quite distinct. We can probably fix the Metrics processor in this PR and do a deeper dive on the Trace issue.

File: data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OTelMetricsRawProcessor.java [hunk 3]
```diff
@@ -36,34 +37,41 @@
...
+                recordsDroppedMetricsRawCounter.increment();
```
Comment (dlvenable) [inline data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OTelMetricsRawProcessor.java:74]: We should probably log the exception as well.

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OTelMetricsRawProcessor.java (hunk 2 above)
Comment (kkondaka) [reply data-prepper-plugins/otel-metrics-raw-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/OTelMetricsRawProcessor.java:73]: Makes sense. I thought each record in doExecute() corresponds to one metric but it looks like it can result in multiple metrics. I will move the try-catch to `processMetricsList`

File: data-prepper-plugins/otel-metrics-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/MetricsPluginSumTest.java [hunk 4]
```diff
@@ -109,6 +110,63 @@ public void test() throws JsonProcessingException {
         assertSumProcessing(map);
     }
 
+    @Test
+    public void missingNameInvalidMetricTest() throws JsonProcessingException {
```
Comment (dlvenable) [inline data-prepper-plugins/otel-metrics-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/MetricsPluginSumTest.java:114]: It could be good to include a single valid metric to ensure that it processes that as well. I'll approve this as is, but feel free to consider a follow-on PR!

**Review by dlvenable — APPROVED** [review]

**Review by graytaylor0 — APPROVED** [review]

File: data-prepper-plugins/otel-metrics-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/MetricsPluginSumTest.java (hunk 4 above)
Comment (kkondaka) [reply data-prepper-plugins/otel-metrics-raw-processor/src/test/java/org/opensearch/dataprepper/plugins/processor/otelmetrics/MetricsPluginSumTest.java:114]: Pushed a new diff with this change.

**Review by dlvenable — APPROVED** [review]
