### PR TITLE
Tag events that fail for all exceptions in the grok processor. Resolves #4031

### LINKED ISSUE #4031: [BUG] Many Grok failures do not tag events
**Describe the bug**

There are several exceptions which the `grok` processor catches that do not tag the event.

**To Reproduce**

Run a pipeline with a grok pattern than times out. The event is not tagged.

**Expected behavior**

I expect that any failure to match will result in a tag.

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

This PR tags events for all exceptions in the grok processor. This includes timeout exceptions and other runtime exceptions that the processor catches as it will still send those events further through the pipeline.

I also consolidated the exception handling. The error messages for exceptions other than timeouts do not seem to need different wording as they all will include the actual exception. Also, an "unknown exception" might seem confusing to a user, especially since it is handled the same as the "known" exceptions.
 
### Issues Resolved

Resolves #4031
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java [hunk 1]
```diff
@@ -131,18 +131,13 @@ public Collection<Record<Event>> doExecute(final Collection<Record<Event>> recor
...
                 grokProcessingTimeoutsCounter.increment();
-            } catch (ExecutionException e) {
-                LOG.error(EVENT, "An exception occurred while matching on record [{}]", record.getData(), e);
-                grokProcessingErrorsCounter.increment();
-            } catch (InterruptedException e) {
-                LOG.error(EVENT, "Matching on record [{}] was interrupted", record.getData(), e);
-                grokProcessingErrorsCounter.increment();
-            } catch (RuntimeException e) {
+            } catch (final ExecutionException | InterruptedException | RuntimeException e) {
                 event.getMetadata().addTags(tagsOnMatchFailure);
```
Comment (graytaylor0) [inline data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java:139]: Should we add a default tag of `grok_match_failure` here and `grok_timeout` for a timeout? The default behavior of tagging is not different here between a match failure and a timeout. 

Alternative option is to add a separate `tags_on_timeout` as alternative to `tags_on_failure` (even though timeout is a failure too, so I would be find with just giving clear indication of which failure was hit

Comment (dlvenable) [reply data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java:139]: Are you suggesting that we make this a different configuration for users?

```
grok:
  tags_on_match_failure: [it_failed]
  tags_on_timeout: [it_timed_out]
```

What about the unknown types of exceptions? Would we have another option for those?

Comment (graytaylor0) [reply data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java:139]: I don't think we have to group them like that, but yes I think that would be clear. I just think we need a way to differentiate between a timeout and a match failure. It may make sense to also differentiate the unknown exceptions from the true grok_match_failure tags.

Comment (dlvenable) [reply data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java:140]: @graytaylor0 , I added `tags_on_timeout` based on this feedback in my latest commit.

**Review by graytaylor0 — DISMISSED** [review]

File: data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java (hunk 1 above)
Comment (dlvenable) [reply data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java:140]: @kkondaka ,

> I am thinking we should add tags_on_match_failure in all cases except timeout case.

Are you suggesting that we change the default behavior? I'm a bit uncertain of doing that as it will affect existing pipelines in a way that users may not expect.

> And in case of timeout, if tags_on_timeout is not configured, tags_on_match_failure should be added

I'm onboard with this change and will make it.

Comment (dlvenable) [reply data-prepper-plugins/grok-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/grok/GrokProcessor.java:140]: @kkondaka , I changed the code such that `tags_on_match_failure` takes over when `tags_on_timeout` is empty.

**Review by kkondaka — APPROVED** [review]

**Review by graytaylor0 — APPROVED** [review]
