### PR TITLE
Release events that are not routed to any sinks

### LINKED ISSUE #3866: [BUG] Incomplete route set leads to duplicates when E2E ack is enabled.
**Describe the bug**
This is not technically a bug, but is easy to miss and leads to unexpected behavior. If a user has acknowledgements enabled for their source and routes enabled, but the routes do not cover all possibilities of the incoming data, a portion of the data will never end up in a sink or DLQ. This prevents the ack from being acknowledged and the sink permanently loops on a set of incoming data.

Example:
* S3-SQS source pipeline with acks enabled
* A single route is defined where `'/myfield == "my value"'`

If one of the S3 objects contains `/myfield` with a value of `not my value`, then it is not routed to a sink so the acknowledgement set cannot complete successfully. The ack timeout expires and the object re-enters the queue to be processed again.

**To Reproduce**
Steps to reproduce the behavior: Documented above

**Expected behavior**
There are a few ways this could be handled, I am not sure which is correct.

1. Any records not matching a route end up in a DLQ
2. Acknowledgements consider records with no route being dropped as intentional and still send a positive ack in this case
3. Validation prevents a pipeline from being created if acks are enabled and the routes form an incomplete set of all possibilities

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
Release events that are not routed to any sinks.
When an event is not routed any sink, acknowledgement is sent so that the events are dropped.

Resolves #3866 
### Issues Resolved
Resolves #3866 
### Check List
- [ X] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/Router.java [hunk 1]
```diff
@@ -6,24 +6,28 @@
...
 /**
  * Provides routing of event records over a collection of {@link DataFlowComponent} objects.
  */
 public class Router {
     private final RouteEventEvaluator routeEventEvaluator;
     private final DataFlowComponentRouter dataFlowComponentRouter;
+    private final Consumer<Event> unroutedEventHandler;
 
-    Router(final RouteEventEvaluator routeEventEvaluator, final DataFlowComponentRouter dataFlowComponentRouter) {
+    Router(final RouteEventEvaluator routeEventEvaluator, final DataFlowComponentRouter dataFlowComponentRouter, final Consumer<Event> handler) {
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/Router.java:27]: Maybe rename `handler` to `noRoutedHandler` to clarify how it is different.

**Review by chenqi0805 — APPROVED** [review]

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterTest.java [hunk 2]
```diff
@@ -143,6 +147,40 @@ void route_with_multiple_DataFlowComponents() {
         }
     }
 
+    @Nested
+    class WithUnroutedRecords {
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterTest.java:151]: It would also be good to have a test case where the records are not `Event` objects. In such a case, we should not call the `Consumer` with those records.

**Review by graytaylor0 — DISMISSED** [review]
Looks good to me. You ran data prepper with multiple routes and `acknowledgments` enabled and verified unrouted Events were acked?

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterFactory.java [hunk 3]
```diff
@@ -22,6 +22,6 @@ public class RouterFactory {
 
     public Router createRouter(final Set<ConditionalRoute> routes) {
         final RouteEventEvaluator routeEventEvaluator = new RouteEventEvaluator(expressionEvaluator, routes);
-        return new Router(routeEventEvaluator, dataFlowComponentRouter);
+        return new Router(routeEventEvaluator, dataFlowComponentRouter, event -> event.getEventHandle().release(true));
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterFactory.java:25]: Let's add a test case for this in `RouterFactoryTest`.

You can do this with some mocking:

1. Mock the constructor for `Router`.
2. Call `createRouter`.
3. Extract the `Consumer` provided as an argument to the constructor.
4. Call the real consumer with a mocked `Event` and verify the expected calls.

**Review by dlvenable — CHANGES_REQUESTED** [review]
Overall this looks good. I have a few comments.

It would also be good to add some integration test cases for this. We have a router test `Router_ThreeRoutesIT` that doesn't use acknowledgements. Maybe we can add a new `RouterWithAcks_ThreeRoutesIT`. But, that could come as a follow-on PR.

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterTest.java [hunk 4]
```diff
@@ -62,7 +66,9 @@ void setUp() {
     }
 
     private Router createObjectUnderTest() {
-        return new Router(routeEventEvaluator, dataFlowComponentRouter, event -> event.getEventHandle().release(true));
+        //noRouteHandler = event -> event.getEventHandle().release(true);
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterTest.java:69]: Please remove this commented code.

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterFactory.java [hunk 5]
```diff
@@ -22,6 +22,15 @@ public class RouterFactory {
...
     public Router createRouter(final Set<ConditionalRoute> routes) {
         final RouteEventEvaluator routeEventEvaluator = new RouteEventEvaluator(expressionEvaluator, routes);
-        return new Router(routeEventEvaluator, dataFlowComponentRouter, event -> event.getEventHandle().release(true));
+        return new Router(routeEventEvaluator, dataFlowComponentRouter,
+                event -> {
+                    // Release unrouted events ONLY if routes are defined.
+                    // If routes are not used in the config, then all
+                    // events will have zero size for the routes set and
+                    // we shouldn't be releasing such events here
+                    if (routes.size() > 0) {
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterFactory.java:31]: Thanks for adding the unit test. Let's also add one to verify that `release()` is not called when `routes.size() == 0`.

File: data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java [hunk 6]
```diff
@@ -130,7 +131,7 @@ void three_pipelines_with_route_and_multiple_records() {
                 .untilAsserted(() -> {
             List<Record<Event>> outputRecords = inMemorySinkAccessor.get(IN_MEMORY_IDENTIFIER);
             assertThat(outputRecords, not(empty()));
-            assertThat(outputRecords.size(), equalTo(numRecords));
+            assertThat(outputRecords.size(), lessThanOrEqualTo(numRecords));
```
Comment (dlvenable) [inline data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java:134]: I'm curious about why you made this change? Is this too lenient?

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java (hunk 6 above)
Comment (kkondaka) [reply data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/integration/PipelinesWithAcksIT.java:134]: No. Some records will not be sent to sink. But I will create a new test for it and keep the existing test untouched.

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterFactory.java (hunk 5 above)
Comment (kkondaka) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterFactory.java:31]: This comment is not applicable  anymore because we have changed the code.

Comment (dlvenable) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/router/RouterFactory.java:31]: I think we can drop this condition now. So this can be:

```
event -> event.getEventHandle().release(true)
```

Right?

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterTest.java [hunk 7]
```diff
@@ -138,11 +153,85 @@ void route_with_multiple_DataFlowComponents() {
...
+            recordsToRoutes.put(record1, Set.of(UUID.randomUUID().toString()));
+            recordsToRoutes.put(record2, Set.of(UUID.randomUUID().toString()));
+            recordsToRoutes.put(record3, Set.of());
+            recordsToRoutes.put(record4, Set.of());
+            when(routeEventEvaluator.evaluateEventRoutes(recordsIn)).thenReturn(recordsToRoutes);
+            dataFlowComponents = new ArrayList<>();
+            for (int i = 0; i < 5; i++) {
+                final DataFlowComponent dataFlowComponent = mock(DataFlowComponent.class);
+                dataFlowComponents.add(dataFlowComponent);
+                if (i == 0) {
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/router/RouterTest.java:221]: It might be cleaner to move the mocking out of the condition and only have the set in the condition.


```
final Set<String> routes;
if(i == 0) {
  routes = Collections.emptySet();
}
else {
  routes = Set.of("aa");
}
when(dataFlowComponent.getRoutes()).thenReturn(routes);
```

or

```
final Set<String> routes = i ==0 ? Collections.emptySet() : Set.of("aa");
when(dataFlowComponent.getRoutes()).thenReturn(routes);
```

**Review by dlvenable — CHANGES_REQUESTED** [review]
Thank you for iterating on this solution. I think it is looking good. I have a couple small comments.

**Review by graytaylor0 — APPROVED** [review]
