### PR TITLE
OpenSearch Sink: Add log messages when there is no exception

### LINKED ISSUE #3508: [BUG] No permissions for writing to OpenSearch serverless collection only shows errors after max_retries limit is reached
**Describe the bug**
No permissions when writing to serverless collections results in infinite retry (or up to max_retries) before an exception message is shown to the user. This can lead to never seeing the permission issue. This may occur for more than just serverless collections but I have only personally hit the issue with serverless

**To Reproduce**
1. Create a serverless collection 
2. Configure an OpenSearch sink with this serverless collection, with an `sts_role_arn` that does not have permissions on the data access policy

**Expected behavior**
Log permission exceptions immediately when they occur, instead of after the max_retries limit is reached. The easiest solution would be for us to log on top of `Bulk Operation Failed. Number of retries {}. Retrying...` with one of the actual bulkResponse exceptions

**Additional context**

### PR DESCRIPTION
**Pull request by kkondaka**
### Description
OpenSearch Sink: Add log messages when there is no exception.
OpenSearch Sink BulkOperation failure logs messages only if there is an exception. It is possible that it fails without exception, it is good to log the error reasons for each operation in those cases as well.
 
Resolves #3508 
### Issues Resolved
Resolves #3508 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by graytaylor0 — COMMENTED** [review]
Implementation looks good. Should add some unit tests

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java [hunk 1]
```diff
@@ -238,6 +238,13 @@ private BulkOperationRequestResponse handleRetriesAndFailures(final Accumulating
         if (doRetry) {
             if (retryCount % 5 == 0) {
                 LOG.warn("Bulk Operation Failed. Number of retries {}. Retrying... ", retryCount, e);
+                if (Objects.isNull(e)) {
+                    for (final BulkResponseItem bulkItemResponse : bulkResponse.items()) {
+                        if (Objects.nonNull(bulkItemResponse.error())) {
```
[the remark this answers is not in the document]
Comment (kkondaka) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java:243]: Do you mean to say "it will be NULL for successful records"?
Don't know how to test this path easily. But based on the following existing code, I think it will be set to null for successful records.

```
if (bulkItemResponse.error() == null) {
                    sentDocumentsOnFirstAttemptCounter.increment();
 }
```

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java [hunk 2]
```diff
@@ -248,7 +255,13 @@ private BulkOperationRequestResponse handleRetriesAndFailures(final Accumulating
...
+        LOG.warn("Bulk Operation Failed.", failure);
         if (Objects.isNull(failure)) {
+            for (final BulkResponseItem bulkItemResponse : bulkResponse.items()) {
+                if (Objects.nonNull(bulkItemResponse.error())) {
+                    LOG.warn("operation = {}, error = {}", bulkItemResponse.operationType(), bulkItemResponse.error());
+                }
+            }
             handleFailures(bulkRequest, bulkResponse.items());
         } else {
             handleFailures(bulkRequest, failure);
```
[the remark this answers is not in the document]
Comment (kkondaka) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java:267]: The new change, prints "failure" in both cases. If it is non-null, it will be printed. If it is non-null, I think it would be useful.

**Review by graytaylor0 — APPROVED** [review]

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java [hunk 3]
```diff
@@ -238,6 +238,13 @@ private BulkOperationRequestResponse handleRetriesAndFailures(final Accumulating
         if (doRetry) {
             if (retryCount % 5 == 0) {
                 LOG.warn("Bulk Operation Failed. Number of retries {}. Retrying... ", retryCount, e);
+                if (Objects.isNull(e)) {
```
Comment (dlvenable) [inline data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java:241]: The reason `isNull` exists is to help with streams. I think outside of a stream, we should use `x == null`.

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java [hunk 4]
```diff
@@ -248,7 +255,13 @@ private BulkOperationRequestResponse handleRetriesAndFailures(final Accumulating
     }
 
     private void handleFailures(final AccumulatingBulkRequest<BulkOperationWrapper, BulkRequest> bulkRequest, final BulkResponse bulkResponse, final Throwable failure) {
+        LOG.warn("Bulk Operation Failed.", failure);
         if (Objects.isNull(failure)) {
+            for (final BulkResponseItem bulkItemResponse : bulkResponse.items()) {
+                if (Objects.nonNull(bulkItemResponse.error())) {
```
Comment (dlvenable) [inline data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java:261]: Again, let's use `bulkItemResponse.error() == null`.

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java [hunk 5]
```diff
@@ -248,7 +255,13 @@ private BulkOperationRequestResponse handleRetriesAndFailures(final Accumulating
     }
 
     private void handleFailures(final AccumulatingBulkRequest<BulkOperationWrapper, BulkRequest> bulkRequest, final BulkResponse bulkResponse, final Throwable failure) {
+        LOG.warn("Bulk Operation Failed.", failure);
```
Comment (dlvenable) [inline data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java:258]: Do we want the full stack trace here? We know where the exception is thrown from right?

Or should this be the following?

```
 LOG.warn("Bulk Operation Failed. {}", failure.getMessage());
```

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java (hunk 5 above)
Comment (kkondaka) [reply data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/BulkRetryStrategy.java:258]: This function may be called from multiple paths, right?

**Review by graytaylor0 — APPROVED** [review]

**Review by dlvenable — APPROVED** [review]
