### PR TITLE
Catch processor exceptions instead of shutting down

### LINKED ISSUE #4103: [BUG] Data Prepper process threads stop when processors throw exceptions
**Describe the bug**

When a processor throws an exception, the current Data Prepper processor thread stops processing. Data Prepper is not shutting down the pipeline, nor is it attempting to restart the thread.

**To Reproduce**

Create a pipeline with a processor that will throw an exception. The `date` processor throws an exception when the `date_when` value has in valid expression.

Run Data Prepper and send data through.

The threads stop.

**Expected behavior**

There are two things I'd expect:

* The whole pipeline shuts down
* Data Prepper attempts to restart the thread

**Analysis**

The exact cause is this line:

https://github.com/opensearch-project/data-prepper/blob/2be8166ac8ac1f80784201f2a6e33302145cb5a8/data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java#L91-L93

The `ProcessWorker` catches the exception. Then the `ProcessWorker::run` method exits. After this, the thread remains, but it is waiting on a task to run. 

You can see that the thread remains with a thread dump:

```
"my-pipeline-pipeline-processor-worker-1-thread-1" #41 prio=5 os_prio=0 cpu=2889321.30ms elapsed=70643.67s tid=0x0000aaaadebd3310 nid=0xa8 waiting on condition  [0x0000ffff08bdf000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.22/Native Method)
	- parking to wait for  <0x00000005e1d1c890> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.22/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.22/AbstractQueuedSynchronizer.java:2081)
	at java.util.concurrent.LinkedBlockingQueue.take(java.base@11.0.22/LinkedBlockingQueue.java:433)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.22/ThreadPoolExecutor.java:1054)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.22/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.22/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.22/Thread.java:829)
```

**Environment (please complete the following information):**

Data Prepper 2.6.1

### PR DESCRIPTION
**Pull request by graytaylor0**
### Description
This change makes it so exceptions thrown from `Processors` in `ProcessWorker` to not shut down the thread.

Instead of shutting down, we will just pass the batch of Events that resulted in the exception to the next processor in the chain
 
### Issues Resolved
Resolves #4103 
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java [hunk 1]
```diff
@@ -126,13 +125,17 @@ private void doRun() {
...
+            try {
+                List<Event> inputEvents = null;
+                if (acknowledgementsEnabled) {
+                    inputEvents = ((ArrayList<Record<Event>>) records).stream().map(Record::getData).collect(Collectors.toList());
+                }
+                records = processor.execute(records);
+                if (inputEvents != null) {
+                    processAcknowledgements(inputEvents, records);
+                }
+            } catch (final Exception e) {
```
[the remark this answers is not in the document]
Comment (graytaylor0) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java:137]: Yes we could make it configurable to send these records to a pipeline DLQ. However, I am not sure if dropping the data is the best behavior here. As a user, I would rather get my data and not have it be as I expected rather than silently dropping data. Then, if it does not appear correctly in the sink, these error logs will help guide what the issue is. I tend to think that downstream processors should be robust enough to at least not crash when they do not get what they expect, even if it means they are tagged with certain values indicating failure to perform an action on the Event in the downstream processor

[the remark this answers is not in the document]
Comment (dlvenable) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java:137]: I think for most processors, this is probably the case. Which is why I support adding the try-catch blocks in those processors.

However, some processors will not want this behavior. One example is the service map. If an exception leaks from there we'd be sending trace events to the service map index. Other examples are pipelines that generate metrics from logs and alerting on anomalies.

But, if we make this change in core, we force all events to flow through all processors this way.

I think the ideal solution has:
1. Appropriate try-catch in the processors where it is ok to do this.
2. Dropping events from exceptions in core

[the remark this answers is not in the document]
Comment (graytaylor0) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java:137]: That is a fair point I did not consider stateful processors. I am ok with changing to drop the batch instead of passing them downstream

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/ProcessWorkerTest.java [hunk 2]
```diff
@@ -147,6 +149,45 @@ void testProcessWorkerWithProcessorThrowingExceptionIsCaughtProperly() {
...
+
+        records.add(mockRecord);
+
+        final CheckpointState checkpointState = mock(CheckpointState.class);
+        final Map.Entry<Collection, CheckpointState> readResult = Map.entry(records, checkpointState);
+        when(buffer.read(pipeline.getReadBatchTimeoutInMillis())).thenReturn(readResult);
+
+        final Processor processor = mock(Processor.class);
+        when(processor.execute(records)).thenThrow(RuntimeException.class);
+        when(processor.isReadyForShutdown()).thenReturn(true);
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/ProcessWorkerTest.java:184]: Why did you mock this method?

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/ProcessWorkerTest.java [hunk 3]
```diff
@@ -147,6 +149,45 @@ void testProcessWorkerWithProcessorThrowingExceptionIsCaughtProperly() {
...
+        processors = List.of(processor);
```
Comment (dlvenable) [inline data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/ProcessWorkerTest.java:185]: It is probably best to include multiple processors and then verify that any after the failing processor are not called.

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java [hunk 4]
```diff
@@ -125,17 +126,25 @@ private void doRun() {
...
-                if (acknowledgementsEnabled) {
-                    inputEvents = ((ArrayList<Record<Event>>) records).stream().map(Record::getData).collect(Collectors.toList());
-                }
                 records = processor.execute(records);
                 if (inputEvents != null) {
                     processAcknowledgements(inputEvents, records);
                 }
             } catch (final Exception e) {
-                LOG.error("A processor threw an exception. This processor will be skipped for the remaining Events in this batch: ", e);
+                LOG.error("A processor threw an exception. This batch of Events will be dropped, and there EventHandles will be released: ", e);
```
Comment (dlvenable) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/pipeline/ProcessWorker.java:141]: Minor typo: "there" -> "their"

**Review by dlvenable — CHANGES_REQUESTED** [review]

File: data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/ProcessWorkerTest.java (hunk 2 above)
Comment (graytaylor0) [reply data-prepper-core/src/test/java/org/opensearch/dataprepper/pipeline/ProcessWorkerTest.java:191]: It is required to return true so that the process worker will shut down without infinitely retrying

**Review by dlvenable — APPROVED** [review]
Nice, thanks!

**Review by kkondaka — DISMISSED** [review]

**Review by dlvenable — APPROVED** [review]

**Review by kkondaka — APPROVED** [review]
