### PR TITLE
Fixes a regression in core where @SingleThread annotated processors are only running the last instance.

### LINKED ISSUE #5901: [BUG] Service Map does not rotate with multiple workers
**Describe the bug**

The `service_map` is no longer rotating its windows.

The cause of this issue is that with the introduction of #5794, the `@SingleThread` annotation is not functioning as expected. Only the last `@SingleThread` processor instances is called by all threads after this commit.

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

This reworks the recent code for the `ProcessorProvider` to create a provider per processor thread. 

With this fix, the processor swaps will not work correctly, but this is not complete anyway.

**New integration test**

This includes an integration test which fails on `main`.

The test exactly shows what I expected to see, which is that the last processor instance is used by all threads.

```
Expected: <1>
     but: was <0>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
		at org.opensearch.dataprepper.integration.ProcessorValidationIT.lambda$verifySingleThreadUsage$4(ProcessorValidationIT.java:217)
		at org.junit.jupiter.api.AssertAll.lambda$assertAll$0(AssertAll.java:68)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
		... 133 more
	Suppressed: java.lang.AssertionError: 
Expected: <1>
     but: was <0>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
		at org.opensearch.dataprepper.integration.ProcessorValidationIT.lambda$verifySingleThreadUsage$5(ProcessorValidationIT.java:218)
		at org.junit.jupiter.api.AssertAll.lambda$assertAll$0(AssertAll.java:68)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
		... 133 more
	Suppressed: java.lang.AssertionError: 
Expected: <1>
     but: was <0>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
		at org.opensearch.dataprepper.integration.ProcessorValidationIT.lambda$verifySingleThreadUsage$6(ProcessorValidationIT.java:219)
		at org.junit.jupiter.api.AssertAll.lambda$assertAll$0(AssertAll.java:68)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
		... 133 more
	Suppressed: java.lang.AssertionError: 
Expected: <1>
     but: was <4>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
		at org.opensearch.dataprepper.integration.ProcessorValidationIT.lambda$verifySingleThreadUsage$7(ProcessorValidationIT.java:220)
		at org.junit.jupiter.api.AssertAll.lambda$assertAll$0(AssertAll.java:68)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
		at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
		... 133 more
```
 
### Issues Resolved

Resolves #5901
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/BasicEventsTrackingTestProcessor.java [hunk 1]
```diff
@@ -20,6 +20,6 @@ public class BasicEventsTrackingTestProcessor extends BaseEventsTrackingProcesso
     private static final String PLUGIN_NAME = "basic_events_tracking_test";
 
     public BasicEventsTrackingTestProcessor() {
-        super(PLUGIN_NAME, PROCESSED_EVENTS_MAP);
+        super(PLUGIN_NAME, PROCESSED_EVENTS_MAP, -1);
```
Comment (kkondaka) [inline data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/BasicEventsTrackingTestProcessor.java]: Why  -1?

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/Pipeline.java [hunk 2]
```diff
@@ -236,8 +236,11 @@ private synchronized void startSourceAndProcessors() {
                         }
                     }
             ).collect(Collectors.toList());
+            final ProcessorRegistry processorRegistry = new ProcessorRegistry(processors);
```
Comment (kkondaka) [inline data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/Pipeline.java]: Why same name as the class member?

File: data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/BasicEventsTrackingTestProcessor.java (hunk 1 above)
Comment (dlvenable) [reply data-prepper-core/src/integrationTest/java/org/opensearch/dataprepper/plugins/BasicEventsTrackingTestProcessor.java]: We don't track it for this processor. I made this a static final with a name to add clarity.

File: data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/Pipeline.java (hunk 2 above)
Comment (dlvenable) [reply data-prepper-core/src/main/java/org/opensearch/dataprepper/core/pipeline/Pipeline.java]: Good call. I renamed this as well as some other fields to try to add clarity.

**Review by graytaylor0 — DISMISSED** [review]

**Review by kkondaka — APPROVED** [review]
