### PR TITLE
Fix AWS Sdk dependency conflict

### LINKED ISSUE #5084: [BUG] Kinesis source is failing on startup
**Describe the bug**

A pipeline with a `kinesis` source fails on start up

```
2024-10-17T19:57:33,161 [kinesis-pipeline-local-sink-worker-2-thread-1] ERROR org.opensearch.dataprepper.plugins.kinesis.source.KinesisService - Caught exception when initializing KCL Scheduler. Will retry
2024-10-17T19:57:35,108 [kinesis-pipeline-local-sink-worker-2-thread-1] ERROR org.opensearch.dataprepper.plugins.kinesis.source.KinesisService - Caught exception when initializing KCL Scheduler. Will retry
````

**Environment (please complete the following information):**

Data Prepper 2.10.0

### PR DESCRIPTION
**Pull request by sb2k16**
### Description
This PR is to address the dependency conflict in Kinesis Source plugin. It looks there is a conflict of AWS Sdk Kinesls Client dependency which was breaking the plugin functionality. 
 

Resolves #5084 

### Check List
- [X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dlvenable — APPROVED** [review]
Thank you @sb2k16 !

File: data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java [hunk 1]
```diff
@@ -138,7 +138,7 @@ public Scheduler getScheduler(final Buffer<Record<Event>> buffer) {
             try {
                 scheduler = createScheduler(buffer);
             } catch (Exception ex) {
-                LOG.error("Caught exception when initializing KCL Scheduler. Will retry");
+                LOG.error("Caught exception when initializing KCL Scheduler. Will retry", ex);
```
Comment (san81) [inline data-prepper-plugins/kinesis-source/src/main/java/org/opensearch/dataprepper/plugins/kinesis/source/KinesisService.java:141]: Thanks for adding ex to this message. Also, please add NOISY flag for this message.

**Review by kkondaka — DISMISSED** [review]

**Review by san81 — APPROVED** [review]

**Review by dlvenable — APPROVED** [review]
