### PR TITLE
FIX: deal with event with object size zero

### LINKED ISSUE #3727: [BUG] S3 source processes SQS notification when S3 folder is created
**Describe the bug**
There is a confusion in s3 source users when source receives notification from SQS on creating S3 folder. S3 sources processes this notifications and tries to get the object from folder, which results in 0 records being created and also logging a warning message along with incrementing `s3ObjectNoRecordsFound` metric.
`Failed to find any records in S3 object: s3ObjectReference=[bucketName=bucket-name, key=folder-name/].`

**To Reproduce**
1. Go to S3
2. Create a folder
3. Check notification in SQS
4. Start a pipeline with that notification
5. You will see the following warning log 
`Failed to find any records in S3 object: s3ObjectReference=[bucketName=bucket-name, key=folder-name/].`

**Expected behavior**
There shouldn't a log that there are no records found in that key, but instead we should skip `getObject` call on this key or have a different log message that it's a folder.

There are couple of ways we can achieve this,
1. Check the object size, it's 0 for folders and objects with zero objects. We already deserialize the SQS notification to `S3EventNotification` which contains size.
https://github.com/opensearch-project/data-prepper/blob/b6e38a77a7aacba7280728890df72197bd7ccd8d/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/S3EventNotification.java#L90
2. Validate if key ends with `/`, I don't see that you can create a key with `/` in the key name. 

We can achieve this by doing the following [here](https://github.com/opensearch-project/data-prepper/blob/6dc1d12a4b84ade389d7cc311799363e3ea3114d/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java#L218) 
```
    if (s3SourceConfig.getNotificationSource().equals(NotificationSourceOption.S3)
         && !parsedMessage.isEmptyNotification()
         && isS3EventNameCreated(parsedMessage)
        && !parsedMessage.getObjectKey().endsWith("/")) {
```

### PR DESCRIPTION
**Pull request by chenqi0805**
### Description
This PR fixes parsing on empty folder creation S3 event in s3 source by skipping the zero size object processing.
 
### Issues Resolved
Resolves #3727 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java [hunk 1]
```diff
@@ -53,6 +53,7 @@ public class SqsWorker implements Runnable {
     static final String SQS_MESSAGES_DELETED_METRIC_NAME = "sqsMessagesDeleted";
     static final String SQS_MESSAGES_FAILED_METRIC_NAME = "sqsMessagesFailed";
     static final String SQS_MESSAGES_DELETE_FAILED_METRIC_NAME = "sqsMessagesDeleteFailed";
+    static final String ZERO_SIZED_OBJECT_COUNT_METRIC_NAME = "zeroSizedObject";
```
Comment (asifsmohammed) [inline data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java:56]: Everything looks good to me except the metrics name. All the s3 metrics starts with `s3` or `s3Object`. It can be `s3ObjectsWithSizeZero` or `s3Zero SizedObjects` or if you have any other suggestions.

Or we already have `s3ObjectSizeBytes` metric, so it can be `s3ObjectSizeZeroBytes`.

**Review by asifsmohammed — CHANGES_REQUESTED** [review]

**Review by oeyh — APPROVED** [review]

File: data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java [hunk 2]
```diff
@@ -53,6 +53,7 @@ public class SqsWorker implements Runnable {
     static final String SQS_MESSAGES_DELETED_METRIC_NAME = "sqsMessagesDeleted";
     static final String SQS_MESSAGES_FAILED_METRIC_NAME = "sqsMessagesFailed";
     static final String SQS_MESSAGES_DELETE_FAILED_METRIC_NAME = "sqsMessagesDeleteFailed";
+    static final String S3_OBJECTS_WITH_SIZE_ZERO_METRIC_NAME = "s3ObjectsWithSizeZero";
```
Comment (dlvenable) [inline data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/s3/SqsWorker.java:56]: Would `s3ObjectsEmpty` be a clearer and more concise name?

**Review by dlvenable — APPROVED** [review]

**Comment by dlvenable** [comment]
@chenqi0805 , Should we backport this to 2.6.1?
